### ISSUE TITLE
cf-210011: 'set-env' bombs with a request to open a defect

### ISSUE THREAD

**Issue by KrisKobylinski** [cloudfoundry/cli#617] opened 2015-10-06 20:17 UTC
kriskobylinski$ cf set-env monips CLIENTS 5

Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf set-env monips CLIENTS 5

	using this version of the CLI:

		6.12.4-b4b6af1

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0xe1b3c8, 0xc2081ce200)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0xe1b800, 0xc2082667e0, 0x9051e0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0xe1b5a0, 0xc2082869f0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:253 +0x2f0
	github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse(0xe1b800, 0xc2082667e0, 0x9051e0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0xe1b5a0, 0xc2082869f0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:271 +0x92
	github.com/cloudfoundry/cli/cf/net.Gatewa

**Comment by nicw** [comment] 2015-10-27 22:11
@KrisKobylinski can you try this with version 6.13? I wasn't able to reproduce it. Thanks!

**Comment by dkoper** [comment] 2015-11-03 03:04
Also, can you let us know if it happens all the time or only once, with any command or only `cf setenv`, on any computer or only one, etc. - any details that could help us pin-point the cause?

Cheers
* CLI team

**Comment by dkoper** [comment] 2015-11-07 22:11
Closing this issue as we have not enough details to investigate. Feel free to reopen if you encounter the issue again on the latest cf cli release and can provide more details.

* CLI team

**Closed by dkoper** 2015-11-07 22:11 UTC
