### ISSUE TITLE
"index out of range" error while logging to Predix with CLI

### ISSUE THREAD

**Issue by AnandChapekar** [cloudfoundry/cli#865] opened 2016-06-19 15:48 UTC
I am developing HellowWorld app for Predix as per link
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1569&tag=1719&journey=Hello%20World&resources=1475,1569,1523

The command prompt in/out on my Windows 7 Professional SP1 64-bit laptop as below.

Please check.
Thx,
Anand

E:\GE-Predix\HelloWorld\predix-nodejs-starter>set CF_TRACE=true
E:\GE-Predix\HelloWorld\predix-nodejs-starter>cf login -a API Endpoint
API endpoint: API

REQUEST: [2016-06-19T20:47:11+05:30]
GET /v2/info HTTP/1.1
Host: API
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / windows

REQUEST: [2016-06-19T20:47:17+05:30]
GET /v2/info HTTP/1.1
Host: API
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / windows

        Something unexpected happened. This is a bug in cf.

        Please re-run the command that caused this exception with the environment
        variable CF_TRACE set to true.

        Also, please update to the latest cli and try the command again:
        https://github.com/cloudfoundry/cli/releases

        Please create an issue at: https://github.com/cloudfoundry/cli/issues

        Include the below information when creating the issue:

                Command
                cf login -a API Endpoint

                CLI Version
                6.19.0+b29b4e0

                Error
                runtime error: index out of range

                Stack Trace
                        goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
       /tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:189 +0xa0
        main.handlePanics(0x3342aa20, 0x11d39180, 0x3342a9f8, 0x11d17260)
                /tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:173 +0x198
        panic(0xb15440, 0x1195c008)
                /usr/local/go/src/runtime/panic.go:443 +0x3fd
        github.com/cloudfoundry/cli/cf/net.getBaseDomain(0x11d15160, 0x12, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:106 +0x101
        github.com/cloudfoundry/cli/cf/net.(*client).checkRedirect(0x119836b0, 0x11cfa0e0, 0x11c9a028, 0x1, 0x2, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:53 +0x196
        github.com/cloudfoundry/cli/cf/net.(*client).(github.com/cloudfoundry/cli/cf/net.checkRedirect)-fm(0x11cfa0e0, 0x11c9a028, 0x1, 0x2, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:38 +0x4c
        net/http.(*Client).doFollowingRedirects(0x11d316c

### Platform Details
Windows 7 Professional SP1 64-bit

### Shell
Windows Command Prompt

**Comment by dkoper** [comment] 2016-06-20 02:34
Hi @AnandChapekar,

Did you actually type `cf login -a API Endpoint` or did you type a proper url for "API Endpoint"?
If you did type a proper url, can you show what it looks like? (okay to obfuscate if you don't want it in public, but I'd like to know whether it start with `api.` and how many levels deep the domain is).

Cheers,
Dies Koper
CF CLI PM

**Comment by AnandChapekar** [comment] 2016-06-20 10:51
Hi Dies,

Thanks much for quick revert and apologies for my ignorance.

I used "API Endpoint" as VERBATIM command line input.

Please suggest if following default URL can be used for all Beta apps:
https://api.system.aws-usw02-pr.ice.predix.io

Also please see if the user message for incorrect API endpoint can be more
intuitive instead of cryptic "index out of range".

Hoping not to trouble you with more  beginner issues..

Regards,
Anand

**Comment by dkoper** [comment] 2016-06-20 21:55
Hi @AnandChapekar 

Yes, I'd like to use this oppportunity to add some validation to that field. Thanks for bringing it up!

**Comment by nickwei84** [comment] 2016-08-08 21:28
@AnandChapekar 
We could not reproduce this panic on windows using v6.19.0 of the CLI. Could you please provide the following additional information:
1. what is in your `config.json` file (this should be located in your <homedir>\.cf\config.json
1. any environment variables set for the CLI
1. what version of golang you have installed
1. also list any CLI commands that you ran prior to this panic (if any)
1. please include all lines of the stack trace (if not already there)

Also anything else you can think of related to this panic.

Thanks
Difan and Nick

**Comment by dkoper** [comment] 2016-10-22 00:14
Closing, as I believe the current output is good enough:
```
D:\Users\koperd\Downloads\bin>cf login -a API Endpoint
API endpoint: API

REQUEST: [2016-10-22T11:12:57+11:00]
GET /v2/info HTTP/1.1
Host: API
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.1+b80ba27 / windows


FAILED
Error performing request: Get https://API/v2/info: Service Unavailable
```

**Closed by dkoper** 2016-10-22 00:14 UTC
Labels: unscheduled
