### ISSUE TITLE
6.52: Unable to run `cf push`: "No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint"

### ISSUE THREAD

**Issue by vpicone** [cloudfoundry/cli#2033] opened 2020-08-27 21:27 UTC
- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Our [CI deployment action](https://github.com/carbon-design-system/carbon-website/runs/1038214398) suddenly started failing once `6.52` was released. Nothing else has changed with our deployment config in months. Pinning to `6.51` fixed the issue for us: [successful run after pinning CF to 6.51](https://github.com/carbon-design-system/carbon-website/runs/1038311186?check_suite_focus=true)

**Expected behavior**
Should be able to login with the same credentials as `6.51`

<img width="904" alt="Screen Shot 2020-08-27 at 4 26 11 PM" src="https://user-images.githubusercontent.com/4078018/91496626-11c90280-e882-11ea-96d6-af101c02b9ea.png">

**Comment by vpicone** [comment] 2020-08-27 21:29
Same exact issue happened at the same time in a seperate project. Pinning the `cf` version to `6.51.0` solved the problem: https://github.com/carbon-design-system/carbon-website/commit/bfd3e7af84b31fd4db853529e81dce32df89b509

**Comment by jeffchew** [comment] 2020-08-28 02:25
@vpicone I wish I found this issue 5 hours ago (when you reported it), our team ran into this same issue and discovered that downgrading to `v6.51.0` fixed the issue. Came here to report our findings but you beat me to it!

**Comment by heyjcollins** [comment] 2020-08-28 23:12
Hey there @vpicone - thanks for reporting this issue.
I'm not absolutely sure, but have a hunch that your issue may be related to the fact that we bumped the config as part of the work we did to enable Legacy plugins use Log Cache.

As per the [v6.52.0 release notes](https://github.com/cloudfoundry/cli/releases/tag/v6.52.0),  CLI users that previously targeted and logged into their foundations before updating to the v6.52.0 CLI version may be required to to re-login & target in order to initialize the updated config.

Is this happening outside of your ci pipelines as well - even after re-login & target?

Please let us know once you've got more info.

**Comment by neumannrf** [comment] 2020-08-31 13:00
@heyjcollins Yes, the error described above happens even if I `login` and `target` again. Apparently it _erases_ the config created by these two commands.

**Comment by damache** [comment] 2020-09-02 16:58
we had this issue when running builds in travis.  We had to force 6.51 when installing as a plugin to the the `ibmcloud` cli... `ibmcloud cf install -v 6.51.0 -f`.  any update on a fix?

**Comment by marek5050** [comment] 2020-09-03 15:35
Hello all, 
We are having the same problems here when using our automated CI/CD pipeline.

**Comment by heyjcollins** [comment] 2020-09-03 16:47
Thanks for the responses @marek5050 @damache @l2fprod  @neumannrf @jeffchew @vpicone,

Could you please provide us with the exact commands you're running which lead to this error?

Also - in each of your cases, is there a wrapper on the cf CLI?
We suspect that **may** have something to do with the logging out and logging back in and retargeting solution NOT solving the problem.

**Comment by l2fprod** [comment] 2020-09-03 17:01
@heyjcollins 

In my case, I'm calling `ibmcloud cf apps` -- so yes `ibmcloud` here acts as a wrapper for the CF CLI.

**Comment by damache** [comment] 2020-09-04 11:05
@heyjcollins 

below is our Travis build script and the corresponding log. the `before_deploy` block is where it fails.

[travis_fail.txt](https://github.com/cloudfoundry/cli/files/5174370/travis_fail.txt)
[travis_fail2.log](https://github.com/cloudfoundry/cli/files/5174355/travis_fail2.log)

Logging back in after every command keep it going until I executed an external script to run a blue green deploy to CF.  Then it failed there for the same issue.  Adding the restriction to the 6.51 install fixed the build.

**Comment by nickjameswebb** [comment] 2020-09-08 22:14
Hi IBM friends, we haven't been able to reproduce this with v6.52.0. It's worth noting though that we are using the `cf cli` directly, and not using the `ibmcloud` wrapper. We are unfamiliar with `ibmcloud` so we are wondering if anyone has been able to reproduce this issue with direct CF CLI commands? Also, if anyone could reproduce with `CF_TRACE=true` environment variable set that would help us with debugging. 

cc @a-b

**Comment by archerzz** [comment] 2020-09-15 06:54
The root cause is that staring in CF CLI `6.52.0` the version of config data has been bumped to `v4`. But IBM Cloud CLI is still saving the config data as `v3`. So the config data will be cleared by CF CLI afterwards, thus resulting in `No API endpoint set` error.
We'll fix this by detecting and loading the correct version of config data. Here is the item filed: https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/issues/218

**Comment by archerzz** [comment] 2020-09-15 08:44
Meanwhile, I suggest CF CLI should consider add a warning message when clearing the config, for user experience perspective.

**Comment by JenGoldstrich** [comment] 2020-09-15 15:28
@archerzz This is really good feedback, I think whenever in the future we update the config between versions we'll try and make that a bit less painful, its also good to know that in the future this will break the ibmcloud CLI when we bump config versions, (we should capture that feedback @heyjcollins) For now I am closing this issue since it seems we have a resolution.  Please feel free to re-open it if you feel that I've closed it in error.  

Thanks for reporting this y'all!!

Jenna

**Closed by JenGoldstrich** 2020-09-15 15:28 UTC
Labels: scheduled
