### ISSUE TITLE
cannot install pcfDev - File is not a valid cf CLI plugin binary.

### ISSUE THREAD

**Issue by tryingT** [cloudfoundry/cli#1162] opened 2017-06-10 11:14 UTC
## Command  
cf install-plugin pcfdev-v0.26.0+PCF1.10.0-windows.exe

## What occurred

Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin pcfdev-v0.26.0+PCF1.10.0-windows_NEW.exe? [yN]
: y
dial tcp 127.0.0.1:58160: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary. 

## CLI Version  

cf.exe version 6.27.0+d26b32d.2017-06-08

## Platform & Shell Details  

Windows 7 64 bit
## Any other relevant information  
same happened any other plugin from https://plugins.cloudfoundry.org/

 cf install-plugin -r CF-Community "cflocal"
Searching CF-Community for plugin cflocal...
Plugin cflocal 0.12.0 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin cflocal? [yN]: y
Starting download of plugin binary from repository CF-Community...
= =1=2=.=6=9= =M=i=B= =/= =1=2=.]6 9  9M9i.B6 9[%= =0=s=============================================
==============] 100.00% 15s
dial tcp 127.0.0.1:58553: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED

**Comment by dkoper** [comment] 2017-06-12 18:04
Hi @tryingT 

This is what I see on Windows 7 64 bit:
```
D:\Users\koperd\Downloads\bin\t>cf -v
cf version 6.27.0+d26b32d.2017-06-08

D:\Users\koperd\Downloads\bin\t>cf install-plugin cflocal -r CF-Community
Searching CF-Community for plugin cflocal...
Plugin cflocal 0.12.0 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to uninstall the existing plugin and install cflocal 0.12.0? [yN]: y

Starting download of plugin binary from repository CF-Community...
 12.69 MiB / 12.69 MiB [=============================================================================================] 100.00% 9s
Installing plugin cflocal...
OK
Plugin cflocal 0.12.0 successfully installed.
```

Are you getting the error you see on the previous cf CLI release as well?

Regards,
Dies Koper
CF CLI PM

**Comment by mkc-nick** [comment] 2017-06-15 02:56
I've got same issue on my Windows 7 64-bits platform.

**Comment by dkoper** [comment] 2017-06-15 07:14
@mkc-nick Are you getting the error you see on the previous cf CLI release as well?

**Comment by mkc-nick** [comment] 2017-06-15 07:38
@dkoper Ya, I've got the same error after I exec the pcfdev-v0.26.0+PCF1.10.0-windows.exe on my windows 7 64-bits laptop. Don't figure out why, it seems the installation package got some internal error or something..

**Comment by dkoper** [comment] 2017-06-15 08:11
@mkc-nick Is this plugin somewhere publicly available for me to download and try?
Is there a previous cf CLI version where this binary does work for you?

**Comment by mkc-nick** [comment] 2017-06-15 08:15
@dkoper Just sign up a account in here : https://network.pivotal.io/, once you have signed in ,you will find a PCF Dev download menu. Yon could choose your favorite platform version such as Win, Linux or Mac. But I didn't work out a solution to solve this issue. Hope the Dev team could take a look at this issue. @ @cf-gitbot

**Comment by dkoper** [comment] 2017-06-15 15:04
@mkc-nick I found a file called `pcfdev-v0.26.0+PCF1.10.0-windows.zip`, unzipped to `pcfdev-v0.26.0+PCF1.10.0-windows.exe`:
```
D:\Users\koperd\Downloads\bin>cf install-plugin D:\Users\koperd\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows.exe
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin D:\Users\koperd\Downloads\pcfdev-v0.26.0+PCF1.
10.0-windows.exe? [yN]: y
Installing plugin pcfdev...
OK
Plugin pcfdev 0.26.0 successfully installed.
```

I'll ask my team to see where your error message could come from.

**Comment by XenoPhex** [comment] 2017-06-15 18:27
I haven't been able to reproduce this on my Windows VMs, but there's a good chance that if it's happening on old versions of `cf` that the problem is with the plugin itself. It might be worth contacting the plugin developers for support first.

**Comment by dkoper** [comment] 2017-06-26 21:11
Closing. We believe the issue could be with the plugin and without access to its source code there's nothing we can do to proceed investigating the isue.

**Closed by dkoper** 2017-06-26 21:11 UTC
Labels: scheduled
