### ISSUE TITLE
The repository 'https://packages.cloudfoundry.org/debian stable InRelease' is not signed.

### ISSUE THREAD

**Issue by nishantrajmitra** [cloudfoundry/cli#3198] opened 2024-09-11 12:50 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

**What happened**
cf install-plugin multiapps -f -> failed due to package error

**Expected behavior**
cf command used to run until last week using same commands.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `get -v -O- https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |
          gpg --dearmor |
          sudo tee /etc/apt/keyrings/cloudfoundry.gpg > /dev/null
          ls /dev/null
          echo "deb [signed-by=/etc/apt/keyrings/cloudfoundry.gpg] https://packages.cloudfoundry.org/debian stable main" |
          sudo tee /etc/apt/sources.list.d/cloudfoundry.list
          cat /etc/apt/sources.list.d/cloudfoundry.list
          sudo apt-get update
          sudo apt-get install cf-cli
          cf install-plugin multiapps -f`
2. See error below:
3. Err:12 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease
  The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
Reading package lists...
W: GPG error: https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease: The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
E: The repository 'https://packages.cloudfoundry.org/debian stable InRelease' is not signed.

**Provide more context**
- platform and shell details : ubuntu-latest
- version of the CLI you are running: latest
- version of the CC API Release you are on

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by xbertzx** [comment] 2024-09-11 14:45
We are running into this same issue in our CI/CD Pipelines. Would really appreciate assistance with this.

**Comment by a-b** [comment] 2024-09-11 14:48
Hi there. We're looking into this. It should be resolved soon.

**Comment by sundaramnarayanaswamy** [comment] 2024-09-11 15:40
we have same issue and our production deployment is blocked

**Comment by nishantrajmitra** [comment] 2024-09-11 15:51
Please update if this is done as we are halted.

**Comment by a-b** [comment] 2024-09-11 16:00
The app is now updated; we're waiting for CDN to propagate changes.

**Comment by a-b** [comment] 2024-09-11 16:02
```
curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --import - ; gpg --list-keys | grep expire
gpg: key 172B5989FCD21EF8: "CF CLI Team <cf-cli-eng@pivotal.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pub   rsa4096 2018-09-13 [SC] [expires: 2025-09-11]
sub   rsa4096 2018-09-13 [E] [expires: 2025-09-11]
```
Please let us know if this works for you, too.

**Comment by xbertzx** [comment] 2024-09-11 16:36
I got an error at the bottom of this log.

gpg: directory '/home/vsts/.gnupg' created
gpg: keybox '/home/vsts/.gnupg/pubring.kbx' created
gpg: /home/vsts/.gnupg/trustdb.gpg: trustdb created
gpg: key 172B5989FCD21EF8: public key "CF CLI Team <cf-cli-eng@pivotal.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
pub   rsa4096 2018-09-13 [SC] [expired: 2024-09-10]
uid           [ expired] CF CLI Team <cf-cli-eng@pivotal.io>
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:6 https://packages.microsoft.com/repos/azure-cli jammy InRelease [3596 B]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:8 https://packages.microsoft.com/repos/azure-cli jammy/main amd64 Packages [1804 B]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [15.1 kB]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [42.9 kB]
Get:11 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [172 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1988 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [349 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [17.8 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [2386 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [410 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 c-n-f Metadata [616 B]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1123 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [261 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [26.2 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [43.3 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 c-n-f Metadata [444 B]
Get:23 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1771 kB]
Get:24 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [291 kB]
Get:25 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [13.3 kB]
Get:26 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [2327 kB]
Get:27 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [400 kB]
Get:28 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [584 B]
Get:29 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [901 kB]
Get:30 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [176 kB]
Get:31 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [19.2 kB]
Get:32 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [37.2 kB]
Get:33 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [228 B]
##[debug]Agent environment resources - Disk: / Available 22551.36 MB out of 74244.74 MB, Memory: Used 979.00 MB out of 6921.00 MB, CPU: Usage 78.04%
##[debug]Agent environment resources - Disk: / Available 22549.07 MB out of 74244.74 MB, Memory: Used 1015.00 MB out of 6921.00 MB, CPU: Usage 50.94%
Fetched 13.0 MB in 2s (5352 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cf8-cli

**Comment by cweibel** [comment] 2024-09-11 18:09
May need to add a calendar reminder to rotate the cert.  This problem happened the same time in September 2023 and September 2020.

**Comment by cweibel** [comment] 2024-09-11 18:54
This is a duplicate of https://github.com/cloudfoundry/cli/issues/3194 which was fixed a short time ago

**Comment by a-b** [comment] 2024-09-12 01:54
@cweibel, we had calendar reminders until our recent calendar migration to the new system.

Closing this issue as GPG key is now up to date.

**Closed by a-b** 2024-09-12 01:54 UTC

**Comment by nishantrajmitra** [comment] 2024-09-12 07:00
This issue is fixed, thank you!
