### ISSUE TITLE
CF CLI not working in Visual Studio

### ISSUE THREAD

**Issue by jacalcat** [cloudfoundry/cli#1056] opened 2017-01-11 20:16 UTC
## Command  

cf login

## What occurred

Running the CF CLI in the Package Manager Console and the CLI hangs. Worked OK with normal PowerShell, so there is likely some kind of issue with running in Visual Studio.

## What you expected to occur
To be able to run commends as in PowerShell

## CLI Version  

Recreated with 6.23.0+c7866be-2016-12-22

## CC API Endpoint Version  

2.54.0

## Platform & Shell Details  

Windows

**Comment by dkoper** [comment] 2017-01-15 21:28
Hi @jacalcat 

This may take some time to find/build an environment to reproduce this.
Can you provide more details? Where does it hang? Is there any output whatsoever before it hangs? Can you include the CF trace (add `-v`)?

**Comment by dkoper** [comment] 2017-01-15 21:33
Also, what version of Package Manager Console are you running, and have you tried with the latest? (A quick google search comes up with a number of reported issues with it hanging, and hotfixes that may resolve them)

**Comment by jeffcodotcom** [comment] 2017-01-16 13:14
@dkoper I can send the trace if needed, but we had multiple people on our team replicate this with the community version of Visual Studio, downloaded a few days ago and used version 6.23.0+c7866be-2016-12-22. 

It hung after I typed in this in the Package Manager Console:

cf login -u [user name] -o [org name] -s [space name]

**Comment by dan-kirberger** [comment] 2017-01-20 22:05
Does the package manager console add any network or proxy configuration you might be using for your package management repository?

Are you normally behind a corporate proxy except when using that console?

You can try setting the HTTPS_PROXY environment variable before using the cli to set or clear proxy configuration.

**Comment by dkoper** [comment] 2017-01-21 23:19
@jeffcodotcom Does it hang if you also provide your password on the command line (-p)?

I had a colleague try this and was able to reproduce it. It's not related to proxies, the place it hangs is different, after making a successful call to UAA.

The cf CLI has special code for Windows and Linux to provide the password prompt (which should not echo what you type). Unfortunately, it does not work as expected on all terminals (e.g. cygwin, see https://github.com/cloudfoundry/cli#known-issues), due to missing support in the  Golang libraries we rely on. If this is the issue. I suspect we won't be able to fix this until Golang adds support for it.

That said, it may be worth raising your issue with the Visual Studio package manager project. As you said, it works fine on Powershell.

**Comment by dkoper** [comment] 2018-01-11 05:15
Closing. I believe this is an issue with the VS package manager project but we lack the time & expertise to investigate in detail in the near future.

**Closed** 2018-01-11 05:14 UTC
Labels: unscheduled
