### ISSUE TITLE
cf services bug (empty service guid)

### ISSUE THREAD

**Issue by melnikalex** [cloudfoundry/cli#1365] opened 2018-04-13 22:45 UTC
## Command  

`cf services -v`

## What occurred

```
...
Getting services in org some-org / space some-space as banana...
...
REQUEST: [2018-04-13T15:35:21-07:00]
GET /v2/services/ HTTP/1.1
Host: api.bloop.cf.banana.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-13T15:35:21-07:00]
HTTP/1.1 404 Not Found
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Fri, 13 Apr 2018 22:35:21 GMT
Server: nginx
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 7dfd46bd-0609-4146-76f8-bbc6fca7753d
X-Vcap-Request-Id: 7dfd46bd-0609-4146-76f8-bbc6fca7753d::23a81356-6251-4255-99e5-ece5767a5db9
{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}


Unknown request
FAILED
```

## What you expected to occur
I expected to get a list of services

## CLI Version  
$ cf --version
cf version 6.36.1+e3799ad7e.2018-04-04

## CC API Endpoint Version  

$ cf api
api endpoint:   https://api.bloop.cf.banana.com
api version:    2.65.0

## Platform & Shell Details  
Mac OS X 10.11 iTerm

## Any other relevant information
I believe this commit introduced the bug I'm seeing:
https://github.com/cloudfoundry/cli/commit/de132a5718fa7de11dc73c5bc908074486c54e07#diff-440cd80467c487171bb17ebab2b7f32cR185

Service guid's are always present on service plans, not necessarily on service instances.

**Comment by XenoPhex** [comment] 2018-04-13 23:50
Marking as a dupe of #1362.

The short answer is upgrade your CF instance? We're more explicitly enforcing our minimum supported version, which happens to be right after your current one. See the other issue for more information.

**Closed by XenoPhex** 2018-04-13 23:50 UTC
Labels: unscheduled
