### ISSUE TITLE
Downloading the bits for a package recognizing text only

### ISSUE THREAD

**Issue by jeffpak93** [cloudfoundry/cli#516] opened 2015-07-16 23:34 UTC
Currently, downloading the bits for a package using cf curl /v2/apps/:guid/download doesn't return the same bits as a regular curl. We think this has something to do with the bits being returned in text mode, rather than in binary.

For example, `cf curl /v2/apps/:guid/download | sha1sum` is different than `curl https://api.example.com/v2/apps/:guid/download | sha1sum`.

**Comment by simonleung8** [comment] 2015-10-26 23:07
@jeffpak93 
We couldn't reproduce the issue using OSX.

Curl wasn't able to download the app bits when we used the `curl` command you have posted, we had to manually extract the redirected URL from curl and issue a second curl for the download to work. Both `cf curl` and `curl` produced the same shasum.

**Comment by dkoper** [comment] 2015-11-04 22:55
Closing as not reproducible. Feel free to re-open if you can help us reproduce it with the latest cf CLI release.

* CLI team

**Closed by dkoper** 2015-11-04 22:55 UTC
Labels: bug
