### ISSUE TITLE
"cf push" is consistently reporting "panic: runtime error" on Windows 10 Home 32-bit version

### ISSUE THREAD

**Issue by chengxing1987** [cloudfoundry/cli#1032] opened 2016-12-22 06:16 UTC
Experiencing "runtime error: invalid memory address or nil pointer dereference" with cf-cli-installer_6.22.2_win32.zip on Windows 10 Home 32-bit version.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x52330b]

goroutine 908 [running]:
panic(0xaf1900, 0x11d2e030)
        /usr/local/go/src/runtime/panic.go:500 +0x331
sync/atomic.LoadUint64(0x12134e5c, 0x11f51cf8, 0x12134dc0)
        /usr/local/go/src/sync/atomic/asm_386.s:159 +0xb
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).retryAction(0x12134dc0, 0x11dbf380, 0x121332c0)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:269 +0xa2
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).streamAppDataTo(0x12134dc0, 0x11f4c780, 0x1207c3f0, 0x24, 0x11f44700, 0x326, 0x12137c58, 0x121332c0, 0x79f401)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:188 +0x10c
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).tailingLogs.func2(0x121332c0, 0x12133280, 0x12134dc0, 0x11f4c780, 0x1207c3f0, 0x24, 0x11f44700, 0x326, 0x12137c58, 0x1)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:163 +0xae
created by code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).tailingLogs
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:164 +0x106

**Comment by dkoper** [comment] 2016-12-22 21:47
Duplicate of  #991. This issue has been resolved in cf CLI 6.23.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Closed by dkoper** 2016-12-22 21:47 UTC
Labels: unscheduled
