### ISSUE TITLE
`cf login --sso` should highlight the SSO URL

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/cli#1296] opened 2017-12-27 22:39 UTC
### What version of UAA/CLI are you running?

4.7.2 
cf version 6.32.0+0191c33d9.2017-09-26

### What did you do?

```
$ cf login -a api.cloud.world --sso
API endpoint: api.cloud.orld

One Time Code ( Get one at https://login.cloud.world/passcode )>
```

The `API endpoint: URL` is in bold and bright color, but the link our users actually need, https://login.cloud.world/passcode, is just regular text.

So our users copy/paste the API URL and wonder why they can't log in.

### What did you expect to see? What goal are you trying to achieve with the UAA?

The passcode URL should be clearly visible and obvious link to use. Right now the API url is what users see (and try to click through on). Please make it more obvious which URL users should visit. Thanks!

![image](https://user-images.githubusercontent.com/1211146/34135817-db15bcd6-e430-11e7-8d34-324e996e135b.png)

See also: https://github.com/cloudfoundry/uaa/issues/751

**Comment by dkoper** [comment] 2018-01-05 10:04
Hi @pburkholder 

Note that the exact prompt (`One Time Code ( Get one at https://login.fr.cloud.gov/passcode ): `) is configurable on the server side (in UAA's login server).
If you can think of a suggestion ofa new text prompt that emphasizes to users to use this URL and not the API endpoint to retrieve their one time passcode, please ask your CF operator to update it.

Also, we have a set of stories to address a number of (minor) issues with `login`, including UX inconsistencies with other CLI commands. As part of that work, the API endpoint URL will no longer be displayed in bold/color. It would then look as follows, with no bold or colour styling:

```
D:\Users\koperd\Downloads\bin>cf login --sso
api endpoint:   https://api.fr.cloud.gov
api version:    2.100.0

One Time Code ( Get one at https://login.fr.cloud.gov/passcode ): 
```

The only thing we could look at doing on the CLI side is to parse prompts obtained from the server side and if we detect a text fragment that looks like a URL, try to change its display style. As we have no idea what kind of prompts CF operators are currently using, we'd have to be very confident of the accuracy of our parsing logic that it doesn't cause bad side-effects.
This is something I'd prefer to postpone exploring until we have confirmed that this is still a major issue that cannot be resolved with a revised text prompt and updated styling of the API endpoint.

Regards,
Dies Koper
CF CLI PM

**Comment by pburkholder** [comment] 2018-01-15 22:17
Thanks for the detailed reply, Dies.

Eliminating the styling will help. Does `login` really need to echo the endpoint and version? Or is that doing more harm than good for an initial user experience? I see confusion about this pretty regularly with new users. 

I agree that trying to style what comes back from UAA is tricky. Would it make sense to suppress the API endpoint when using the `--sso` option?

Thanks, Peter

**Comment by XenoPhex** [comment] 2018-05-02 17:51
Hi @pburkholder thanks for raising this issue and for your feedback. We are closing this issue as a won't fix however when we [redo](https://www.pivotaltracker.com/story/show/126256909) the `login` command, we've made a note to review your feedback. We'll reach out to other users but what you are suggesting seems reasonable. Thanks.

**Closed by XenoPhex** 2018-05-02 17:51 UTC
Labels: enhancement, unscheduled
