### ISSUE TITLE
CF 6.10.0 breaks org-users and space-users

### ISSUE THREAD

**Issue by scotttag** [cloudfoundry/cli#361] opened 2015-02-24 16:13 UTC
Output from org-users and space-users in 6.10.0 is blank where it worked in all versions =< 6.9.0:

$ cf -v
cf version 6.9.0-620f841-2015-01-20T18:01:57+00:00

$ cf org-users CHECK-TEST-ORG
Getting users in org CHECK-TEST-ORG as xxx...

ORG MANAGER
  CHECK-TEST-ADMIN

BILLING MANAGER

ORG AUDITOR

$ cf space-users CHECK-TEST-ORG CHECK-TEST-SPACE
Getting users in org CHECK-TEST-ORG / space CHECK-TEST-SPACE as xxx

SPACE MANAGER
  CHECK-TEST-ADMIN

SPACE DEVELOPER
  CHECK-TEST-DEVELOPER
  CHECK-TEST-ADMIN

---------------------------------

$ cf -v
cf version 6.10.0-b78bf10-2015-02-11T22:26:40+00:00

$ cf org-users CHECK-TEST-ORG
Getting users in org CHECK-TEST-ORG as xxx...

ORG MANAGER

BILLING MANAGER

ORG AUDITOR

$ cf space-users CHECK-TEST-ORG CHECK-TEST-SPACE
Getting users in org CHECK-TEST-ORG / space CHECK-TEST-SPACE as xxx

SPACE MANAGER

SPACE DEVELOPER

SPACE AUDITOR

**Comment by jberkhahn** [comment] 2015-02-24 19:51
Hello there,

We're unable to reproduce this - the ouput looks identical to us for 6.10 and 6.9. Could you please rerun this command with CF_TRACE enabled and post the output?

**Comment by scotttag** [comment] 2015-02-24 23:26
So 6.10 CF Trace is here: https://gist.github.com/scotttag/9a58b34dd0d0a502594e

And if you go to revisions on that gist, I've got 6.9 in there as the original revision so you can see the diff between the two: https://gist.github.com/scotttag/9a58b34dd0d0a502594e/revisions

The big difference seems to be that 6.10 isn't sending the GET /Users request starting at line 248 on the diff, which returns the org admin. Not sure why this is

**Comment by simonleung8** [comment] 2015-02-25 01:09
With API version 2.21.0+, there is no longer a need to hit the UAA endpoint to get org users, and that is the difference you are seeing in cli v6.9 vs v6.10

Looking at the trace, the `admin` user does show up as an org manager in cli v6.10, however, the `username` field does not exist, that is why the `Org Manager` shows the user as an empty line.

Are you able to reproduce this issue with another user with org-manager status?

**Comment by scotttag** [comment] 2015-03-08 15:35
Ah... I only seem to get this for UAAC created users (i.e. admins) - not for CF created users... CF created users show up fine in org-users and space-users

**Comment by goehmen** [comment] 2015-03-13 18:39
I talked to the CF Runtime team.  This is the suggested fix:

I think he's missing the configuration: https://github.com/cloudfoundry/cf-release/releases/tag/v196

User collection endpoints now return usernames in the json response details
This feature requires a new uaa client secret to be defined in the deployment manifest.
uaa.clients.cloud_controller_username_lookup.secret
uaa.scim.userids_enabled must be set to true to enable this feature

I'm going to close this issue with that fix but please reopen if this issue isn't resolved with that recommended fix.

**Closed by goehmen** 2015-03-13 18:39 UTC
