### ISSUE TITLE
nil pointer error in cf create-app-manifest 

### ISSUE THREAD

**Issue by bloodyviking** [cloudfoundry/cli#986] opened 2016-10-26 03:20 UTC
```
   Tell us that you ran this command: 

          cf create-app-manifest aviation-dca-world-history-svc

    using this version of the CLI:

            6.12.2-24abed3

    and that this error occurred:

            runtime error: invalid memory address or nil pointer dereference

    and this stack trace:

            goroutine 1 [running]:
    main.generateBacktrace(0x0, 0x0)
            C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xce
    main.handlePanics(0x30a010, 0xc0820d7740)
            C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x1ab
    github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc08217e480, 0xc082175230, 0x24, 0xc082310440, 0x1e, 0xc0821ce9b0, 0xe, 0x0, 0x0, 0x0, ...)
            C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x8c
    github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc08217e480, 0x30ad70, 0xc08216d940)
            C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4d9
    main.main()
            C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:81 +0xcdd

    goroutine 360 [IO wait]:
    net.(*pollDesc).Wait(0xc0821aca70, 0x72, 0x0, 0x0)
            c:/go/src/net/fd_poll_runtime.go:84 +0x4e
    net.
```

**Comment by dkoper** [comment] 2016-10-26 05:17
Looks like a duplicate of #549, which we fixed a long time ago. Please try with the latest cf CLI version.

**Closed** 2016-11-01 01:14 UTC
Labels: unscheduled
