### ISSUE TITLE
[User experience] cf ssh <app> should check if the ssh is enabled for the app 

### ISSUE THREAD

**Issue by Kaixiang** [cloudfoundry/cli#995] opened 2016-11-04 18:10 UTC
High five for submitting a report!  
If you found an issue with the cf CLI, please visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's not fixed already in the latest release.  
To avoid additional back and forth, please include the following details as relevant:

* Command  
cf ssh myapp

* What occurred, incl. error and/or stack trace
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

* What you expected to occur
(there is an assumption here that you know that SSH has been enabled system-wide for your cf installation)

ERROR: ssh for myapp is disabled, please run `cf enable-ssh myapp` or contact your administrator. 

* CLI Version  
6.22.2+a95e24c-2016-10-27

* CC API Endpoint Version  
API version: 2.63.0

* CF Trace, if issue relates to HTTP requests or strange behavior  
run the command with `-v` and paste or attach the trace output

* Platform & Shell Details  
e.g. Mac OS X 10.11 iTerm, Windows 8.1 64-bit with PowerShell, Ubuntu 14.04.3 64-bit with gnome-terminal

* Any other relevant information  
e.g. details of an environment, cf CLI version, flag or value it does work with, DNS/network configuration, etc.

**Comment by dkoper** [comment] 2016-11-07 08:02
We have a few stories open to improve the user experience with ssh access and the interaction of the several related access levels. Thanks for adding this report, it helps us prioritise this work!

**Comment by XenoPhex** [comment] 2018-04-12 22:57
Thanks @Kaixiang for creating this issue. Closing this out and marking it as a duplicate of #742. Please follow #742 for progress on this issue.

**Closed by XenoPhex** 2018-04-12 22:57 UTC
Labels: enhancement, scheduled, user experience
