### ISSUE TITLE
`cf delete-orphaned-routes` can delete routes which are not orphans

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#746] opened 2016-01-29 15:08 UTC
This problem could occur when two users are simultaneously deleting orphaned routes and associating (currently orphaned) routes with applications. The problem is that the CLI checks for orphaned routes _and then_ deletes them (just before which they could have been associated with applications).

I believe this cannot be fixed unless [CC issue 527](https://github.com/cloudfoundry/cloud_controller_ng/issues/527) is implemented.

**Comment by dkoper** [comment] 2016-06-07 14:36
Closing, as I'm not seeing any progress on the CC issue you raised. As you said, not much the CLI can do if the backend doesn't offer it.

**Comment by glyn** [comment] 2016-06-07 16:08
This is important but not urgent, so please could you leave this issue open to keep it on the books. :-)

I said the same about the CC issue and they have left that issue open.

**Comment by glyn** [comment] 2016-06-07 16:35
Closing until the CC has fixed their issue.

**Comment by zrob** [comment] 2017-04-19 20:44
Please see the CC resolution to this in the following story: https://www.pivotaltracker.com/story/show/112675831

**Comment by dkoper** [comment] 2017-05-13 01:23
@zrob Can you provide a link to the relevant apidoc? Looks like a new API?

**Comment by zrob** [comment] 2017-05-15 05:27
@dkoper 
http://apidocs.cloudfoundry.org/258/spaces/delete_unmapped_routes.html

**Comment by dgrizzanti** [comment] 2019-01-07 15:18
Hi All,

I chatted with @abbyachau last week on the CF slack regarding this issue to see if it was still open for contributions. She confirmed that it was so I started taking a look at the implementation. I had a few questions hoping someone from the community can help me out with.

Is the desire here to maintain the existing `cf delete-orphaned-routes` command and update its logic to use the `delete_unmapped_routes` api or replace it with a new `cf delete-unmapped-routes` command? The latter seems more straightforward and gets around the compatibility issues with v6/v7 CLI code, but I wanted to make sure that was ok with those who would be reviewing.

Thanks!

**Comment by abbyachau** [comment] 2019-01-07 18:34
Hi @dgrizzanti it looks like we wanted to update the logic to use the `delete_unmapped_routes` api - not replace it with a different command. I've tagged this with `dev-review` in case the engs has any additional comments.

**Comment by abbyachau** [comment] 2019-02-13 21:23
Hi @glyn thanks again for creating this issue. @dgrizzanti provided a [pull request](https://github.com/cloudfoundry/cli/pull/1543) to us which we believe have addressed the issue you've raised. We plan to release this fix soon. Closing this issue as fixed but please do not hesitate to get in touch if you have any questions/feedback.

**Closed by abbyachau** 2019-02-13 21:23 UTC
Labels: contributions welcome, enhancement, routing, scheduled
