### ISSUE TITLE
proxy with authentication not working

### ISSUE THREAD

**Issue by BernhardDenner** [cloudfoundry/cli#1765] opened 2019-08-23 11:34 UTC
- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Our corporate network policies require us to use a proxy with authentication to access public resources on the internet. Therefore, I usually have to export `http(s)_proxy` environment variable URLs including username and password.
However, CF-CLI is simply ignoring such proxy setting values, while standard `curl` works.

My current workaround is to use a local proxy without authentication, that forwards to the corporate proxy with authentication. This way the CF-CLI works as desired. However, I want to avoid this since it makes things just a bit more complicated ;)

**What happened**
CF-CLI tries to access the target CF API directly.

```
$> export| grep -i _proxy
HTTPS_PROXY=http://user:password@proxy.corp.intern:8000
HTTP_PROXY=http://user:password@proxy.corp.intern:8000
NO_PROXY=192.168.100.5,localhost
http_proxy=http://user:password@proxy.corp.intern:8000
https_proxy=http://user:password@proxy.corp.intern:8000
no_proxy=192.168.100.5,localhost

$> cf login -a https://api.sys.devtest.xxxxx
API endpoint: https://api.sys.devtest.xxxxx
FAILED
Error performing request: Get https://api.sys.devtest.xxxxx/v2/info: dial tcp: lookup api.sys.devtest.xxxxx on 127.0.0.1:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

$> curl https://api.sys.devtest.xxxxx
{
  "links": {
    "self": {
      "href": "https://api.sys.devtest.xxxxx"
    },
    "cloud_controller_v2": {
...
```

**Expected behavior**
CF-CLI is using the proxy with authentication.

**Provide more context**
- platform: Ubuntu 18.04 and 16.04 shell: zsh
- version of the CLI you are running: 6.46.0
- version of the CC API Release you are on: 2.131.0

**Comment by BernhardDenner** [comment] 2019-08-28 08:22
Some additional input from a Windows 7 platform:

Using CF-CLI version 6.40.0:
```
$ export | grep -i _proxy
HTTPS_PROXY=http://user:password@proxy.corp.intern:8000
HTTP_PROXY=http://user:password@proxy.corp.intern:8000
NO_PROXY=192.168.100.5,localhost
http_proxy=http://user:password@proxy.corp.intern:8000
https_proxy=http://user:password@proxy.corp.intern:8000
no_proxy=192.168.100.5,localhost

$ cf --version
cf.exe version 6.40.0+07673feb9.2018-10-08

$ cf api api.sys.devtest.platform.thalesdigital.io
Setting api endpoint to api.sys.devtest.xxxx...
Request error: Get https://api.sys.devtest.xxxx/v2/info: invalid proxy address "http:
//user:password@proxy.corp.intern:8000": parse http://user:password@proxy.corp.intern:8000: invalid URL escape "%j"
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable i
s correctly set. Else, check your network connection.
FAILED
```

Using CF-CLI version 6.46.1:
```
$ cf --version
cf.exe version 6.46.1+4934877ec.2019-08-23

$ cf api api.sys.devtest.xxxx
Setting api endpoint to api.sys.devtest.xxxx...
Request error: Get https://api.sys.devtest.xxxx/v2/info: dial tcp: lookup api.sys.dev
test.xxxx: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable i
s correctly set. Else, check your network connection.
FAILED
```

Hope the helps ;)

**Comment by staylor14** [comment] 2019-08-29 16:01
Hello @BernhardDenner ,
Sorry to hear you are having trouble with this, and thank you for creating this issue.
We admittedly do not have a wealth of experience with HTTP Proxies, but we did a bit here on our end to try and recreate this issue.

We set up to do some troubleshooting yesterday, but it looks like we didn't capture your use case really at all.

Here's what we did yesterday:

We set up a [tinyproxy](https://tinyproxy.github.io/) on a linux development machine (running it on localhost), and were unable to reproduce the reported behaviors.

The closest we got to reproducing one of the failure modes you reported was to unset `http_proxy` and `https_proxy` entirely:
```
○ → unset https_proxy
○ → unset http_proxy
○ → cf api asdf.1111.112.2                                                                                                                                                                                                                                                        
Setting api endpoint to asdf.1111.112.2... 
Request error: Get https://asdf.1111.112.2/v2/info: dial tcp: lookup asdf.1111.112.2 on 127.0.0.53:53: 
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED
```
The problem that you're *actually* reporting is that the CLI is not preserving the authentication parameters required by your real proxy.  We're sorry we missed that in your clearly-written problem description.

I'll work with our PM and Anchor today to see if we can get a bug report prioritized for this.

Thank you for your patience!

Reagards,
Steve && @bwasmith

**Comment by staylor14** [comment] 2019-08-29 17:55
Hi @BernhardDenner!

We've successfully tested against a proxy that requires basic auth.  Setting `https_proxy` with the wrong password fails with a 401 (unauthorized), and using the correct password allows `cf api` to succeed.

`curl` and `cf` both receive a 401 from the proxy with the wrong password, and both are able to communicate with the public resource when providing the proxy with the correct credentials.

This makes us wonder how DNS is working on your network: You're not getting a 401 (unauthorized), you're unable to resolve the name of the public resource:

> $> cf login -a https://api.sys.devtest.xxxxx
API endpoint: https://api.sys.devtest.xxxxx
FAILED
Error performing request: Get https://api.sys.devtest.xxxxx/v2/info: dial tcp: lookup api.sys.devtest.xxxxx on 127.0.0.1:53: **no such host**
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

We're unable to reproduce the behaviors that you are reporting, so we're closing this issue.  If you can obtain more details that might allow us to reproduce the behaviors, please feel free to re-open it.

We have some thoughts on what might help explain what's going on.  However, our team's collective Windows knowledge here is very limited.  We hope the following commands will give you an idea of what to look for on your platform.

`less /etc/resolv.conf` // see if there are rules that may make DNS behave differently
`dig @127.0.0.1 sys.devtest.xxxx` // we suggest using DNS on localhost because of the error above

Regards,
Steve && @a-b

**Closed by staylor14** 2019-08-29 17:55 UTC
Labels: unscheduled

**Comment by abbyachau** [comment] 2019-08-29 19:10
Hi @BernhardDenner I wanted to add that you could also try Cloud Foundry Slack #general to see if anyone there has had the same issue and could provide any insight.
