### ISSUE TITLE
"cf curl" does not refresh auth token

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cli#1108] opened 2017-03-29 18:32 UTC
± zr |master ✓| → cf -v
cf version 6.25.0+787326d95.2017-02-28

When using cf curl I get invalid auth token errors. If I run a command like `cf orgs` and then go back to curl I have a refreshed token.

**Comment by apoydence** [comment] 2018-02-07 18:39
Is this going to be fixed? We are running into this as well.

**Comment by abbyachau** [comment] 2019-01-10 22:57
Hey @poy sorry the delay in response. We've started this work, hopefully it will be in the next release. Please note that the issue is only with CC API V3. Refresh tokens work correctly with CC API V2.

**Comment by abbyachau** [comment] 2019-01-17 02:02
Hi all, this issue's been fixed and will be in our next release. I'm closing this issue as done but do not hesitate to reach out if you have any questions or would like to provide feedback.

**Closed by abbyachau** 2019-01-17 02:02 UTC
Labels: accepted
