### ISSUE TITLE
Support Linux_arm64 binaries

### ISSUE THREAD

**Issue by rafikt1992** [cloudfoundry/cli#2293] opened 2022-07-13 09:26 UTC
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
Developers use the cli on M1 MacBooks via docker. As M1 silicon is ARM64 architecture, Linux_amd64 binaries are needed to run it

**What's the user value of this feature request?**
Devs using the latest MacBook will be able to use cli

**Who is the functionality for?**
Devs using the latest M1 chip macbook or any linux arm machine

**How often will this functionality be used by the user?**
always 

**Who else is affected by the change?**
This should not affect the other versions

**Is your feature request related to a problem? Please describe.**
yes, although it does somehow run on amd64 unlike some other binaries, it does echo some binary 64 libs are missing

**Describe the solution you'd like**
since the cli is build in GO. we can adjust the make file to compile for linux_arm64. Hopefully, nothing else is needed

**Describe alternatives you've considered**
no alternatives

**Additional context**

**Note:**
As of the GA of the v7 CLI, the v6 line is no longer under active development and will be updated only to patch CVEs or fix severe blocking defects with no workarounds.

**Comment by pivotalgeorge** [comment] 2022-07-14 20:16
Hey @rafikt1992, I left a comment on #2279, could you provide an example of the current target not working for you?

**Comment by pivotalgeorge** [comment] 2022-08-16 17:14
@rafikt1992, just following up. Could you add repro. steps?

**Comment by folz-a** [comment] 2022-09-22 09:26
Just a follow up here from a completely different perspective (but directly related to the title):
We would like to use ARM binaries to install to debian linux.

The PR that is linked will allow the binary to be built without adjusting the Makefile on a debian arm docker image.

Reproduceable:
- Download docker buster image on arm64 platform
- Install required libs (partly manually, e.g. go)
- run Make on this repository
  - If the PR is present, the binary can be built (tested only without the lint and test steps)
  - If PR is not present, no binary is built, since the OS is not supported by the Makefile.

This however is still a workaround, since our primary goal is to get a running cf binary within an ARM linux (debian) docker image.

Preferred behavior:
If possible, please also provide arm binaries for (debian) linux, similar to e.g. arm binary for Mac OS X.

**Comment by fwilhe** [comment] 2023-01-31 11:23
So it seems like the linux/arm64 binary can be built using the makefile now but is not published anywhere? This would be useful imo, is there blocker for doing that or has no one considered it important enough so far?

**Comment by gururajsh** [comment] 2024-09-27 17:53
Closing this issue, since arm support has been provided.

**Closed by gururajsh** 2024-09-27 17:53 UTC
Labels: unscheduled, no-issue-activity
