### ISSUE TITLE
cf env *appname* shows number in scientific format

### ISSUE THREAD

**Issue by vmovva** [cloudfoundry/cli#961] opened 2016-09-15 21:23 UTC
User provided service with number longer than 10 digits as value gets converted into scientific format when ` cf env *appname*` is issued.

* Reproduction steps : 
 
  

1. Create a CUPS :  `cf cups longnumbertest -p '{"longNumber":1234567890}'`
2.    Bind it to an application
3.   Perform cf env *appname* 
4.   Notice that output shows something similar to :
        
>  "user-provided": [
>    {
>     "credentials": {
>      "longNumber": 1.23456789e+09
>     },
>     "label": "user-provided",
>     "name": "longnumbertest",
>     "syslog_drain_url": "",
>     "tags": []
>    }
>   ]

Expectation is that cf env would show number in human readable format , 1234567890
**Note:**  cf curl /v2/apps/*appGUID*/env shows human readable number format.

* CLI Version  
cf version 6.21.1+cd086c8-2016-08-18

* CC API Endpoint Version  
235

**Comment by dkoper** [comment] 2016-09-29 01:49
There seems to be a [related limitation in Golang](https://github.com/golang/go/issues/6384).

My team tried fixing it but it required changes in code that is used by a lot of commands, and tests started failing after the change.
If it were a simple fix, we'd do it, but as it seems complicated with high risk of introducing regressions, we won't fix it at this time.
We may revisit this at a major version upgrade when the functionality of related commands can be changed.

Cheers,
Dies Koper
CF CLI PM

**Closed by dkoper** 2016-09-29 01:49 UTC
Labels: delivered, wontfix
