### ISSUE TITLE
Error performing request: Post https://example.com/v2/service_brokers: http: ContentLength=163 with Body length 0

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cli#1231] opened 2017-09-19 02:58 UTC
## Command  

CF_TRACE=true cf create-service-broker async-service-broker a b http://example.com --space-scoped

## What occurred

Error performing request: Post https://example.com/v2/service_brokers: http: ContentLength=163 with Body length 0

## What you expected to occur

service broker created or meaningful error message

## CLI Version  

cf version 6.31.0+b35df905d.2017-09-15

## CC API Endpoint Version  

2.75.0

## CF Trace

[my-hostname]$ CF_TRACE=true cf -v create-service-broker async-service-broker a b http://example.com --space-scoped
Creating service broker async-service-broker in org user@example.com.mx / space dev as user@example.com.mx...

REQUEST: [2017-09-18T19:53:54-07:00]
POST /v2/service_brokers HTTP/1.1
Host: api.system.aws-usw02-pr.ice.predix.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.31.0+b35df905d.2017-09-15 / linux

{"name":"async-service-broker","broker_url":"http://example.com DATA HIDDEN]","space_guid":"060ce343-1d7f-46d8-9536-eeeee251a774"}
FAILED
Error performing request: Post https://example.com/v2/service_brokers: http: ContentLength=163 with Body length 0

## Platform & Shell Details  
debian jessie, bash

**Comment by dkoper** [comment] 2017-09-19 03:17
Did you get this error once, or consistently? Only with this cf CLI version, or also older ones?

**Comment by cppforlife** [comment] 2017-09-19 03:20
this feels like a retry issue. first time request fails because it read the
body, cursor of the body is now at the end. retry happens and tries to read
already read body.

we did a fix in our retryable impl (
https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/request_retryable.go#L54)
to seek if possible.

**Comment by erjoalgo** [comment] 2017-09-19 04:05
I got this consistently from a broker hosted outside of CF

**Comment by combor** [comment] 2018-11-22 16:54
Same here while running CATS:
```
[2018-11-22 16:34:54.54 (UTC)]> cf create-service-broker CATS-1-BRKR-35117fef81b74767 username password https://CATS-1-BRKR-35117fef81b74767.[REDACTED]
Creating service broker CATS-1-BRKR-35117fef81b74767 as paas-test-runner-admin...
FAILED
Error performing request: Post https://api.[REDACTED]/v2/service_brokers: http: ContentLength=176 with Body length 0
```
CF-TRACE output
```
REQUEST: [2018-11-22T16:34:54Z]
POST /v2/service_brokers HTTP/1.1
Host: api.[REDACTED]
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.39.1+efdd631d2.2018-09-18 / linux

{"name":"CATS-1-BRKR-35117fef81b74767","broker_url":"https://CATS-1-BRKR-35117fef81b74767.[REDACTED]","auth_username":"username","auth_password":"[PRIVATE DATA HIDDEN]"}
FAILED
Error performing request: Post https://api.[REDACTED]/v2/service_brokers: http: ContentLength=176 with Body length 0
```

**Comment by georgi-lozev** [comment] 2018-11-23 10:03
Hey, @combor, thank you very much for the comment.

We've recently refactored the `create-service-command` and we think it should solve the problem you see.

The new version is not yet part of an official release, so we could do one of the following.
- Use an [edge CLI binary](https://github.com/cloudfoundry/cli#edge-binaries) to see if the issue still persists
- Wait for the next official CLI release and check if it fixes the problem for you

Please get back to us if none of our suggestions above work for you and the problem is still there with the refactored version.

BR,
Georgi and @ablease on behalf of Services API Team

**Comment by georgi-lozev** [comment] 2018-12-03 13:52
Hi, @combor. Have you tried any of the suggestions above? 
In the meantime there is a new CLI version release.

**Comment by abbyachau** [comment] 2019-04-24 20:49
Hi @erjoalgo @combor  thanks for creating this issue. Please let us know if you are still experiencing this issue, thanks!

**Comment by georgi-lozev** [comment] 2019-05-20 08:58
We're closing the issue.

Please feel free to re-open or create new if the problem still persists.

BR,
Georgi & @nmaslarski

**Closed by georgi-lozev** 2019-05-20 08:58 UTC
Labels: pending-refactor, sapi, unscheduled
