### ISSUE TITLE
cf help doesn't print any help information

### ISSUE THREAD

**Issue by jeffchi** [cloudfoundry/cli#320] opened 2015-01-06 06:03 UTC
Tell us that you ran this command:

                cf help delete

        using this version of the CLI:

                6.8.0-b15c536

        and that this error occurred:

                template: help:2:31: executing "help" at <
>: short write

        and this stack trace:
~~~
                goroutine 1 [running]:
        main.generateBacktrace(0xc08401bf00, 0x3)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:166 +0xac
        main.handlePanics(0x1915d8, 0xc084048ca0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:150 +0x126
        runtime.panic(0x8ffd40, 0xc0841b6320)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/s
rc/pkg/runtime/panic.c:248 +0x11b
        github.com/codegangsta/cli.printHelp(0xc08414f420, 0xab, 0x9b2860, 0xc08
4151c60)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/Godeps/_workspace/src/github.com/codegangsta/cli/help.go:167 +0x192
        github.com/cloudfoundry/cli/cf/app.showCommandHelp(0xc08414f420, 0xab, 0
x9e8160, 0x6, 0x9e7ec0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/app/help.go:376 +0x90
        github.com/cloudfoundry/cli/cf/app.ShowHelp(0xc084047210, 0xab, 0x9b2860
, 0xc084151bd0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/app/help.go:
~~~

**Comment by simonleung8** [comment] 2015-01-10 00:22
Hi,

Unfortunately we are unable to reproduce the problem. Are you still having the problem? Is there additional information you could provide?

Thanks
Simon

**Comment by jberkhahn** [comment] 2015-01-19 19:36
We're going to go ahead and close this. Feel free to reopen if you experience this problem again.

**Closed by jberkhahn** 2015-01-19 19:36 UTC
