### ISSUE TITLE
Creating a normal route with no path fails if a route with a path already exists

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cli#1406] opened 2018-06-22 21:22 UTC
## Summary
If you create a route with a path such as
```
my-app.example.com/api
```
then try to create a route for the same host/domain with no path
```
my-app.example.com
```
then you get the "...route exists in a different space" error message, even though the route does NOT exist in a different space.

## Command

```
▶ cf create-route training example.com -n my-app --path api
Creating route my-app.example.com/api for org Demo / space training as johndoe...
Route my-app.example.com/api has been created.
OK

▶ cf create-route training example.com -n my-app
Creating route my-app.example.com for org Demo / space training as johndoe...
The app cannot be mapped to route my-app.example.com because the route exists in a different space.
FAILED
```

Hmm... that's weird, let's try map-route instead

```
▶ cf map-route my-app example.com -n my-app
Creating route my-app.example.com for org Demo / space training as johndoe...
OK
Adding route my-app.example.com to app my-app in org Demo / space training as johndoe...
OK
```
This seems like a bug

## What occurred

As you can see above, we see the "route exists in a different space" message when the route does not actually exist in another space.

## What you expected to occur

I expect create-route to work just as well as map-route.

## CLI Version

```
▶ cf version
cf version 6.37.0+a40009753.2018-05-25
```

## CC API Endpoint Version

```
▶ cf api
api endpoint:   <REDACTED>
api version:    2.109.0
```

## Platform & Shell Details

macOS High Sierra with iTerm2

**Comment by forbushbl** [comment] 2018-08-03 22:14
I've confirmed that this is still an issue in v6.37.0. We continue to hear reports from users about this issue.

In our organization, it is common to deploy web apps as two separate apps, a frontend app (e.g. coolapp.example.com) and a backend app (e.g. coolapp.example.com/api). If the frontend is deployed first then users don't encounter this bug but if they happen to deploy the backend first then they end up having to work around the issue before they can get the frontend deployed.

Steps to Fail:
```
cf create-route example.com -n coolapp --path /api .  # Succeeds
cf create-route example.com -n coolapp                # Fails
```

Workaround
```
cf create-route example.com -n coolapp                # Succeeds
cf create-route example.com -n coolapp --path /api    # Succeeds
```

The workaround above assumes that no path-based routes with this host/domain are already created. In a space where this isn't the case, here are some other workarounds I can think of are:
1) Deploy the app with --no-route, then use map-route to create the route (because for some reason map-route works even where create-route fails)
2) Delete all path based routes, then create the route with no path, then recreate all the path based routes

**Comment by forbushbl** [comment] 2018-08-03 22:15
Whoops, just meant to provide an update. Sorry for the noise! This is still an issue as of v6.37.0. See details above.

**Comment by abbyachau** [comment] 2018-12-11 21:06
cc @shalako @shubhaat

**Comment by shalako** [comment] 2018-12-19 19:42
I have confirmed the reported behavior and this appears to me to be a bug in CC API. 

```
$ cf create-route test istio-acceptance.routing.cf-app.com -n scoen-tmp --path /foo
Creating route scoen-tmp.istio-acceptance.routing.cf-app.com/foo for org scoen / space test as admin...
Route scoen-tmp.istio-acceptance.routing.cf-app.com/foo has been created.
OK

$ cf create-route test istio-acceptance.routing.cf-app.com -n scoen-tmp -v

...

REQUEST: [2018-12-19T11:35:29-08:00]
GET /v2/routes?q=domain_guid%3A57c74a0d-b146-4f8b-8712-636f4e92ca6c&q=host%3Ascoen-tmp&q=path%3A HTTP/1.1
Host: api.istio-acceptance.routing.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-12-19T11:35:29-08:00]
HTTP/1.1 200 OK
Alt-Svc: clear
Content-Length: 107
Content-Type: application/json;charset=utf-8
Date: Wed, 19 Dec 2018 19:35:29 GMT
Server: nginx
Via: 1.1 google
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: b5c15189-95dd-4944-5429-84b25d0e08bd::f847e654-4bc9-4455-b27b-73c3ac2d0890
{
  "next_url": null,
  "prev_url": null,
  "resources": [],
  "total_pages": 1,
  "total_results": 0
}

REQUEST: [2018-12-19T11:35:29-08:00]
GET /v2/routes/reserved/domain/57c74a0d-b146-4f8b-8712-636f4e92ca6c?host=scoen-tmp HTTP/1.1
Host: api.istio-acceptance.routing.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-12-19T11:35:29-08:00]
HTTP/1.1 204 No Content
Alt-Svc: clear
Date: Wed, 19 Dec 2018 19:35:29 GMT
Server: nginx
Via: 1.1 google
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f13983af-20f0-415c-6f32-08e228230b2b::ec68b858-f561-4940-83d2-12a8ae370ff8
{}


The app cannot be mapped to route scoen-tmp.istio-acceptance.routing.cf-app.com because the route exists in a different space.
FAILED
```

In the second request the CLI receives a response of `204`, which according to [API docs](https://apidocs.cloudfoundry.org/6.7.0/routes/check_a_http_route_exists.html) indicates that route does exist, when it actually does not.

I'll open an issue with CAPI.

**Comment by shalako** [comment] 2018-12-19 19:53
Created CAPI issue https://github.com/cloudfoundry/cloud_controller_ng/issues/1274

**Comment by abbyachau** [comment] 2019-02-07 01:35
Hi @forbushbl (thanks @shalako) we are closing this issue since this is a CC API bug. Please do not hesitate to reopen or create a new issue if that does not fix the issue.

**Closed by abbyachau** 2019-02-07 01:35 UTC
Labels: bug, routing, unscheduled

**Comment by forbushbl** [comment] 2019-02-08 18:49
@abbyachau and @shalako Thanks for looking into the issue and re-opening it against the correct project. I'll follow the CAPI issue.
