### ISSUE TITLE
http: ContentLength=N with Body length 0

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/cli#1015] opened 2016-11-30 20:58 UTC
* Command  

Any command that calls into `gateway.doRequest` where the request fails.

* What occurred, incl. error and/or stack trace

We keep on seeing the cli fail in the following way:

```
Error performing request: Put https://api.coconut.cf-app.com/v2/apps/c8ac7f24-b1b0-4dc3-bdd5-9e4b7d4aefea/bits?async=true: http: ContentLength=56900 with Body length 0
```

* What you expected to occur

The CLI shouldn't fail in this way.

After some quick research it looks like the request object needs to be recreated for ever iteration of the loop here:

https://github.com/cloudfoundry/cli/blob/b1f2484c6cca1e06c4474d5454f991ba4254a856/cf/net/gateway.go#L423-L430

See: http://stackoverflow.com/questions/31337891/net-http-http-contentlength-222-with-body-length-0#answer-31338443

* CLI Version  
built from master

* CC API Endpoint Version  
2.65.0

**Comment by jasonkeene** [comment] 2016-11-30 21:03
Instead of recreating it was pointed out by @nelsam that you could also type assert the `Body` `io.Reader` into an `io.Seeker` and if that is successful you can call `Seek`.

Also, retrying in this way might be a bad idea all together since some of these requests might not be idempotent.

**Comment by XenoPhex** [comment] 2016-12-03 01:49
Thanks for the bug @jasonkeene! It's funny, because I was actually looking at this part of the codebase over the last few weeks for [this story](https://www.pivotaltracker.com/story/show/127286907) and noticed a lot of the stuff you've pointed out. So thanks for confirming a lot of the suspicions I had.

As for fixing the problem, well... that get tricky. We're in the process of refactoring, well, [everything](https://www.pivotaltracker.com/n/projects/892938/search?q=label%3A%22cli-refactor%22) and the [problem's already been fixed in the new code](https://github.com/cloudfoundry/cli/blob/master/api/cloudcontroller/wrapper/retry_request.go). This fix will only affect the refactored commands though, so if you're seeing this issue a lot with a particular command, let us know and we'll move it up in priority.

We're trying to stay away from modifying core parts of the `cf` package as these changes have becoming increasingly unpredictable (eg. regressions after regressions). So my response is that we're not going to fix it; if this becomes a critical bug, reopen this issue and we'll figure out how to proceed.

**Closed by XenoPhex** 2016-12-03 01:49 UTC
Labels: scheduled
