### ISSUE TITLE
cf run-task does not support special characters in app name

### ISSUE THREAD

**Issue by crstamps2** [cloudfoundry/cli#1285] opened 2017-12-12 13:01 UTC
## Command  

`cf run-task app-v0.62.0+2 "bundle exec rake my_task:task['some','params']" -k 1G -m 1G`

## What occurred

```bash
App app-v0.62.0+2 not found
FAILED
```

## What you expected to occur

The task to have ran.

## CLI Version  

cf version 6.33.0+a345ea34d.2017-11-20

## CC API Endpoint Version  

2.82.0

## Platform & Shell Details  

Mac OS X 10.12.6 iTerm

## Any other relevant information  

When running `cf app app-v0.62.0+2`, it is successful and has output.

**Comment by dkoper** [comment] 2017-12-12 21:06
@zrob Our `run-task` and V3 commands don't seem to be able to find an app with a plus sign in their name. The API call we're making is:
`GET /v3/apps?names=app-v0.62.0%2B&space_guids=a034bdd1-f723-4e59-9dfc-4634432576f2`.
It works with the V2 API:
`GET /v2/apps?q=name%3Aapp-v0.62.0%2B&q=space_guid%3Aa034bdd1-f723-4e59-9dfc-4634432576f2`

Are we doing something wrong?

**Comment by zrob** [comment] 2017-12-13 18:53
It looks like you're doing the correct thing.  I was able to reproduce this behavior.  I also tried it with an app that had a different character that needed encoded `a%b`.  When I query for that with `names=a%25b` then I get the correct result.  It seems CC has a bug when `+` is in the query param.

**Comment by zrob** [comment] 2017-12-13 19:00
CAPI story https://www.pivotaltracker.com/story/show/153644785

**Comment by dkoper** [comment] 2017-12-13 20:38
Thanks!
Closing this issue - no changes required on the CLI.
@crstamps2 Please follow the CAPI story instead.

**Closed by dkoper** 2017-12-13 20:38 UTC
Labels: unscheduled
