### ISSUE TITLE
Cannot push app to Predix.io (V6.22.2)

### ISSUE THREAD

**Issue by EagleEatApple** [cloudfoundry/cli#991] opened 2016-11-03 11:53 UTC
I'm using Ubuntu Kylin 16.04 LTS.
When I try to use CF CLI 6.22.2 to push a very simple app to Predix, I get below errors, however, CLI 6.21.0, 6.21.1, 6.22.0, 6.22.1 are working well.
eagle@ubuntu:~/predix/Predix-HelloWorld-WebApp$ cf push
Using manifest file /home/eagle/predix/Predix-HelloWorld-WebApp/manifest.yml

Using stack cflinuxfs2...
OK
Updating app Predix-HelloWorld-WebApp-eagle-tang in org eagle.tang@ge.com / space dev as eagle.tang@ge.com...
OK

Uploading Predix-HelloWorld-WebApp-eagle-tang...
Uploading app files from: /home/eagle/predix/Predix-HelloWorld-WebApp
Uploading 3.2K, 5 files
Done uploading               
OK

Stopping app Predix-HelloWorld-WebApp-eagle-tang in org eagle.tang@ge.com / space dev as eagle.tang@ge.com...
OK

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x816392b]

goroutine 1309 [running]:
panic(0x871dc60, 0x18f24008)
	/usr/local/go/src/runtime/panic.go:500 +0x331
sync/atomic.LoadUint64(0x18f7753c, 0x19487b30, 0x18f774a0)
	/usr/local/go/src/sync/atomic/asm_386.s:159 +0xb
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).retryAction(0x18f774a0, 0x193579c0, 0x19428e80)
	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:269 +0xa2
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).streamAppDataTo(0x18f774a0, 0x19487b20, 0x193fd200, 0x24, 0x19404f00, 0x491, 0x193f28b8, 0x19428e80, 0x18f0ca01)
	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:188 +0x10c
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).tailingLogs.func2(0x19428e80, 0x19428e40, 0x18f774a0, 0x19487b20, 0x193fd200, 0x24, 0x19404f00, 0x491, 0x193f28b8, 0x1)
	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:163 +0xae
created by code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consumer).tailingLogs
	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer/async.go:164 +0x106

**Comment by nickwei84** [comment] 2016-11-04 17:31
@EagleEatApple Thanks for submitting this issue.

To reproduce this panic, we would need to see your manifest file. Can you please share it?

Thanks.

**Comment by EagleEatApple** [comment] 2016-11-05 05:28
@nickwei84 Nick, thanks so much for quick response!
The source is from https://github.com/PredixDev/Predix-HelloWorld-WebApp
I just clone it and modify manifest file a little bit (only application name).
Please find the manifest file below.
My OS is Ubuntu Kylin 16.04.
---
#
#  A basic hello world index.html file
#  This application, and steps to deploy are described in full in the getting started guide on predix.io
#  Step 1 is to change your application name, save, exit, and cf push
#  Step 2 - After you have your application running you can bind to the services below as described on predix.io

applications:
  - name: Predix-HelloWorld-WebApp-eagle-tang
    buildpack: staticfile_buildpack 
    #path: dist
    memory: 256M
    stack: cflinuxfs2

    # Later, to Bind to services, uncomment the section below and enter the service name that you gave, e.g.
    #services:
    #        - my_redis_instance # change this to your redis service instance name
    #        - my_viewsvc_instance # change this to your view service instance name
    # You may set environment variables that your code will read in, e.g.
    #env:
    #  UAA_SERVER_URL: <my-UAA-URL>
    #  REDIS: redis-<num>

**Comment by nickwei84** [comment] 2016-11-07 18:05
@EagleEatApple Can you please provide us the version of the CC API you are using. You can get this information by running `cf api` after you have a api endpoint targeted. This information should looks like `API version: x.xx.x`.

**Comment by nickwei84** [comment] 2016-11-08 00:11
@EagleEatApple the Loggregator team has created a bug for this issue in their [tracker](https://www.pivotaltracker.com/n/projects/993188/stories/133883341)

**Comment by EagleEatApple** [comment] 2016-11-08 10:01
@nickwei84 The version of API is 2.62 which is using by GE Predix now. I also tried v6.22.2 Debian 64 bit on Ubuntu 16.04 (not Ubuntu Kylin 16.04) 64 bit, and it worked well. The issue I reported was v6.22.2 Debian 32 bit.

**Comment by dkoper** [comment] 2016-11-10 00:58
Hi @EagleEatApple, I'm a bit confused with the different combinations you've tried. Can you confirm?

Your OS | cf CLI | `cf push` | Other commands (`cf logs`?)
------------ | ------------- | ------------- | -------------
Ubuntu Kylin 16.04 64 bit | 6.22.2 Debian 64 bit | ? | ?
Ubuntu Kylin 16.04 32 bit | 6.22.2 Debian 32 bit | panic | ?
Ubuntu Kylin 16.04 32 bit | 6.21.x & 6.22.1 Debian 32 bit | works | works
Ubuntu 16.04 64 bit | 6.22.2 Debian 64 bit | works | works
Ubuntu 16.04 32 bit | 6.22.2 Debian 32 bit | ? | ?

Also, does the command always fail at that spot, or is this a one-time or occasional panic?
How about for `cf logs`?

**Comment by EagleEatApple** [comment] 2016-11-14 00:51
@dkoper , sorry for late response and the confusing.
I tried Ubuntu Kylin 16.04 32 bit first, and 6.22.2 Debian 32 bit did not work when I used cf push (after cf login successfully). I tried a few times and the same error were repeated, then I tried 6.21.x & 6.22.1 Debian 32 bit and they worked.
And then I tried Ubuntu 16.04 64 bit	6.22.2 Debian 64 bit, and it worked for both of cf login and cf push

And I did not use cf logs. the commands I used were just "cf login" then "cf push".

**Comment by wfernandes** [comment] 2016-11-16 20:32
@EagleEatApple We are working on this issue. Here is the story for your tracking purposes: https://www.pivotaltracker.com/story/show/133883341

**Comment by XenoPhex** [comment] 2016-11-28 17:35
@EagleEatApple We believe we've finally gotten the fix into our latest (edge) build of the CLI: https://s3-us-west-1.amazonaws.com/cf-cli-releases/master/cf-cli_edge_win32.zip

Would you mind confirming that it worked?

**Comment by hanwsf** [comment] 2016-11-29 14:33
in deepin linux system, I got panic also. then I Tried Ubuntu on laptop, but the os is So stupid for laptop, gave up, using windows now

**Comment by EagleEatApple** [comment] 2016-12-10 03:41
@XenoPhex  Sorry  for my late response, I had a long business trip. I reported the issue on Ubuntu Kylin 16.04 LTS 32 bit OS, not Windows. 
Today I downloaded "Debian 32 bit" v6.22.2 installer from
https://github.com/cloudfoundry/cli/releases
on my Ubuntu Kylin 16.04 LTS 32 bit OS again, and the issue still there.
![kylin32-cf-cli-error-20161210](https://cloud.githubusercontent.com/assets/20390188/21070892/f48edcec-beca-11e6-9a22-8df75eaa3d4f.PNG)
And v6.22.1 "Debian 32 bit" is ok on my Ubuntu Kylin 16.04 LTS 32 bit OS.

**Comment by nickwei84** [comment] 2016-12-12 17:50
@hanwsf Sorry for the late followup.

We are aware of a panic when pushing an application on some 32bit OS systems. We are curious if the panic you encountered is related. To make this determination, can you please provide the following information about the panic you encountered:

- the CLI command you ran that caused the panic
- panic stack trace
- the version of the CLI that you were using
- the version of the OS you are running and whether it's 32/64bit

**Comment by nickwei84** [comment] 2016-12-12 17:58
@EagleEatApple The bug that you reported has been fixed in the latest linux 32bit edge binary [link here](https://s3-us-west-1.amazonaws.com/cf-cli-releases/master/cf-cli_edge_linux_i686.tgz). Apologies for providing you a link to a windows binary earlier.

Version 6.22.2 of the CLI that you used in your latest test does not have this fix and is expected to panic.

**Comment by nevenc-pivotal** [comment] 2016-12-21 22:40
Hi @nickwei84 

Where can we find edge releases for windows 32-bit?
When do you plan on releasing this as a standard 32-bit release?

Thanks,
Neven

**Comment by dkoper** [comment] 2016-12-21 23:30
Hi @nevenc-pivotal 

You can find the Windows 32 bit edge binary download link in [this comment](https://github.com/cloudfoundry/cli/issues/991#issuecomment-263337964) above.
We hope to publish a new release with it later today or tomorrow.

**Comment by nevenc-pivotal** [comment] 2016-12-21 23:44
Thanks @dkoper 

I used this link:
https://cli.run.pivotal.io/edge?arch=windows32&source=github

The version of cf:
cf version 6.22.2+0d48309-2016-12-21

Tested and this latest edge release does not crash CF CLI the way standard 6.22.2 release did.

Thanks for the information!

**Comment by dkoper** [comment] 2016-12-22 03:02
This issue has now been resolved in cf CLI 6.23.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Closed by dkoper** 2016-12-22 03:02 UTC
Labels: accepted, bug, unscheduled

**Comment by nevenc-pivotal** [comment] 2016-12-22 05:45
@dkoper 

Thank you!

Tested and confirmed the new CF version on windows 32-bit:
cf version 6.23.0+c7866be-2016-12-22
