### ISSUE TITLE
run-task `--wait` parameter is missing from cf8

### ISSUE THREAD

**Issue by mogul** [cloudfoundry/cli#2238] opened 2021-12-08 23:20 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

I was trying to run `cf run-task [PARAMS] --wait` to wait for the output before proceeding in a script.

**What happened**
`Incorrect Usage: unknown flag '--wait'`

**Expected behavior**
The command does not error out, and does not return until the task succeeds or fails.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. `brew install cloudfoundry/tap/cf-cli@7`
2. `cf run-task --wait` (errors out because of missing parameters, but no complaints about `--wait`)
4. `brew uninstall cloudfoundry/tap/cf-cli@7`
1. `brew install cloudfoundry/tap/cf-cli@8`
2. `cf run-task --wait` (this is not sufficient parameters to actually run a task, but it demonstrates that `--wait` no longer works in cf8) 
3. See error about the `--wait` parameter
 
**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
  - This was in Ubuntu Linux, using the cf-cli 8 installed via Homebrew (which now supports Linux)
- version of the CLI you are running
  - CF7: `cf version 7.4.0+e55633fed.2021-11-15`
  - CF8: `cf version 8.0.0+e8d41cf8e.2021-09-16`
- version of the CC API Release you are on
  - N/A

See [the Slack thread that precipitated this issue](https://cloudfoundry.slack.com/archives/C032824SM/p1638818105015600) for additional info; note that the --help output and CLI docs site for CF8 will need updating when this fixed as well.

**Comment by mogul** [comment] 2022-01-14 20:16
This is causing problems between teams who share tooling that uses the `cf` CLI... People keep wanting to iterate the tooling to `cf8` when certain tasks are only possible with `cf7`. Any chance it can be addressed soon?

**Comment by stephanme** [comment] 2022-01-19 10:01
+1

Looks like a regression on cf8 especially because cf cli v8 added --wait for many commands: https://github.com/cloudfoundry/cli/releases/tag/v8.0.0

**Comment by mogul** [comment] 2022-02-13 08:20
I'd love to see this fixed in an 8.2.1... Please? At least ahead of 8.3.0?

**Comment by CN91** [comment] 2022-10-18 11:04
is this being picked up??

**Comment by gururajsh** [comment] 2024-09-06 18:10
Thank you @mogul for bringing this up. Since the fix for this issue is in, will close this issue.

**Closed by gururajsh** 2024-09-06 18:10 UTC
Labels: unscheduled
