### ISSUE TITLE
In the CLI, send only JSON to STDOUT by default

### ISSUE THREAD

**Issue by davidfetter** [cloudfoundry/cli#1060] opened 2017-01-27 18:04 UTC
## What occurred

The cf CLI produces a mix of JSON and not-json to STDOUT.  This makes the output difficult to pass on to things that expect only JSON.  The workarounds are fragile and the code to implement them is hard to explain at first glance.  Here's an example, with the fragile, hard-to-understand part in bold:

`cf service-key my-db my-key | `**tail -n +3**` | jq -r '.uri'`

## CLI Version  

By default, "helpful" messages and decoration go to STDERR, while only the JSON payload goes to STDOUT.

## CC API Endpoint Version  

Not relevant.

## CF Trace

Not relevant

## Platform & Shell Details  

All platforms and shells.

## Any other relevant information  

Not applicable

**Comment by dkoper** [comment] 2017-02-04 00:58
Hi @davidfetter 

As my anchor mentioned on Slack, we're working on a proposal to provide json formatted output for all commands, which should also address the issue you point out with `cf service-key`.
We'll share it on CF Dev when ready for review, but I'll make sure I ping you here as well.

Regards,
Dies Koper
CF CLI PM

**Comment by devorbitus** [comment] 2017-05-05 14:49
@dkoper did the JSON formatted output proposal ever take flight, I haven't seen anything and just checking in

**Comment by dkoper** [comment] 2017-05-06 09:16
@devorbitus We wanted to first explore what other issues people have or things we should improve to ease scripting with the CLI, and continue on the JSON output proposal according to its priority in a bigger list.
And then we got side-tracked by a number of features coming from CC.
Hope to get back to this soon.

**Comment by tobias-hd** [comment] 2017-08-17 07:45
@dkoper Since you are asking for feedback, to improve scripting with the cf cli: 
Apart from printing all output as JSON, I'd very much appreciate a --query option on top of the JSON output, to filter out the data that is actually needed. Amazon has this in the aws cli (see https://docs.aws.amazon.com/cli/latest/reference/index.html#cli-aws), and this is a huge improvement over greps, seds, and so on.

**Comment by davidfetter** [comment] 2017-08-17 14:03
@tobias-hd have you looked at `jq` for this kind of thing?  I find it a good bit more powerful than AWS's --query option, and unlike --query, it's always there and consistent.

**Comment by tobias-hd** [comment] 2017-08-20 20:00
@dkoper Thanks a lot for that hint! `jq` indeed looks very promising. Then I'm waiting even more eagerly for the json-output of `cf` :-)

**Comment by XenoPhex** [comment] 2018-04-16 19:08
Hi @davidfetter thanks for creating this. We are closing this issue and marking it as a duplicate of #851. Please do not hesitate to create a new issue if you have any further questions/feedback.

**Closed by XenoPhex** 2018-04-16 19:08 UTC
Labels: unscheduled
