### ISSUE TITLE
Issue with the CLI removing a non-empty directory

### ISSUE THREAD

**Issue by cfjedimaster** [cloudfoundry/cli#1158] opened 2017-06-02 15:25 UTC
## Command  

cf push

## What occurred

Uploading app files from: /mnt/c/Users/ray/Desktop/nodeexample2
Uploading 10.6M, 10980 files
FAILED
Error processing app files: Error uploading application.
remove /tmp/apps473228129/node_modules/eslint/lib/rules: directory not empty

## What you expected to occur

For it not to error. ;)

## CLI Version  

cf version 6.26.0+9c9a261.2017-04-06

## CC API Endpoint Version  

api endpoint:   https://api.ng.bluemix.net
api version:    2.54.0

## CF Trace

Nothing seemed helpful here.

## Platform & Shell Details  

Windows Subsystem for Linux

## Any other relevant information  

If I remove my own node_modules locally, it works.

**Comment by dkoper** [comment] 2017-06-03 01:35
Hi @cfjedimaster

We've seen issues on Windows with deep paths. They seem to have been resolved in Golang 1.8, with which we are currently building (post cf CLI 6.26.0 release).
You could try downloading [an edge release](https://github.com/cloudfoundry/cli#edge-binaries) and see if you can reproduce the issue.
If the issue is still there, we're refactoring the `push` command and trying to avoid the creation of all those temporary files, which should definitely fix it. But that's still some time out.

Regards,
Dies Koper
CF CLI PM

**Comment by cfjedimaster** [comment] 2017-06-05 13:12
I can confirm the edge release helped - thanks.

**Comment by dkoper** [comment] 2017-06-09 01:19
Resolved in 6.27.0. Thanks for confirming on the edge release.
https://github.com/cloudfoundry/cli#downloads

**Closed by dkoper** 2017-06-09 01:19 UTC
Labels: accepted, bug
