### ISSUE TITLE
Cyclical symlinks result in catastrophic failure

### ISSUE THREAD

**Issue by kpsuperplane** [cloudfoundry/cli#943] opened 2016-08-24 19:41 UTC
Wanting to simply work on the static side of a flask application, I created a symlink that happened to create a cyclical folder structure.
- /static
  - css
  - js
  - /static (points to the parent folder).

CF did not handle this well on `cf push`
![capture](https://cloud.githubusercontent.com/assets/4126319/17945293/3582e77a-6a11-11e6-88eb-063ff9c03703.PNG)

**Comment by dkoper** [comment] 2016-08-28 00:33
Hi @kpsuperplane 

What were you expecting to happen?
I wonder, without knowing how much effort it would be to add detection logic and display a better error message, whether it's safe to say people wouldn't intentionally push an app with cyclical symlinks like that (i.e. would include a `.cfignore` file to prevent it being included in the push), and if they did so accidentally, the current error message provides a clear hint for where the issue is.

Regards,
Dies Koper
CF CLI PM

**Comment by kpsuperplane** [comment] 2016-08-28 02:55
@dkoper I forgot the symlink existed when pushing 😛. Your point is fair in that this situation is rather ridiculous, so this should be low on the priority list. But, yes, either ignore on cyclical or some sort of warning would be nice.

**Comment by dkoper** [comment] 2016-09-28 02:14
Thanks for the feedback.
Closing as a "would-be-nice-but-not-likely-to-reach-the-top-of-our-list-in-the foreseeable-future".

**Closed by dkoper** 2016-09-28 02:14 UTC
Labels: unscheduled
