### ISSUE TITLE
cf routes --orglevel Shows routes in all orgs

### ISSUE THREAD

**Issue by stevewallecs** [cloudfoundry/cli#787] opened 2016-03-03 19:12 UTC
### Command

cf routes --orglevel

### CLI Version

cf version 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00

### Error

Running "cf routes --orglevel" as an admin returns routes from all orgs.

### Platform Details

centos 7

### Shell
terminal

**Comment by dkoper** [comment] 2016-03-07 05:08
Hi @stevewallecs,

Can you reproduce it on the latest cf CLI release? If so, can you provide the output of the command as well as CF_TRACE output?
I am not able to reproduce it, neither with cf CLI 6.13.0 nor the latest release.

Regards,
Dies Koper
CF CLI PM

**Comment by stevewallecs** [comment] 2016-03-07 19:25
Hi @dkoper,
Thanks for taking a look at this. I'm unable to provide all the information in the CF_TRACE. There's some sensitive information in the environment variables. Here are some snippets from the log though that show the profile. Notice in the request, the org guid is specified. And then in the output, there's a route listed that's associated with a different orgranization. Something else of note, the domain "int.apps.cfdev1.ux.dg.local" was created to only be visible to a specific org. Which is not the org we did the search on.

Some specific details I notice:
1) The command is executed with organization_guid:8e9745c8-07b0-458d-9f75-71aa0d6c37fd
2) The owning org guid for the app with the listed route is "owning_organization_guid": "49441c61-f8f6-4bbb-83a3-4b0e2a186f8c"

This looks like a smoking gun. Why is a route listed with the owing_organization_guid differs from the organization_guid specified in the "GET"?

[orglevelsnippet.txt](https://github.com/cloudfoundry/cli/files/161941/orglevelsnippet.txt)

**Comment by dkoper** [comment] 2016-03-08 05:21
What is your CF/CC version?

**Comment by dkoper** [comment] 2016-03-08 21:02
Hi @stevewallecs 

`cf share-private-domain` allows you to share a private domain with other organizations. In this case, the route's owing_organization_guid differs from the organization_guid specified in the "GET".

I don't see anything suspicious or wrong in the trace. If you do, I suggest opening an issue in the Cloud Controller's issue tracker because they're more familiar with the response content?

**Comment by dkoper** [comment] 2016-03-17 21:43
Closing as we have no new information to investigate further.

**Closed by dkoper** 2016-03-17 21:43 UTC

**Comment by jregehr** [comment] 2017-05-25 20:12
Please re-open. This issue is still present in cf CLI v 6.25.0+787326d95.2017-02-28

If you execute cf routes --orglevel it is showing routes for all the orgs in the foundation.

**Comment by dkoper** [comment] 2017-12-18 05:18
@jregehr Comments on a closed issue are easily missed. Please submit a new issue and attach CF trace to it to help us investigate.
