### ISSUE TITLE
Inconsistent hostname naming behavior between push/map/create

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/cli#1386] opened 2018-05-24 23:24 UTC
## Command  

`cf push myapp -n CRAZYTOWN`  and `cf map-route myapp -n CRAZYTOWN`

## What occurred

`push` downcased the hostname whereas `map-route` maintained the custom casing supplied.

## What you expected to occur

The casing is consistently downcased (based on push being the gold standard / pattern we have used).

## CLI Version  

cf version 6.36.1+e3799ad7e.2018-04-04

## CC API Endpoint Version  

2.113.0

## Platform & Shell Details  

OSX 10.13.4 / regular ol bash

## Any other relevant information  

We've clearly got the downcasing behavior for push [here](https://github.com/cloudfoundry/cli/blob/ffee70cca68ab15df71f48641f6fa3bb007c4a2b/cf/commands/application/push.go#L477-L482) but we do not downcase anywhere else.

**Comment by abbyachau** [comment] 2018-05-25 17:57
Note: This appears to work as intended (uppercase hostname is preserved on `push`) on `cf version 6.28.0+9e024bdbd.2017-06-27`. However `cf version 6.37.0+3caf345b3.2018-05-21` on `push`, the hostname is pushed as lowercase. Marking as a bug for eng review.

**Comment by liuxh0** [comment] 2019-11-20 20:53
Hi,
I noticed this "good first issue" and want to start to contribute.
Since this issue has been opened long time ago, I want to ask if this is still waiting to be fixed.

**Comment by heyjcollins** [comment] 2020-05-20 19:49
Thanks for your contribution @liuxh0. 
We've merged #1853  so I'm going to close this issue.

**Closed by heyjcollins** 2020-05-20 19:49 UTC
Labels: Easy, bug, routing, unscheduled
