### ISSUE TITLE
The host is taken (can not cf push from trial orgs)

### ISSUE THREAD

**Issue by danfein** [cloudfoundry/cli#1360] opened 2018-04-05 19:55 UTC
## Command  

cf push (using the cf-spring demo app)

## What occurred

"The host is taken: cf-spring-friendly-numbat"
+failed on multiple concurrent pushes with different random names

![screen shot 2018-04-05 at 12 02 46 pm](https://user-images.githubusercontent.com/4053985/38388396-fa938518-38cf-11e8-9d63-f2dfb3e43b74.png)

## What you expected to occur

app to upload
(cf-spring demo app)

## CLI Version  

cf version 6.36.0+eca59e5b8.2018-04-02

## CC API Endpoint Version  

2.107.0

## Platform & Shell Details  

osx 10.13.4 + iTerm

## Any other relevant information  

Note, this happened repeatedly at different times, on two different accounts that were on a trial account org. In both cases, a second org was created and the problem stopped.

**Comment by shydictator** [comment] 2018-09-19 07:52
I renamed the folder from which I 'cf push' and it goes. And even after rename it backward it goes anyway. Tricky thing.

**Comment by rrafaelpaz** [comment] 2018-11-30 00:15
Changing the folder name also worked for me. cheers @shydictator

**Comment by abbyachau** [comment] 2018-11-30 01:48
Thank you @shydictator for providing a workaround, really appreciate that.

**Comment by tauinger-de** [comment] 2018-12-05 08:58
I simply tried again and again and then it worked. Seems like the random keywords in the route conflict.

**Comment by abbyachau** [comment] 2019-02-12 22:36
Thanks @danfein and everyone who has commented, we are looking into this issue and hope to have a fix soon.

**Comment by aquaraga** [comment] 2019-02-15 10:32
I presume the more correct workaround is to modify the application name in the manifest.yml. Change it from "cf-spring" to "cf-<your user name>" and give it a try.

**Comment by willmurphyscode** [comment] 2019-02-21 18:10
Hello everyone,

Thanks for your comments. When running `cf push` with a random route, the CLI will choose a route for you of the form: `<name-of-app>-<random-adjective>-<random-animal>.<cloudfoundry-domain>`. 

Because following this [basic CF tutorial](https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry/deploy-the-sample-app) will always result in pushing an app with the same name, and because these apps tend to live until they run out of free trial, a high percentage of our random-adjective/random-noun pairs are taken, which is the root cause of this error.

@aquaraga 's workaround above seems best to me: after cloning the sample app, edit `manifest.yml` to change the name of the app.

We're considering adding more entropy to the random route generation, to reduce the probability of collisions, but there are actually a few complications here:

1. We don't want to choose a route that is too long, see https://github.com/cloudfoundry/cli/issues/1331
2. We want to choose a route that humans can easily remember
3. We don't want to make API calls to do collision detection or really anything else that would make random route selection slow or error-prone.

We'll probably come up with something that fixes all of these, but it's not at the top of our backlog right now.

In the meantime, please rename the app or choose your own route.

**Comment by willmurphyscode** [comment] 2019-02-28 21:44
Because it seems like people deploying the CF spring demo app as part of training with Cloud Foundry or a Pivotal Web Services free trial are the most likely to experience this issue, we decided to rename the sample app that gets pushed as part of the tutorial: https://github.com/cloudfoundry-samples/cf-sample-app-spring/pull/15

This should reduce the probability of these random route collisions.

If you are experiencing this issue in a different situation, or if you see more random route collisions as part of the PWS free trial, please comment here.

**Comment by abbyachau** [comment] 2019-04-10 16:14
Hi @danfein and folks who have commented, thanks again for letting us know about this issue. I'm closing this as we haven't had any reported issues regarding this in over a month. Please do no hesitate to get in touch if you run into this issue again, thanks again.

**Comment by abbyachau** [comment] 2019-10-24 23:29
Hi everyone, we've heard this has become an issue again so will be looking into a fix. Thanks.

**Closed** 2021-09-01 15:21 UTC
Labels: bug, accepted
