### ISSUE TITLE
Getting running or staging environment variable groups panics

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cli#535] opened 2015-08-04 20:23 UTC
If the running or staging environment variable group is null:

`cf set-staging-environment-variable-group 'null'`

```
cf staging-environment-variable-group
Retrieving the contents of the staging environment variable group as admin...


	Aww shucks.

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		interface conversion: interface is nil, not map[string]interface {}
```

**Comment by camelpunch** [comment] 2015-09-16 14:50
Confirmed on master

**Comment by SrinivasChilveri** [comment] 2015-09-23 13:56
Hi @camelpunch  @fraenkel ,

The main reason is the response body is nil from CC & which we are accessing directly without validation. The flow is like this

ListRunning()-->repo.gateway.GetResource(url, &raw_response)--->gateway.PerformRequestForJSONResponse()

In the marshalToEnvironmentVariables(raw_response) function we are accessing the raw_response directly without validation

REQUEST: [2015-09-23T17:11:00+08:00]
GET /v2/config/environment_variable_groups/running HTTP/1.1
Host: api.10.244.0.34.xip.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.3-c0c9a03 / linux

RESPONSE: [2015-09-23T17:11:00+08:00]
HTTP/1.1 200 OK
Content-Length: 4
Content-Type: application/json;charset=utf-8
Date: Wed, 23 Sep 2015 09:11:00 GMT
Server: nginx
X-Cf-Requestid: 99d2ba19-d0ec-4308-4e68-e607c7171fbf
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 8463ccbc-9075-436a-79de-6a910b7d2735::95d68d62-0e89-4f7f-a194-236dc3986737

null

So if just put the validation then it works fine.

Thanks & Regards,
SriniCH

**Comment by camelpunch** [comment] 2015-11-02 17:16
Closing in favour of the Tracker story. Please keep an eye on that for updates.

**Closed by camelpunch** 2015-11-02 17:16 UTC
Labels: bug

**Comment by dkoper** [comment] 2015-11-19 00:11
@fraenkel, @SrinivasChilveri What CF release is this issue still occurring with?
I cannot reproduce the panic with the current CF CLI and CF release. Are there any CF releases commonly used out there that exhibit this issue that it's worth fixing the CLI for?

Cheers,
Dies Koper
CF CLI PM
