### ISSUE TITLE
when app ssh is toggled off, improve error message

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#778] opened 2016-02-25 08:16 UTC
if app ssh is turned off, the command should prompt the user to turn it on rather than resulting in an error message that doesn't indicate how to address the problem. may need to consider whether it's turned off at the space or not, if it is, then another error message would help.

```
$ cf ssh jamesboot
FAILED
This app does SSH access disabled. Please use the 'cf enable-ssh APP_NAME' command.
```
### Command

cf-ssh
### CLI Version

6.15.0+fa1bfe2-2016-01-13
### Error

this is the error that is not actionable enough to give users a hint about what they should do to fix it.

```
$ cf ssh jamesboot
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```
### CC API Version

2.51.0
### Platform Details

e.g. Mac OS X 10.11.3
### Shell

iTerm

**Comment by krishicks** [comment] 2016-02-26 16:51
We could fail early if the application has SSH disabled, and prompt as you suggest.

However, this doesn't ensure that the user will be able to do so and successfully SSH to the application, as was alluded to. The operator may have disabled SSH entirely, and we can't know that they've done so. We *are* able to [detect](http://apidocs.cloudfoundry.org/231/spaces/get_space_summary.html) if the space has it enabled, and maybe that would be helpful.

I think some thought needs to be put into what we can do, what we should do, and how to message what we cannot do. The user may get a little annoyed if we tell them they just need to enable SSH on the application only for it to fail again because the operator has disabled it.

**Comment by abbyachau** [comment] 2018-04-11 18:46
Hi @jbayer, thanks for creating this issue. We are closing this issue and marking it as a duplicate of #742 - please follow the other issue for progress moving forward. 

Note: the error returned from CAPI/Diego is the same for your situation and the other issue. We'll have to determine a clean error message for the overall inaccessibility.

**Closed by abbyachau** 2018-04-11 18:46 UTC
Labels: duplicate, enhancement, pending-refactor
