### ISSUE TITLE
CLI user should be able to enable verbose logging for `cf ssh` as if they were using `ssh -vvv`

### ISSUE THREAD

**Issue by wedrive-rb26** [cloudfoundry/cli#814] opened 2016-04-11 07:20 UTC
### Command

cf ssh
### CLI Version

cf version 6.15.0

While trying to create a tunnel to a backend service, I get a failure to connect:

Error: SSH session allocation failed: write tcp SOMEHOST:SOMEPORT->OTHERHOST:2222: use of closed network connection

I would like to be able to enable more verbose logging to get more context to help me debug the situation.

**Comment by dkoper** [comment] 2016-05-11 06:41
Hi @wedrive-rb26 

I am not sure there is more information we can provide that would be helpful. I'll ask the team to investigate.
Were you able to resolve the failure itself, and can you provide any information on how to reproduce this error, and how to resolve it?

Cheers,
Dies Koper
CF CLI PM

**Comment by tomwhoiscontrary** [comment] 2016-07-27 16:57
I would also like this. I am trying to cf ssh into an app, and it just hangs. Eventually it times out. I have no idea what the problem is. If this was normal SSH, i would keep adding -v until i could see what the problem was.

I set CF_TRACE, and i see lots of detail about the HTTP operations, but nothing about SSH. Perhaps setting CF_TRACE should also enable verbose logging from SSH.

I assume you're using a Go SSH client rather than shelling out to the system SSH client. Perhaps you could add some way to let people use an external SSH client. For example, if you're using an authorized key, you could just print it out and let users use it, rather than starting an SSH session. Then, i could use my normal -v approach.

**Comment by dkoper** [comment] 2016-07-27 22:37
@tomwhoiscontrary 
Can you add output of what the details were that normal SSH displayed with each added -v, up to the point you could see what the problem was?
And can you tell us how we can reproduce this hang so we can experiment with logging more details?

Refer to the following documentation on how to use an external SSH client:
http://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#other-ssh-access

**Comment by tomwhoiscontrary** [comment] 2016-07-29 16:09
@dkoper Thanks for the link to the external SSH client - that's super useful.

Unfortunately, the problem, whatever it was, has now been fixed by cloudops (it was PCF-EU), so i can't produce ssh -v output for comparison. Apparently it was something to do with DNS.

**Comment by abbyachau** [comment] 2018-04-11 21:09
Hi @tomwhoiscontrary, thanks for creating this issue. We are closing it due to inactivity, and it appears your problem was resolved. Please do not hesitate to create a new issue should you have any feedback. Thanks.

**Closed by abbyachau** 2018-04-11 21:09 UTC
Labels: enhancement, user experience

**Comment by tomwhoiscontrary** [comment] 2018-04-11 21:42
I resolved the problem by not using Cloud Foundry any more!
