### ISSUE TITLE
CF CLI on Windows 10 64bit displays password while "cf login"

### ISSUE THREAD

**Issue by karthikgooner** [cloudfoundry/cli#1835] opened 2019-10-29 16:53 UTC
Hello,

I just setup CF CLI on my windows 10 64 bit. While trying to login into our organisation, the password field is showing what the standard input instead of blank (which is how it works on my colleague's macbook terminal).

Env: Windows 10 / git bash 
CF CLI version: 6.47.1

![image](https://user-images.githubusercontent.com/42998530/67789849-f0866280-fa74-11e9-8f3c-45f071e2245f.png)

**Comment by abbyachau** [comment] 2019-10-29 18:52
Hi @karthikgooner thanks for creating this issue. We are reviewing now and will respond soon.

**Comment by JenGoldstrich** [comment] 2019-10-29 20:59
Hi @karthikgooner thanks for reporting this issue!

With the release of CF CLI 6.47.1 we inadvertantly made GitBash work with ```cf login```, in previous releases, cf login would not work at all with GitBash (see known issues).  Our recommendation is to use a different terminal emulator, we were unable to reproduce this in the standard Windows cmd.

Closing this issue, thanks!

**Closed by JenGoldstrich** 2019-10-29 20:59 UTC
Labels: unscheduled
