### ISSUE TITLE
`cf push <app name>` accepts `-` as app name, but other commands don't

### ISSUE THREAD

**Issue by FelisiaM** [cloudfoundry/cli#1571] opened 2019-02-12 12:27 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Accidentally pushed an app with name '-' when trying to access `cf push` help  (ran `cf push - help`). This succeeds and the app can be inspected with `cf app -`. However, other commands (e.g. attempting to delete or rename the app) fail with:

```
FAILED
Incorrect Usage

Invalid flag: -
```

**Expected behavior**
`cf push` should not allow '-' as an app name.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf push -` for an arbitrary app
2. Attempt to delete the app with `cf delete -`
3. See error

**Provide more context**
- Using cf cli version 6.42.0+0cba12168.2019-01-10

cc: @jrmcneil

**Comment by Ema93sh** [comment] 2019-02-12 18:36
Thanks for creating this issue. I was able to reproduce the issue in my machine. It seems to be a problem for unrefactored version of the commands. This should be fixed once the commands are refactored.

@FelisiaM In the meantime, you could use this workaround command to delete the app:
`$ cf curl -X DELETE "/v2/apps/$(cf app - --guid)?async=true&recursive=true"`

@abbyachau

**Comment by bwasmith** [comment] 2020-01-16 18:12
Confirming this has been addressed in the v7 CLI:

```
$ cf -v
cf version 7.0.0-beta.29+947eaab38.2020-01-16

$ cf delete -
Really delete the app -? [yN]: y
Deleting app - in org org / space space as admin...
OK
```

At this point, the CF-CLI is very selectively fixing bugs for v6.

Hope this is acceptable @FelisiaM !

**Closed by bwasmith** 2020-01-16 18:12 UTC
Labels: unscheduled
