### ISSUE TITLE
Redirecting '<' has stopped working on later versions

### ISSUE THREAD

**Issue by venusbb** [cloudfoundry/cli#1325] opened 2018-02-14 10:32 UTC
Redirecting '<' has stopped working on later versions

## Command  

cf push -f < 'commands to make the manifest file'

## What occurred

We have been using this command to generate manifest file, which has information that we don't want to be stored. And this has stopped working in later versions of cli. 

## What you expected to occur

We can redirect the output. 

## CLI Version  

6.34

## CF Trace

cf push -f <(make -s CF_MANIFEST_FILE=xxxxxxx.yml generate-manifest)
Pushing from manifest to org xxxx / space preview as xxxxxx...
Using manifest file /dev/fd/63

Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: buildpack, command, env, instances, memory, routes.
Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.

FAILED
Error reading manifest file:
Invalid manifest. Expected a map
make: *** [cf-deploy-prototype] Error 1

## Platform & Shell Details  

Mac OSX iterm

**Comment by jbpivotal** [comment] 2018-02-22 01:55
@venusbb We recently merged the refactored `v2-push` into `push`. I'm not familiar with `<` for `cf push`. Where did you see that documented? Is there a reference on https://docs.cloudfoundry.org/? I did a quick search and didn't find it.

**Comment by emalm** [comment] 2018-02-22 16:08
@jbpivotal: @venusbb is referring to the "process substitution" feature of Bash and other shells, http://tldp.org/LDP/abs/html/process-sub.html, which allows the shell user to take the output of one command and turn it into something like a "virtual file" that can be used as the input to another command that expects a filename to process. In some sense this is the inverse operation to the `cat` command, which takes a file and prints its contents to stdout: process substitution takes stdout for a process and captures it in one of these virtual files. For example, `echo foo` and `cat <(echo foo)` both print `foo` to stdout, and `diff <(cat a) <(cat b)` is a more complicated way to run `diff a b`.

In any case, I've observed that process substitution is still compatible with v6.34.1 of the CF CLI, using `cf push -f <(cat ../manifest.yml)` as a trivial way to involve process substitution that is equivalent to `cf push -f ../manifest.yml`.

@venusbb, from the `Invalid manifest. Expected a map` error in the CLI output, it could be possible that the `make -s CF_MANIFEST_FILE=xxxxxxx.yml generate-manifest` command does not produce valid YAML output. Could you run `make -s CF_MANIFEST_FILE=xxxxxxx.yml generate-manifest` on its own and paste the output here (with any sensitive information removed, of course), using a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to preserve the formatting? Also, if you separate the manifest-generation step from the push step via `make -s CF_MANIFEST_FILE=xxxxxxx.yml generate-manifest > temp-manifest.yml; cf push -f temp-manifest.yml`, does the push succeed?

Thanks,
Eric, CF Diego PM

**Comment by allait** [comment] 2018-02-23 11:05
@emalm writing the manifest to a file does work and was our original workaround for this issue, which is why we suspected that the problem is with CF CLI and process substitution.

I've looked a bit more into this and I believe this has something to do with `cf push` encountering deprecated features in the manifest (top-level attributes in our case). Here's the simplest manifest that reproduces the issue:
```
---
applications:
- name: test-app
instances: 1
```

This works with `cf push -f manifest.yml`, but raises `FAILED Error reading manifest file: Invalid manifest. Expected a map` when I use it with `cf push -f <(cat manifest.yml)`. This manifest also works with process substitution on CF CLI 6.32.

```
---
applications:
- name: test-app
  instances: 1
```
Works both with `cf push  -f manifest.yml` and `cf push -f <(cat manifest.yml)`.

**Comment by XenoPhex** [comment] 2018-05-02 18:39
Hey @venusbb, thanks for submitting this issue!

We can confirm that this is an issue whenever a manifest contains a deprecated field. This is due to the temporary file descriptor being emptied out due to reading `push` having to read the "manifest" twice.

After reviewing the options on how to fix this issue, we determined the best course of action is no action. Since the issue arises from the use of warned, deprecated fields. The amount of work required for the CF CLI to fix this vs the user just moving the field(s) under the `application` section is too much.

I'd suggest reviewing the [CF CLI manifest documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) on how to adjust your `Makefile` to the most up to date version of the manifest. I don't believe it'll take more than a few minutes to fix your manifest.

Closing as won't fix.

**Closed by XenoPhex** 2018-05-02 18:39 UTC
Labels: unscheduled
