### ISSUE TITLE
slow to upload jar file with many files

### ISSUE THREAD

**Issue by svennela** [cloudfoundry/cli#980] opened 2016-10-17 22:32 UTC
Hi,

Jar file comprised of many small files.
- What occurred, incl. error and/or stack trace
  It take approximately 30 mints to push 50MB jar file. 
- What you expected to occur
  It should take less time around 5 to 10 mints.
- CLI Version  
  e.g. 6.13.0-dfba612 (see `cf -v` output)
  CLI v6.16.1 and the latest v6.22.1 

Thank you,
Sridhar & Derek

**Comment by dkoper** [comment] 2016-10-18 10:36
Hi @svennela 

Is your jar file publicly available somewhere? Or can you email me a link to it?

Cheers,
Dies Koper
CF CLI PM

**Comment by svennela** [comment] 2016-10-18 23:16
Hi Dies,

This is sample jar file. This file does not take quite as long as our real application since the file size is smaller, but it does take a very long time to get to the point of staging/starting the application. It would be interesting to explore the idea of a `--big-file` or `--do-not-expand` flag to `push`.

https://drive.google.com/file/d/0B-cuL30S7IQQLUVoa3hCQlZsOWc/view?usp=sharing

**Comment by dkoper** [comment] 2016-10-19 02:51
I pushed your app from my Windows 7 machine (in Australia) to a test bosh-lite environment running on AWS in the US and it took 4 min (with --no-routes and --no-start).
Copied from trace file:

[2016-10-19T13:11:18+11:00] CLI tries to retrieve the app (to check if it's a new app or an update)
[2016-10-19T13:11:20+11:00] CLI calls the API to create the app
[2016-10-19T13:12:07+11:00] CLI sends a list of sha's of the files in the zip to the resource matching API. (we looked at skipping the checksum logic for smaller files before but saw no significant speed-up). CC returns "no match" response at [2016-10-19T13:12:16+11:00], i.e. in 9 sec.
[2016-10-19T13:13:36+11:00] CLI upload the jar of 27.6M with 40257 files (returns in 84 sec with a job id).
[2016-10-19T13:15:00+11:00] CLI starts polling the job
[2016-10-19T13:15:16+11:00] Response from 4th poll that job completed

A second push (i.e. updating the app above) takes about 3 minutes (5.5M, 40218 files), so resource matching reduces subsequent push time by 25%!

First impressions:
- If pushing this 30MB app (excl. staging and starting) takes 4 min, assuming a 50MB would then take 6 min, but it's taking 30 min. for you, there is so much time spent in staging and starting any improvements we could attain in the CLI could be negligent?
- We investigated before whether skipping the checksumming of <64KB files would speed up the resource matching, and it didn't improve much.
- Not sure what's happening in the 90 sec just before uploading the app bits. If the resource matching API responds that there are no matches, and there are no files in .cfignore to exclude, what are we doing?

**Comment by randomtask1155** [comment] 2016-10-24 22:05
@svennela @dkoper at this point we believe this problem has to do with the CF environment we are uploading to. The file resource_match does not appear to be causing the delay so we are going to look into environmental factors that could be causing the 30 minute upload delay

**Comment by dkoper** [comment] 2016-11-01 01:19
Closing as you indicated the issue is believed not to be with the cf CLI. Feel free to reopen or submit a new issue if there turns out to be a CLI issue after all.
We're planning to refactor the push command to make it easier to maintain and enhance. After/as part of that work we'll consider my findings above and see if we can explore some further performance improvements.

**Closed by dkoper** 2016-11-01 01:19 UTC
Labels: unscheduled
