### ISSUE TITLE
Is it possible to configure a message of the day (MOTD) when someone logins via the CLI?

### ISSUE THREAD

**Issue by pivotal-manuel-morales** [cloudfoundry/cli#1008] opened 2016-11-23 23:47 UTC
Hi,

I am looking for steps to add a dynamic MOTD to the output of the CL LOGIN command. Any and all suggestions are appreciated.

| => cf login -a https://api.local.dev.io --skip-ssl-validation
API endpoint: https://api.local.dev.io

Email> user@test.com
Password> 
Authenticating...
OK

Targeted org dev-org
Targeted space dev-space
       
API endpoint:   https://api.local.pcfdev.io (API version: 2.58.0)
User:           user
Org:            dev-org
Space:         fdev-space

TIA,

Manuel

**Comment by dkoper** [comment] 2016-11-28 22:57
Hi @pivotal-manuel-morales 

The cf CLI does not provide such feature natively and we have no plan to add it.
You could write your own script or alias that prints a MOTD before invoking the cf CLI?

**Comment by mogul** [comment] 2017-06-15 00:11
We're interested in this for the cloud.gov team. Our use-cases include: 

- Informing users of pending maintenance windows
- Informing users of platform updates (eg a pointer to our web-based release notes)
- Informing users when staging apps might fail (see for example, https://github.com/cloudfoundry/cf-release/releases#v263-notices, though ideally the platform itself would handle that messaging)

**Comment by XenoPhex** [comment] 2018-04-16 18:26
Closing this issue and marking it as a duplicate of #901 - @pivotal-manuel-morales please follow the aforementioned github issue for progress on this feature enhancement. Thanks.

**Closed by XenoPhex** 2018-04-16 18:26 UTC
Labels: enhancement, unscheduled
