### ISSUE TITLE
Support for Apple M1 chips

### ISSUE THREAD

**Issue by nirajhx** [cloudfoundry/cli#2131] opened 2021-01-25 10:55 UTC
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
Not able to install on Apple MacBook with M1 chipset 

**What's the user value of this feature request?**
Devs using the latest MacBook will be able to use cli

**Who is the functionality for?**
Devs using the latest M1 chip macbook

**How often will this functionality be used by the user?**
Always

**Who else is affected by the change?**
This should not affect the other versions

**Is your feature request related to a problem? Please describe.**
Trying to install CLI on my M1 chip MacBook, but the installation fails with following error:
```
==> Installing cf-cli from cloudfoundry/tap
cf-cli: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.
```

**Describe alternatives you've considered**
I tried compiling the source code, but that also didn't workout. Got following error:
```
go build -ldflags "-w -s -X code.cloudfoundry.org/cli/version.binarySHA=$(git rev-parse --short HEAD) -X code.cloudfoundry.org/cli/version.binaryBuildDate=$(date -u +"%Y-%m-%d") -X code.cloudfoundry.org/cli/version.binaryVersion=$(cat BUILD_VERSION) " -o out/cf .
# code.cloudfoundry.org/cli/api/cloudcontroller/ccv3/constant
assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1020cf4d8 abi_kind=6 emulation_interval=[0x1020f8df8,0x1020f8e0c) instruction_interval=[0x1020f8de4, 0x1020f8e0c) x86_rip=0x101c91a
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)
```

**Comment by a-b** [comment] 2021-02-05 05:33
Hello @nirajhx, thanks for reporting this issue. Did you tried running our macOS binary using `Rosetta Shell`?

**Comment by nirajhx** [comment] 2021-02-11 08:59
Yeah, binary did work for me. Thanks 😊

**Comment by biolauri** [comment] 2021-05-25 09:15
Could someone re-open this issue? Albeit the workaround with `Rosetta Shell` does work, it'd be very great to have the cf cli native for ARM-based architecture.

**Comment by a-b** [comment] 2021-05-26 19:14
@biolauri do you know if it is possible to transpile (compile the binary for ARM on Linux) Golang for ARM?

**Comment by a-b** [comment] 2021-05-26 20:04
It looks like Apple Silicone is just a normal [ARM](https://github.com/golang/go/issues/38485) we will look into this proposal as we start working on the improvement of our release process next couple of months.

**Comment by biolauri** [comment] 2021-05-27 23:46
Great to hear @a-b! Yes, AFAIK, Apple Silicon is just normal ARM64 architecture.

**Comment by sumitpal-singh** [comment] 2021-06-01 06:39
> Hello @nirajhx, thanks for reporting this issue. Did you try running our macOS binary using `Rosetta Shell`?

Binary did not work for me using the ZSH shell

**Comment by Parovsky** [comment] 2021-08-24 11:23
[This](https://cutecoder.org/software/run-command-line-apple-silicon/) guide is useful for installing Rosetta Shell and Homebrew and after the restart, you can run the command `brew install cloudfoundry/tap/cf-cli`

**Comment by a-b** [comment] 2021-08-24 17:06
Technically now you can compile M1, check [this](https://github.com/cloudfoundry/cli/blob/ef091af950f3f184b9051f85185f212836a5a38a/Makefile#L177-L179)

**Comment by mattreddy3** [comment] 2021-09-21 04:26
Hi all, wondering if this is still on the radar? I unfortunately am not advanced enough to take the information above and compile the binary myself :) so am wondering if it's A. available somewhere or B. still in process or C. off the table?

**Comment by a-b** [comment] 2021-09-22 06:09
While M1 support is not entirely off the radar, I can't give you any specific timeline.

**Comment by mattreddy3** [comment] 2021-09-22 15:07
Got it, thank you for the update. Is there an approach you would recommend for utilizing the CF CLI on ARM containers in the meantime? 

So far my best solution is running an AMD container on my M1-native docker desktop install, but the qemu runs everything so slowly (per Docker's [known issues](https://docs.docker.com/desktop/mac/apple-silicon/)) that i'm better off using my local machine w/rosetta and praying i keep all my global programs/versions in sync.

**Comment by lokhmakov** [comment] 2021-11-17 07:56
Any updates?

**Comment by a-b** [comment] 2021-11-22 21:16
We are working on a new release process, this feature might be bundled or done right after this initiative. One particular question is we do not have the infrastructure to test binary built for M1

**Comment by gmuth** [comment] 2021-12-07 08:05
By default installing via homebrew fails (workarounds may exists):

Cloning into '/Volumes/Toolchain/homebrew/Library/Taps/cloudfoundry/homebrew-tap'...
remote: Enumerating objects: 1929, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 1929 (delta 54), reused 57 (delta 25), pack-reused 1837
Receiving objects: 100% (1929/1929), 248.61 KiB | 1.54 MiB/s, done.
Resolving deltas: 100% (1222/1222), done.
Tapped 9 formulae (25 files, 330.2KB).
**cf-cli: The x86_64 architecture is required for this software.
Error: cf-cli: An unsatisfied requirement failed this build.**

**Comment by lokhmakov** [comment] 2021-12-07 08:37
Temporary solution:

```sh
docker run -it --mount src=`pwd`,target=/home/piper/app,type=bind ppiper/cf-cli:latest /bin/bash
```

**Comment by oarthursilva** [comment] 2021-12-18 17:40
> Temporary solution:
> 
> ```shell
> docker run -it --mount src=`pwd`,target=/home/piper/app,type=bind ppiper/cf-cli:latest /bin/bash
> ```

Thanks, it worked for me.

**Comment by oarthursilva** [comment] 2021-12-18 23:53
Facing an issue while using to connect on postgres by using `ppiper/cf-cli:latest `.

I'm following the wiki https://help.sap.com/viewer/b3fe3621fa4a4ed28d7bbe3d6d88f036/Cloud/en-US/69036a6c0b3b4377a1ae6a1edd084988.html in order to establish connection with Postgres. I'm able to access the container, and establish a ssh conenction with Postgres, but can't connect into DB using DBeaver... always having connectivity issues.

**Comment by onesail** [comment] 2021-12-19 10:33
@oarthursilva, from your description it looks like the cause is **not** related to native support for Apple Silicon.

**Comment by marcosrmendezthd** [comment] 2022-03-15 13:07
any progress on this?

**Comment by AkihiroKitada** [comment] 2022-03-23 06:56
Any progresses on this?

I understand cf cli intel binary for Mac can work on M1 Mac once it's installed based on Rosetta technology. The problem is that users could not install easily cf cli on M1 Mac via Homebrew system unless applying the following kind of trick:
[https://community.pivotal.io/s/article/The-x86-64-architecture-is-required-unsatisfied-requirement-failed-this-build-error-when-installing-cf-CLI-on-an-M1-MacBook](https://community.pivotal.io/s/article/The-x86-64-architecture-is-required-unsatisfied-requirement-failed-this-build-error-when-installing-cf-CLI-on-an-M1-MacBook?language=en_US)

The ideal resolution is to provide ARM64 binary for cf CLI. But, at least, should we work for something to enable M1 Mac users to install cf cli via homebrew easily without any tricks?

**Comment by wanddynosios** [comment] 2022-04-12 06:35
I created a homebrew tap for this, which I will keep manually updated until the official release comes around:
````brew install wanddynosios/tap/cf-cli````

**Comment by the-docta** [comment] 2022-04-12 18:25
WOW. Thanks! The repository https://github.com/wanddynosios/homebrew-tap got a ⭐ 

dunno why this isnt yet added to official builld..

**Comment by a-b** [comment] 2022-04-18 21:34
Our team just finished migrating our release process into GitHub Actions #2265 
As part of this effort, we start building ARM Mac binaries. Our next step will include them into our official homebrew tap.

We discourage using 3rd party taps, to avoid confusion and support issues.

**Comment by jeffreyaggrey** [comment] 2022-05-10 00:11
When will this be resolved.

**Comment by wanddynosios** [comment] 2022-06-04 08:42
@jeffreyaggrey It has been resolved for v8.4.0 and can now be installed via homebrew (see [this commit](https://github.com/cloudfoundry/homebrew-tap/commit/69f268f18ea10a4c8e19c99a8bb209c1ebbcbe7d))

**Comment by rafikt1992** [comment] 2022-07-06 09:16
is it possible to support linux_arm as well

when running docker on M1 Mac. Docker will use linux arm64 instead of amd64. Thus cf for linux_arm64 is needed.

**Comment by a-b** [comment] 2022-07-13 00:52
@rafikt1992 please create a separate GitHub Issue to track your proposal. Would you be open to helping with testing this?

**Comment by a-b** [comment] 2022-07-13 00:56
Closing this issue since Apple ARM are now supported in [V8](https://github.com/cloudfoundry/homebrew-tap/blob/c5c013332493a5636eeb6a4f6dcfc1e4c0b5d5ce/cf-cli%408.rb#L11) and [V7](https://github.com/cloudfoundry/homebrew-tap/blob/c5c013332493a5636eeb6a4f6dcfc1e4c0b5d5ce/cf-cli%407.rb#L11)

### Next steps
- Add Apple ARM support to the plugins.

**Closed by a-b** 2022-07-13 00:56 UTC
Labels: unscheduled

**Comment by rafikt1992** [comment] 2022-07-13 11:32
@a-b 

sure i can help i created a PR and an issue

however i noticed there is already a similar PR 

https://github.com/cloudfoundry/cli/pull/2279
https://github.com/rafikt1992/cli/pull/1

**Comment by niklas1375** [comment] 2022-07-23 13:02
For anyone coming here thinking it still does not work with Homebrew: You'll need to explicitly tell brew to use v8:
```sh
brew install cloudfoundry/tap/cf-cli@8
```

**Comment by sangareddynalla** [comment] 2023-06-30 15:01
Hi,

I am trying to execute the command % brew install credhub-cli
But is giving the error :  credhub-cli: The x86_64 architecture is required for this software.
Error: credhub-cli: An unsatisfied requirement failed this build.

I am using Apple M2 system with  Mac OS : 13.4.1   (ventura)

Please help me how to fix this issue on the Apple M2

**Comment by the-docta** [comment] 2023-06-30 16:26
@sangareddynalla its been a while, but as far as I remember, the brew package has some architecture dependency. but not cli. So just install with x86 version of brew, and use it from your native terminals
