### ISSUE TITLE
cf files gives " Service Unavailable" error

### ISSUE THREAD

**Issue by IkuEisou** [cloudfoundry/cli#829] opened 2016-05-03 09:29 UTC
Hello,
My app has pushed successfully, and works well.
But, when using `cf files`, it gives " Service Unavailable" error. 

### Command

cf files business logs/

### CLI Version

e.g. 6.13.0-e68ce0f  / linux

### Error

> Getting files for app business in org DevBox / space sp_yu as admin...
> FAILED
> Error performing request: Get https://acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io/instance_paths/f514a7a45b184966bba86628f6a562c7?hmac=7e5c8e1fcba90b8e0c26a06ad5eb81c291c9a055c3ac6df30a810bfe148d32f511617a55292dc5da3b6ad453542efe935ca779f12b50e463f7bea474602cf27b&path=logs%!F(MISSING)&timestamp=1462265966: Service Unavailable

### CC API Endpoint Version

API version: 2.40.0

### CF Trace

> REQUEST: [2016-05-03T17:00:59+08:00]
> GET /v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/apps?q=name%3Abusiness&inline-relations-depth=1 HTTP/1.1
> Host: api.10.167.227.48.xip.io
> Accept: application/json
> Authorization: [PRIVATE DATA HIDDEN]
> Content-Type: application/json
> User-Agent: go-cli 6.13.0-e68ce0f / linux
> 
> RESPONSE: [2016-05-03T17:00:59+08:00]
> HTTP/1.1 200 OK
> Content-Length: 5386
> Content-Type: application/json;charset=utf-8
> Date: Tue, 03 May 2016 09:00:59 GMT
> Server: nginx
> X-Cf-Requestid: c30cc32c-14e5-4b85-42f6-fe0b1d64f79d
> X-Content-Type-Options: nosniff
> X-Vcap-Request-Id: d68abbf3-2d2c-4381-5abe-ff0c18cbe8b8::d969ecdc-6f31-4fa4-93cf-89c99fdff168
> 
> {
>   "total_results": 1,
>   "total_pages": 1,
>   "prev_url": null,
>   "next_url": null,
>   "resources": [
>     {
>       "metadata": {
>         "guid": "c0144c15-ab0d-4702-918b-34b1c500002c",
>         "url": "/v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c",
>         "created_at": "2016-05-03T03:26:27Z",
>         "updated_at": "2016-05-03T08:35:17Z"
>       },
>       "entity": {
>         "name": "business",
>         "production": false,
>         "space_guid": "ea3d4dcc-a360-4210-9802-9683add1d814",
>         "stack_guid": "5f96409b-7259-47cb-9558-fcbe0623eb7d",
>         "buildpack": "java_buildpack_offline",
>         "detected_buildpack": null,
>         "environment_json": {
>           "no_proxy": "127.0.0.1,api.10.167.227.48.xip.io,doppler.10.167.227.48.xip.io,hm9000.10.167.227.48.xip.io,uaa.10.167.227.48.xip.io,loggregator.10.167.227.48.xip.io,business.10.167.227.48.xip.io"
>         },
>         "memory": 256,
>         "instances": 1,
>         "disk_quota": 1024,
>         "state": "STARTED",
>         "version": "e4731227-e113-4891-aca3-7d1a7fbc8af1",
>         "command": null,
>         "console": false,
>         "debug": null,
>         "staging_task_id": "e2197d302e7641c6ae73273682740617",
>         "package_state": "STAGED",
>         "health_check_type": "port",
>         "health_check_timeout": null,
>         "staging_failed_reason": null,
>         "staging_failed_description": null,
>         "diego": false,
>         "docker_image": null,
>         "package_updated_at": "2016-05-03T03:26:33Z",
>         "detected_start_command": "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.0_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) &&  JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS=\"-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Daccess.logging.enabled=false -Dhttp.port=$PORT\" $PWD/.java-buildpack/tomcat/bin/catalina.sh run",
>         "enable_ssh": true,
>         "docker_credentials_json": {
>           "redacted_message": "[PRIVATE DATA HIDDEN]"
>         },
>         "space_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814",
>         "space": {
>           "metadata": {
>             "guid": "ea3d4dcc-a360-4210-9802-9683add1d814",
>             "url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814",
>             "created_at": "2016-05-03T03:04:21Z",
>             "updated_at": null
>           },
>           "entity": {
>             "name": "sp_yu",
>             "organization_guid": "e9479108-596b-4ec2-b9ee-5ff21a2d11e0",
>             "space_quota_definition_guid": null,
>             "allow_ssh": true,
>             "organization_url": "/v2/organizations/e9479108-596b-4ec2-b9ee-5ff21a2d11e0",
>             "developers_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/developers",
>             "managers_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/managers",
>             "auditors_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/auditors",
>             "apps_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/apps",
>             "routes_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/routes",
>             "domains_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/domains",
>             "service_instances_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/service_instances",
>             "app_events_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/app_events",
>             "events_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/events",
>             "security_groups_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814/security_groups"
>           }
>         },
>         "stack_url": "/v2/stacks/5f96409b-7259-47cb-9558-fcbe0623eb7d",
>         "stack": {
>           "metadata": {
>             "guid": "5f96409b-7259-47cb-9558-fcbe0623eb7d",
>             "url": "/v2/stacks/5f96409b-7259-47cb-9558-fcbe0623eb7d",
>             "created_at": "2015-11-09T01:50:12Z",
>             "updated_at": null
>           },
>           "entity": {
>             "name": "cflinuxfs2",
>             "description": "Cloud Foundry Linux-based filesystem"
>           }
>         },
>         "events_url": "/v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/events",
>         "service_bindings_url": "/v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/service_bindings",
>         "service_bindings": [
> 
>         ],
>         "routes_url": "/v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/routes",
>         "routes": [
>           {
>             "metadata": {
>               "guid": "ccbb9c64-3e8a-4fd3-a123-be816203d580",
>               "url": "/v2/routes/ccbb9c64-3e8a-4fd3-a123-be816203d580",
>               "created_at": "2016-05-03T03:26:27Z",
>               "updated_at": null
>             },
>             "entity": {
>               "host": "business",
>               "path": "",
>               "domain_guid": "290918c3-4a43-4f2f-a795-572a02c8dec9",
>               "space_guid": "ea3d4dcc-a360-4210-9802-9683add1d814",
>               "service_instance_guid": null,
>               "port": 0,
>               "domain_url": "/v2/domains/290918c3-4a43-4f2f-a795-572a02c8dec9",
>               "space_url": "/v2/spaces/ea3d4dcc-a360-4210-9802-9683add1d814",
>               "apps_url": "/v2/routes/ccbb9c64-3e8a-4fd3-a123-be816203d580/apps"
>             }
>           }
>         ]
>       }
>     }
>   ]
> }
> Getting files for app business in org DevBox / space sp_yu as admin...
> 
> REQUEST: [2016-05-03T17:00:59+08:00]
> GET /v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/instances/0/files/logs/ HTTP/1.1
> Host: api.10.167.227.48.xip.io
> Accept: application/json
> Authorization: [PRIVATE DATA HIDDEN]
> Content-Type: application/json
> User-Agent: go-cli 6.13.0-e68ce0f / linux
> 
> REQUEST: [2016-05-03T17:00:59+08:00]
> GET /instance_paths/f514a7a45b184966bba86628f6a562c7?hmac=35e907e0e7bae7b48e2ffdffaac99b58c4c3f3b6247beb2f822db443f070099ab535f107806bc4afca803914c35dd63410bc07ca4e9cd9046809afdde8e9983b&path=logs%2F&timestamp=1462266059 HTTP/0.0
> Host: acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io
> Accept: application/json
> Authorization: [PRIVATE DATA HIDDEN]
> Referer: https://api.10.167.227.48.xip.io/v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/instances/0/files/logs/
> User-Agent: go-cli 6.13.0-e68ce0f / linux
> 
> REQUEST: [2016-05-03T17:01:20+08:00]
> GET /instance_paths/f514a7a45b184966bba86628f6a562c7?hmac=13fd777fa8c8c94512e1c9cd94a7606e1902d895ad1fec3c5a59a7fc1996b8fa0d49a40104b7c034a360635b9c7576a69e8fc2188c4f90379b76ba2597514891&path=logs%2F&timestamp=1462266080 HTTP/0.0
> Host: acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io
> Accept: application/json
> Authorization: [PRIVATE DATA HIDDEN]
> Referer: https://api.10.167.227.48.xip.io/v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/instances/0/files/logs/
> User-Agent: go-cli 6.13.0-e68ce0f / linux
> 
> REQUEST: [2016-05-03T17:01:41+08:00]
> GET /instance_paths/f514a7a45b184966bba86628f6a562c7?hmac=5d3062624c322e2db108                                                       d1d84d8d3b68cf384319be4b6f91dd8432b4bbeeb6f9078ef7216&path=logs%2F&timestamp=1
> Host: acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io
> Accept: application/json
> Authorization: [PRIVATE DATA HIDDEN]
> Referer: https://api.10.167.227.48.xip.io/v2/apps/c0144c15-ab0d-4702-918b-34b1
> User-Agent: go-cli 6.13.0-e68ce0f / linux
> 
> FAILED
> Error performing request: Get https://acd2aeaba9b141f4a70fb3708fe83249.10.167.                                                       a562c7?hmac=5d3062624c322e2db1089c4987cc041edc7e3a94a14d1752ed2d6bb89c873ee1ef                                                       8ef7216&path=logs%!F(MISSING)&timestamp=1462266101: Service Unavailable

### Platform Details

Ubuntu 14.04.3 64-bit

### Shell

Terminal(putty)

I tried send the same request with curl command like this, but it also failed.

> $ CF_TRACE=true curl -k --get https://api.10.167.227.48.xip.io//instance_paths/ --header "HOST:acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io"  --header "Accept: application/json" --header "User-Agent: go-cli 6.13.0-e68ce0f / linux" --data "hmac=35e907e0e7bae7b48e2ffdffaac99b58c4c3f3b6247beb2f822db443f070099ab535f107806bc4afca803914c35dd63410bc07ca4e9cd9046809afdde8e9983b&path=logs%2F&timestamp=1462266059"
> DEA is unreachable

**Comment by dkoper** [comment] 2016-05-04 00:54
We've seen issues with xip.io not being a stable DNS service. Can you change to use bosh-lite.com instead?

**Comment by IkuEisou** [comment] 2016-05-05 02:18
The 10.167.227.48.xip.io is mapped to the localhost in the hosts file,  so I don't think it will use xip.io DNS service.
And if xip.io was unstable "business.10.167.227.48.xip.io" should not be accessed, but actually it can be accessed.
So it doesn't seem to be caused by the  xip.io.

I don't know why the host of the second request has became "acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io.", 
although I think it should be business.10.167.227.48.xip.io.

It seems that the "acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io." doesn't appear in the hosts file, so when the second request  was sent to the web server on the container,  it can't  reach to that container.

> Getting files for app business in org DevBox / space sp_yu as admin...
> REQUEST: [2016-05-03T17:00:59+08:00]
> GET /v2/apps/c0144c15-ab0d-4702-918b-34b1c500002c/instances/0/files/logs/ HTTP/1.1
> Host: api.10.167.227.48.xip.io
> ...
> REQUEST: [2016-05-03T17:00:59+08:00]
> GET /instance_paths/f514a7a45b184966bba86628f6a562c7?hmac=35e907e0e7bae7b48e2ffdffaac99b58c4c3f3b6247beb2f822db443f070099ab535f107806bc4afca803914c35dd63410bc07ca4e9cd9046809afdde8e9983b&path=logs%2F&timestamp=1462266059 HTTP/0.0
> Host: acd2aeaba9b141f4a70fb3708fe83249.10.167.227.48.xip.io
> ...

**Comment by dkoper** [comment] 2016-06-07 14:15
You'd have to ask the Cloud Controller team to confirm, but possibly the Files API redirects to another hostname that serves the file to you. I don't know if this hostname is always the same - you may not be able to get it to work reliably by adding it to /etc/hosts.
Also, I'm not sure why the trace is not displaying the responses, which could help understand where that host name comes from. The CLI version you use is over 6 months old. You could try on the latest version.

**Comment by dkoper** [comment] 2016-08-01 10:19
Closing. I have confirmed in my local bosh-lite environment that the Files API redirects to a generated hostname, ad that works for me (using bosh-lite.com, not xip.io). Why it is that way is a question for the CAPI team.

**Closed by dkoper** 2016-08-01 10:19 UTC
