### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by ryanmkaplan** [cloudfoundry/cli#789] opened 2016-03-05 20:09 UTC
### Command

cf --version

### CLI Version

lastest

### Error

fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x9e5a20, 0x21)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7fff5fbff7a0 sp=0x7fff5fbff788
runtime.goenvs()
	/usr/local/go/src/runtime/os1_darwin.go:76 +0x8d fp=0x7fff5fbff7c8 sp=0x7fff5fbff7a0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:440 +0xa7 fp=0x7fff5fbff810 sp=0x7fff5fbff7c8
runtime.rt0_go(0x7fff5fbff840, 0x2, 0x7fff5fbff840, 0x0, 0x2, 0x7fff5fbff9f0, 0x7fff5fbff9f3, 0x0, 0x7fff5fbffa35, 0x7fff5fbffa43, ...)
	/usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7fff5fbff818 sp=0x7fff5fbff810

### CF Trace

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

e.g. Mac OS X 10.10.5

### Shell

iTerm

I've tried installing the CLI every way, and still getting the issue.

**Comment by dkoper** [comment] 2016-03-07 05:17
Hi @ryanmkaplan 

Thanks, we'll look into this.
Can you confirm at which release it stopped working? 6.16.0? 6.15.0?

Regards,
Dies Koper
CF CLI PM

**Comment by ryanmkaplan** [comment] 2016-03-07 14:24
@dkoper thanks, it's not working on 6.16; I was told 6.15 works fine

**Comment by cbguder** [comment] 2016-03-09 20:26
@ryanmkaplan we believe this error is happening due to Anti-Virus/Security software. do you have one of the following, or other Anti-Virus/Security software installed?

* McAfee Endpoint Protection for Mac
* Trend Micro Data Loss Prevention
* Websense Endpoint
* Digital Guardian

**Comment by dkoper** [comment] 2016-03-09 23:18
@ryanmkaplan Also, if you temporary disable your antvirus/security software, does cf 6.16.x work?
Knowing that would help us tremendously in pinpointing the cause of the issue.

**Comment by hadesara** [comment] 2016-03-14 18:36
I have the same issue. And the issue persisted even after disabling the McAfee Endpoint Protection for Mac.

**Comment by ryanmkaplan** [comment] 2016-03-16 17:09
@dkoper @cbguder - sorry for the delay. I'm not able to disable McAfee (do not have permissions) but the downgrade is working fine.

**Comment by cbguder** [comment] 2016-03-17 22:51
@ryanmkaplan @hadesara We have built a new binary that we think might fix this issue. Please give it a try and let us know if it fixes the issue you're seeing.

Installer: https://s3.amazonaws.com/go-cli/releases/v6.16.1-2016-03-17/cf-cli-installer_6.16.1_osx.pkg

Binary: https://s3.amazonaws.com/go-cli/releases/v6.16.1-2016-03-17/cf-cli_6.16.1_osx.tgz

**Comment by johnrjacobs** [comment] 2016-03-25 18:51
@cbguder I previously had the same issue as @ryanmkaplan and @hadesara  and the new binary looks like it fixed this issue. Thanks.

**Comment by dkoper** [comment] 2016-03-26 02:06
@johnrjacobs 

Thanks for the confirmation. We have ported the fix into our edge binaries. Any chance you could try out our edge binary as well and confirm the issue is addressed?
https://cli.run.pivotal.io/edge?arch=macosx64&source=github

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment] 2016-04-15 22:59
The fix has been included in cf CLI v6.17.0.
https://github.com/cloudfoundry/cli#downloads

Thanks again!
Dies Koper
CF CLI PM

**Closed by dkoper** 2016-04-15 22:59 UTC
