### ISSUE TITLE
Unmapping route: Something unexpected happened.

### ISSUE THREAD

**Issue by Neumann-Nils** [cloudfoundry/cli#2679] opened 2023-11-29 12:43 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I was trying to delete a destination from a route using the cf curl command. I cannot reproduce this error, it was a one-time problem.

**What happened**
The destination was not deleted from the route and the command exited with an error:

```
Unmapping route with guid <guid> from destination with guid <guid>...
 
Something unexpected happened. This is a bug in cf8.
 
Please re-run the command that caused this exception with the environment
variable CF_TRACE set to true.
 
Also, please update to the latest cli and try the command again:
https://code.cloudfoundry.org/cli/releases
 
Please create an issue at: https://code.cloudfoundry.org/cli/issues
 
Include the below information when creating the issue:
 
Command
cf8 curl /v3/routes/<route-guid>/destinations/<destination-guid> -X DELETE --fail
 
CLI Version
8.7.3+efd1d03.2023-09-12
 
Error
runtime error: invalid memory address or nil pointer dereference
 
Stack Trace
goroutine 1 [running]:
code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
/home/runner/work/cli/cli/util/panichandler/handler.go:19 +0x57
panic({0x107e5a0, 0x1b6d300})
/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/panic.go:884 +0x213
code.cloudfoundry.org/cli/actor/v7action.Actor.MakeCurlRequest({

{0x13e7480, 0xc000004300}
, {0x7fe1a3433a48, 0xc0002bc380}, {0x13d0b28, 0xc00007fec0}, {0x13d8c68, 0xc00001a7e0}, {0x13cad38, 0xc00031be30}, ...}, ...)
/home/runner/work/cli/cli/actor/v7action/curl.go:51 +0x311
code.cloudfoundry.org/cli/command/v7.CurlCommand.Execute({{{0x13e39d0, 0xc000258630}, {0x13e52e0, 0xc0002bc380}, {0x13d4a10, 0xc00007fec0}, {0x13e8850, 0xc000181420}, 0xc000004300, 0xc00001a7e0}, ...}, ...)
/home/runner/work/cli/cli/command/v7/curl_command.go:25 +0x99
code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).executionWrapper(0xc000340590, {0x7fe1a3433898, 0x1b97d28}, {0xc000136000, 0x0, 0x5})
/home/runner/work/cli/cli/util/command_parser/command_parser.go:88 +0x297
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000322fc0, {0xc00003e1f0, 0x5, 0x5})
/home/runner/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:333 +0x908
code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).parse(0xc000340590, {0xc00003e1f0?, 0x5, 0x5}, {0x1083d60, 0x1b96320})
/home/runner/work/cli/cli/util/command_parser/command_parser.go:219 +0xf3
code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).ParseCommandFromArgs(...)
/home/runner/work/cli/cli/util/command_parser/command_parser.go:52
main.main()
/home/runner/work/cli/cli/main.go:41 +0x213
 
goroutine 61 [syscall]:
os/signal.signal_recv()
/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
/opt/hostedtoolcache/go/1.20.7/x64/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
/opt/hostedtoolcache/go/1.20.7/x64/src/os/signal/signal.go:151 +0x2a
 
goroutine 25 [chan receive]:
code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc0002c8fd0?, {0xc00004f4c0, 0x1f})
/home/runner/work/cli/cli/util/configv3/write_config.go:64 +0x25
created by code.cloudfoundry.org/cli/util/configv3.(*Config).WriteConfig
/home/runner/work/cli/cli/util/configv3/write_config.go:41 +0x28b
```

**Expected behavior**
Deletes the destination from the route without any error and continues.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf8 curl /v3/routes/<route-guid>/destinations/<destination-guid> -X DELETE`
3. See above error

**Provide more context**
Platform: Ubuntu 22.04.3 LTS
CLI version: 8.7.3+efd1d03.2023-09-12
CC API release: 3.149.0

**Comment by 00Aisha** [comment] 2023-12-03 07:15
Something unexpected happened. Please try again.I have tried everything but the same problem keeps coming up.

**Comment by 00Aisha** [comment] 2023-12-03 07:15
What should I do in this situation can you help me I need your help

**Comment by 00Aisha** [comment] 2023-12-03 07:16
Hello?

**Comment by a-b** [comment] 2024-09-27 21:10
I was unable to reproduce using recent cli and capi:
```
capi                   1.191.0*   24406792  
```
```
❯ cf version
cf version 8.8.2+483578c.2024-09-20
```

I'm resolving this issue for now, but please don't hesitate to reopen it if you have any more questions or comments.

**Closed by a-b** 2024-09-27 21:10 UTC
Labels: unscheduled
