### ISSUE TITLE
ruby buildpack fails when pushed from Windows machine

### ISSUE THREAD

**Issue by sbenario** [cloudfoundry/cli#710] opened 2015-12-09 00:50 UTC
Reported by Matt Stine (@mstine)

1) clone and open this application:  https://github.com/mstine/2016_CloudNativeAppArchWorkshop/tree/master/labs/pact_broker 
2) cf push from an OS X host
3) cf push from a Windows host

On OS X, the Ruby buildpack is detected automatically and works as expected. When pushing from a Windows host, automatic detection fails. (application builds correctly if specified with "-b ruby_buildpack".

**Comment by dkoper** [comment] 2015-12-10 00:31
Hi Steve, Matt,

I was unable to reproduce it on Windows, auto-detection worked fine.

* Can you provide more info? Can you reproduce it with the latest cf CLI version?
* Does it always fail on Windows or intermittently? Specific to one machine or any?
* Is the behaviour different between an initial push or a re-push after a file update?
* Can you provide us with the full command line used to push it?
* What is the full command output? Can you attach the logs?
* What are the file permissions of the files you are pushing?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment] 2015-12-15 21:28
Closing as we have not enough information to proceed. Feel free to reopen or submit a new issue when you have more details.

Dies Koper
CF CLI PM

**Closed by dkoper** 2015-12-15 21:28 UTC
