### ISSUE TITLE
Cf ignore all folders with vendor as name 

### ISSUE THREAD

**Issue by houssemFat** [cloudfoundry/cli#1057] opened 2017-01-12 13:57 UTC
## Command  

cf push

## What occurred

All folder with name `vendor` are ignored

## What you expected to occur
I'm using cloudfoundary to deploy a bluemix application, i need to ignore a folder named `vendor` which is under the root path of my application and keep the other folder `vendor` under an other folder.

When i browse the app after push, all `vendor` folder were ignored.

I use another case with another name  `folder__2` it **works fine**.

Here's my`.cfignore` file 

```
/vendor__2/
!/app/vendor__2/
/vendor/
!/app/vendor/
/node_modules/
```
In this case, the folder `vendor__2`  of root was ignored and the `vendor__2` under app exists which is the expected case. For the folders with `vendor` as name, they  were  all ignored! 
 
## CLI Version  

6.22.1+6b7af9c-2016-09-24

## Platform & Shell Details  

Window 10 / ubuntu 14.04

**Comment by dkoper** [comment] 2017-01-13 11:49
Hi @houssemFat 

I cannot reproduce this. Maybe I did not understand your issue correctly?

I have a Java app. I added two `vendor` folders, one in the root and one under `WEB-INF`:
```
D:.
├─vendor
└─WEB-INF
    ├─classes
    │  └─filter
    ├─lib
    └─vendor
```

Both `vendor` folders contain a file.
In the root I also have the `.cfignore` with its contents copied & pasted from your issue description.

I pushed it to a Diego backend. When I `cf ssh` in, I can see the `vendor` directory in the root was ignored, but the `vendor` directory under WEB-INF is there, as expected:
```
D:\s>cf ssh vendor -c "find . | grep -v buildpack"
.
./logs
./app
./app/CharacterSetFilter.java
./app/WEB-INF
./app/WEB-INF/web.xml
./app/WEB-INF/vendor
./app/WEB-INF/vendor/blah.txt
./app/WEB-INF/classes
./app/WEB-INF/classes/filter
./app/WEB-INF/classes/filter/CharacterSetFilter.class
./app/WEB-INF/lib
./app/WEB-INF/lib/jstl-1.2.jar
./app/WEB-INF/lib/tomcat-jdbc.jar
./app/trace-tasks.txt
./app/simple.jsp
./tmp
./staging_info.yml
./.bash_history
./.bashrc
./.bash_logout
./.profile
```

Note that with Diego, your application files are placed under an `./app` folder, so it looks more confusing when you have an `app/` folder name in your application as well.

**Comment by houssemFat** [comment] 2017-01-14 09:49
Hi, @dkoper thank you for support ! This issue were occurred in a symfony application (which use a vendor folder to manage dependencies in the application root). 
Sorry, my code below works fine, but i tried to just simplify the case of our symfony app. 
I think that's related to the php buildpack version. Should we open this issue on the php buildpack repo ?

**Comment by dkoper** [comment] 2017-01-15 10:43
@houssemFat Sure. If the problem only happens with the php buildpack, it is not likely there is an issue with the cf CLI - it treats all types of application the same.

**Comment by houssemFat** [comment] 2017-01-16 07:37
Ok @dkoper , Thank you !!

**Comment by dkoper** [comment] 2017-01-30 10:59
Closing. Feel free to reopen or submit a new issue if there is something on the CLI side we need to investigate again.

**Closed by dkoper** 2017-01-30 10:59 UTC
Labels: unscheduled
