### ISSUE TITLE
brew install error: Error: No such file or directory - cf

### ISSUE THREAD

**Issue by apps4u** [cloudfoundry/cli#1434] opened 2018-08-09 02:40 UTC
## Command
brew install cf-cli

## What occurred
I tried to update brew today and got a error so I removed cf and tried to install again with the same error. Not sure what cf directory it cannot find or its path.

```
brew install cf-cli 
==> Installing cf-cli from cloudfoundry/tap
==> Downloading https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=6.38.0&source=homebrew
Already downloaded: /Users/admin/Library/Caches/Homebrew/cf-cli--6.38.0.0
Error: No such file or directory - cf
```

## What you expected to occur
install with out issue
## CLI Version

Already downloaded: /Users/admin/Library/Caches/Homebrew/cf-cli--6.38.0.0
## Platform & Shell Details
Mac osx 10.13.6,  Terminal App.

## Any other relevant information
Updated did not work, I tried to reinstalled , I then removed and tried to install again.  I need my CF cli So I now removed the old version so I stuck using ibmcloud cli for now.

**Comment by apps4u** [comment] 2018-08-09 02:44
thanks that was quick, I will track issue. And I'll keep you updated with any more info I get as I'm try and debug.

**Comment by tjvman** [comment] 2018-08-09 15:58
@apps4u Was not able to reproduce this behavior.

OS X: 10.11.6 (El Capitan)
Homebrew: 1.7.1

```
==> Installing cf-cli from cloudfoundry/tap
==> Downloading https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=6.38.0&source=homebrew
==> Downloading from https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.38.0/cf-cli_6.38.0_osx.tgz
######################################################################## 100.0%
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cf-cli/6.38.0: 6 files, 18.1MB, built in 3 seconds
```

What version of Homebrew and OSX are you using? Also, did you remove the cli using `brew uninstall` or using some other means?

**Comment by anwarchk** [comment] 2018-08-09 16:05
I have the same issue: Here are my `brew config` details:
```HOMEBREW_VERSION: 1.7.1-204-g8e703e3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e703e30ba53f8089686b0fc90f87803b4fd5d90
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a0f27d7db954b326fac40040b8509b3bed8b7e28
Core tap last commit: 76 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172, 1.8.0_162, 1.8.0_152, 1.8.0_141, 1.8.0_131, 1.8.0_121, 1.8.0_112, 1.8.0_102, 1.8.0_92, 1.8.0_77, 1.7.0_79
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
```
and the output from `brew install cf-cli --verbose`:
```/usr/bin/sandbox-exec -f /private/tmp/homebrew20180809-56109-ekf3v0.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/cask/lib:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/cloudfoundry/homebrew-tap/cf-cli.rb --verbose
==> Downloading https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=6.38.0&source=homebrew
Already downloaded: /Users/achirakkattil/Library/Caches/Homebrew/cf-cli--6.38.0.0
==> Verifying cf-cli--6.38.0.0 checksum
cp -p /Users/achirakkattil/Library/Caches/Homebrew/cf-cli--6.38.0.0 /private/tmp/cf-cli-20180809-56111-1a3ei7u/stable
Error: No such file or directory - cf
```

**Comment by XenoPhex** [comment] 2018-08-09 16:54
Also debugging this under https://github.com/cloudfoundry/homebrew-tap/issues/48

**Comment by XenoPhex** [comment] 2018-08-15 16:43
Closing this ticket in favor of https://github.com/cloudfoundry/homebrew-tap/issues/48. Please use that ticket for any new updates/comments.

**Closed by XenoPhex** 2018-08-15 16:43 UTC
Labels: in progress
