### ISSUE TITLE
Installer does not complete in Debian Jessie (stable)

### ISSUE THREAD

**Issue by bunnybooboo** [cloudfoundry/cli#507] opened 2015-07-05 05:56 UTC
I'm using the cf-cli_amd64.deb file (downloaded 5 July) and a new install of Debian Jessie 8.1.
Install just hangs when the task bar seemingly does its when it gets to 'running'. It doesn't complete though, leaving me with only the options cancel/close.

**Comment by MontesClarosServidores** [comment] 2015-07-05 23:05
ok

**Comment by camelpunch** [comment] 2015-09-16 14:16
@bunnybooboo I've tried to reproduce this using a Debian 8.1 Docker container with both 6.12.0 and 6.12.1 to no avail.

I'm closing this for now since there have been other releases since July. Please re-open if this issue persists in the latest release. Thanks!

**Closed by camelpunch** 2015-09-16 14:16 UTC
