### ISSUE TITLE
updating staging variables that seems acceptable fails on the retrieval

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/cli#1534] opened 2018-12-24 07:55 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

-[x ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
-[x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
-[x ] I am reporting a bug that others will be able to reproduce.

Retrieving back the staging variables generates an error when the value is a more complex JSON than a string.   It seems the data is returned but cf-cli is failing on the display.

**Expected a string output of the JSON.**

**cf version 6.41.0+dd4c76cdd.2018-11-28
MacOs Mojave  Version 10.14.2**

**cf -v set-staging-environment-variable-group '{"name":[1,2,3]}'**
Setting the contents of the staging environment variable group as admin...

REQUEST: [2018-12-23T23:41:50-08:00]
PUT /v2/config/environment_variable_groups/staging HTTP/1.1
Host: api.dev.cfdev.sh
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.41.0+dd4c76cdd.2018-11-28 / darwin

{"name":[1,2,3]}

RESPONSE: [2018-12-23T23:41:50-08:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 39
Content-Type: application/json;charset=utf-8
Date: Mon, 24 Dec 2018 07:41:50 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 0b84f835-c814-40c8-5c86-1793f0232e76::750965fa-8830-4cf7-bc57-c20bb224865b

{
  "name": [
    1,
    2,
    3
  ]
}
**OK**

**cf -v staging-environment-variable-group**
Retrieving the contents of the staging environment variable group as admin...

REQUEST: [2018-12-23T23:41:50-08:00]
GET /v2/config/environment_variable_groups/staging HTTP/1.1
Host: api.dev.cfdev.sh
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.41.0+dd4c76cdd.2018-11-28 / darwin

RESPONSE: [2018-12-23T23:41:50-08:00]
**HTTP/1.1 200 OK**
Connection: close
Content-Length: 39
Content-Type: application/json;charset=utf-8
Date: Mon, 24 Dec 2018 07:41:50 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 92f42bd6-8cd8-4f9e-62e1-4508f239d756::5768b2cd-3236-430d-b9a0-89b4da888bc4

{
  "name": [
    1,
    2,
    3
  ]
}
**FAILED
Attempted to read environment variable value of unknown type: []interface {}{1, 2, 3}**

**Comment by norman-abramovitz** [comment] 2018-12-24 16:31
cf env works correctly

No user-defined env variables have been set

...
Running Environment Variable Groups:
name1: 1234
name2: [1 2 3]

Staging Environment Variable Groups:
name1: 1234
name2: [1 2 3]

**Comment by abbyachau** [comment] 2019-01-02 17:22
Hi @norman-abramovitz thanks for creating this bug report. We will try to reproduce this on our side and get back to you as soon as we can. Thanks again.

**Comment by Ema93sh** [comment] 2019-01-07 17:38
Hi @norman-abramovitz thanks for creating this issue. I was able to reproduce the issue and marked it as a bug. It is a bug in our legacy code (`staging-environment-variable-group`  command) which expects only a string or float as the value of environment variable and fails otherwise. However the `set-staging-environment-variable-group` command does not care about the type of value of the environment variable.

**Comment by sladyn98** [comment] 2019-06-06 20:21
@Ema93sh is this issue a good one as a good first bug? If yes I would like to take a look at it.

**Comment by willmurphyscode** [comment] 2019-06-07 21:09
@sladyn98  We think this is a good first bug to work on. Thanks!

**Comment by sladyn98** [comment] 2019-06-17 18:27
@willmurphyscode Hey I did go through the comments on the issue and it seems like the `staging-environment-variable-group` accpets only strings but it should not care about the type am i right?

**Comment by bwasmith** [comment] 2019-06-24 17:51
Hello @sladyn98 ,

Sorry for the delay! 

It looks like you are on the right track. In `cf staging-environment-variable-group`, it looks to me like the way we unmarshal the JSON response from the server does not handle non-strings and non-floats correctly. It should be able to accept other types gracefully (perhaps by not attempting to type-caste the responses). 

Just playing around, it seems like situations like this do not work (not surprisingly):
```
$ cf -v set-staging-environment-variable-group '{"name":{"inner_name":[1,2,3]}}'
Setting the contents of the staging environment variable group as admin...

REQUEST: [2019-06-24T10:46:37-07:00]
PUT /v2/config/environment_variable_groups/staging HTTP/1.1
Host: api.trail-beetle.lite.cli.fun
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.45.0+c7f606b10.2019-06-24 / linux

{
  "name": {
    "inner_name": [
      1,
      2,
      3
    ]
  }
}


RESPONSE: [2019-06-24T10:46:37-07:00]
HTTP/1.1 200 OK
...
OK

```

```
$ cf -v staging-environment-variable-group
Retrieving the contents of the staging environment variable group as admin...

REQUEST: [2019-06-24T10:49:37-07:00]
GET /v2/config/environment_variable_groups/staging HTTP/1.1
...


RESPONSE: [2019-06-24T10:49:37-07:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 71
Content-Type: application/json;charset=utf-8
Date: Mon, 24 Jun 2019 17:49:37 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 6e21ca4c-15b1-4616-4a34-3368e01d8fa6::6cc2e87f-ed6a-4cd9-a455-c97de4b5ca04

{
  "name": {
    "inner_name": [
      1,
      2,
      3
    ]
  }
}
FAILED
Attempted to read environment variable value of unknown type: map[string]interface {}{"inner_name":[]interface {}{1, 2, 3}}


```

**Comment by bwasmith** [comment] 2019-06-24 17:56
I feel like you are on the right path. But, if you want an additional pointer, see [the marshalToEnvironmentVariables function](https://github.com/cloudfoundry/cli/blob/c7f606b103b947d17ad956b1d957f9728670b86c/cf/api/environmentvariablegroups/environment_variable_groups.go#L72)

**Comment by acrmp** [comment] 2019-07-26 18:55
Hi @norman-abramovitz,

We discussed this further in #1704 and determined that supporting environment variables with complex values was unusual behaviour in the Cloud Controller V2 API implementation.

With the V3 API an error is returned if you attempt to set an environment variable with a complex structure. I think the correct approach if you want to represent more complex values is to marshal the value to JSON.

Thanks to @sladyn98 for investigating a fix for this issue. I'm going to close the issue but please re-open if you want to continue the conversation.

Thanks,

Andrew.

**Closed by acrmp** 2019-07-26 18:55 UTC
Labels: Easy, bug, contributions welcome, unscheduled

**Comment by norman-abramovitz** [comment] 2019-07-26 22:00
Sorry to hear that.   I only looked into this issue because there were some services/apps that depended on the "complex" syntax.   Having people needing to encode into JSON seems heavy-handed.
