### ISSUE TITLE
unexpected 'invalid memory address' bug in cf.exe

### ISSUE THREAD

**Issue by sachins50** [cloudfoundry/cli#902] opened 2016-07-27 01:08 UTC
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command

        Something completely unexpected happened. This is a bug in cf.exe.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

#cf.exe curl /v2/apps/cab88999-5782-45a0-ae95-4c6f82d9d7dd/droplet/download -H Host: cfsys-gcg-nonprd.nam.nsroot.net -H Cookie:  -
-output contents.tar

        using this version of the CLI:

                6.13.0-e68ce0f

### Error

                runtime error: invalid memory address or nil pointer dereference

### Stack Trace
                goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:127 +0xbb
        main.handlePanics(0x375bd20, 0xc082538640)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:111 +0x183
        github.com/cloudfoundry/cli/cf/api.CloudControllerCurlRepository.Request(0x375c000, 0xc08253b1d0, 0x375c268, 0xc082070000, 0xe4a498, 0x1,
 0x12a05f200, 0x0, 0x0, 0x0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/api/curl.go:56 +0x867
        github.com/cloudfoundry/cli/cf/api.(*CloudControllerCurlRepository).Request(0xc082070360, 0xcbba50, 0x3, 0xc08200c190, 0x3e, 0xc082530480
, 0x2e, 0x0, 0x0, 0x0, ...)
                <autogenerated>:17 +0x16e
        github.com/cloudfoundry/cli/cf/commands.(*Curl).Execute(0xc082509a70, 0x37f0408, 0xc08252a3c0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/curl.go:81 +0x3d3
        main.main()
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cl

### CC API Endpoint Version

API endpoint: https://api.cfsys-gcg-nonprd.nam.nsroot.net (API version: 2.43.0)

### CF Trace

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

Windows 7

### Shell

CMD DOS terminal

**Comment by dkoper** [comment] 2016-07-27 01:16
Hi @sachins50 

cf CLI 6.13.0 is very old, we have fixed a great number of issues since then. Can you please try on the latest cf CLI release to see if you can reproduce it, and if so, include the backtrace here?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment] 2016-08-11 03:21
Closing. Feel free to reopen or file a new issue report if you encounter an issue with the latest cf CLI release.

**Closed by dkoper** 2016-08-11 03:21 UTC
Labels: unscheduled
