### ISSUE TITLE
If you are not a space developer, renaming a service fails with an unhelpful error

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#438] opened 2015-04-30 23:33 UTC
If you are not a space developer, you are able to list all services, but trying to rename the service gives you the error that "service instance foo not found". This was very confusing, since I had just been shown the service. It would be much nicer if the CLI showed an error message like "You do not have permission to rename spaces".

```bash
→ cf services
Getting services in org rivals / space acceptance as me@example.com...
OK

name           service         plan     bound apps                                         last operation
foo            sendgrid        free    cool-app    update succeeded

→ cf rename-service foo bar
FAILED
Service instance foo not found
```

**Comment by dsabeti** [comment] 2015-04-30 23:42
@simonleung8 We think this is probably an API bug. I've filed a story in our backlog and am trying to reproduce the issue. If it's on our side, I'll let you know so you can close this issue.

**Comment by jberkhahn** [comment] 2015-06-10 17:43
@rmasand what was the outcome of this? was it something on your end?

**Comment by rmasand** [comment] 2015-06-10 18:35
We can't find the story in our tracker, but it looks like things have changed since this issue was filed.

For managed service instances we get 
```
Server error, status code: 403, error code: 10003, message: You are not authorized to perform the requested action
```

From talking with @wendorf, it sounds like they were using a user provided service instance, which results in the following message:

```
Server error, status code: 404, error code: 340001, message: The service instance could not be found: guid-guid-guid-guid
```

We added a [new story](https://www.pivotaltracker.com/story/show/96693556) to cover this issue. 

- Raina & @Gerg

**Comment by jberkhahn** [comment] 2015-06-11 18:07
@goehmen So, it looks like this is working as intended on the services end - user provided service instances don't have a corresponding service or service plan. 

So, how do we determine the difference on our end between a service instance that doesn't actually exist and a UPS on our end? I guess if we get a 404 we could do a lookup on UPS and see if it's there? And then tell the user to use update-UPS?

**Comment by camelpunch** [comment] 2015-09-15 16:23
Closing for now as I think the original issue is captured in https://github.com/golang/go/issues/10464#issuecomment-97974790, and that is apparently expected behaviour.

**Closed by camelpunch** 2015-09-15 16:23 UTC
