### ISSUE TITLE
cf delete -r doesn't delete all routes belonging to app

### ISSUE THREAD

**Issue by WalterS** [cloudfoundry/cli#1627] opened 2019-04-30 08:43 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I tried to delete an app with more than 100 routes.

**What happened**
All but the default route weren't deleted when I used `cf d $APP -r -f`

**Expected behavior**
I expected all routes belonging to the app to be deleted

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Deploy an app with 100 routes in the manifest
or
1. Deploy an app and run `for i in {1..100}; do cf map-route $APP example.com --hostname $APP --path $i; done`
2. Run `cf d $APP -r -f`
3. Run `cf routes|awk 'BEGIN {n=0} $2~/'"$APP"'$/ {print;n++} END {print n, "orphaned routes for '$APP'"}'`
4. Run `cf delete-orphaned-routes -f` to delete the now orphaned routes

**Provide more context**
- Ubuntu 18.04 with Bash version 4.4.19(1)
- CLI version: 6.43.0
- CC API release: 2.133.0

**Comment by abbyachau** [comment] 2019-04-30 20:21
Thanks @WalterS we will try to reproduce and will get back to you when we can.

**Comment by acrmp** [comment] 2019-06-25 02:39
Hi @WalterS,

Thanks for reporting this issue! I can confirm that this is a bug in the CLI.

It affects deletion of any application with more than 50 routes.

This is because the current implementation requests the application together with its routes using the V2 API `inline-relations-depth` param. The Cloud Controller V2 API has a default limit of 50 inline objects and will not inline the resources if there are more than 50.

* [relevant limit in the Cloud Controller code](https://github.com/cloudfoundry/cloud_controller_ng/blob/2068e578204205439c73a55dfe0113c16a6c4bbb/app/presenters/v2/relations_presenter.rb#L8)
* where we [naively loop](https://github.com/cloudfoundry/cli/blob/7fcf63b88053d0e37164b09b7e9c9c14ee75f939/cf/commands/application/delete.go#L98-L103) over the set of routes fetched inline with the app
* where we [request the app resource together with its inlined routes](https://github.com/cloudfoundry/cli/blob/7fcf63b88053d0e37164b09b7e9c9c14ee75f939/cf/api/applications/applications.go#L77)

I've added the `contributions welcome` label and we'll also talk to @abbyachau about whether this can be prioritised to work on.

Thanks,

Andrew.

**Comment by bwasmith** [comment] 2020-01-16 17:28
This was fixed in the v6.49.0 release.

**Closed by bwasmith** 2020-01-16 17:28 UTC
Labels: accepted, bug, contributions welcome, v6
