### ISSUE TITLE
"Error dialing traffic controller server" message doesn't tell me I need to re-login if endpoints have changed

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#886] opened 2016-07-11 17:08 UTC
### Command

`cf logs [my-app]`
### CLI Version

6.20.0+25b1961-2016-06-29
### Error

I see the following error even though my operator has fixed the doppler/loggergator endpoint:

```
FAILED
Error dialing traffic controller server: dial tcp x.x.x.x:4443: getsockopt: connection refused.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.sys.x.y.z.com:4443).
```

My Cloud Foundry instance updated doppler/trafficcontroller to run on 443, but the CLI has not yet picked up on it, and the error message doesn't tell me that if the operator has fixed things, I may need to re-login.
### CC API Endpoint Version

2.56.0
### Platform Details

Mac OS X 10.10.5
### Shell

iTerm2 3.0.4

**Comment by dkoper** [comment] 2016-10-26 06:15
The message comes from the noaa library, and the issue is that the CLI does not reload the /v2/info information until you specify an endpoint to `cf api` or `cf login -a` as it caches it locally. I'm not sure we want to reload this endpoint for each command (although we may for the v3 API if it's HATEOS).
I imagine this endpoint would rarely if ever be updated, so rather than address this in the CLI, I'd hope for CF operators to notify their users when they make such changes.

**Comment by shalako** [comment] 2017-02-11 04:18
Just ran into this myself. 

Logging out and back in did not help.

bosh-lite on aws

```
Error dialing trafficcontroller server: dial tcp 52.204.197.35:4443: getsockopt: operation timed out.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.catwoman.cf-app.com:4443).. Retrying...
```

Still troubleshooting

**Comment by dkoper** [comment] 2017-05-18 06:03
This should be addressed in cf CLI v6.26.0: we refactored the `logs` command and refactored commands always load /v2/info to get the latest. Feel free to reopen or submit a new issue if you are still experiencing this issue.

**Closed by dkoper** 2017-05-18 06:03 UTC
Labels: unscheduled

**Comment by varun7447** [comment] 2018-06-02 00:04
We are seeing this issue with the latest version `cf version 6.37.0+a40009753.2018-05-25` `WEBSOCKET REQUEST: [2018-06-02T00:01:56Z]
GET /apps/4201d384-d118-44a8-8881-72080ef00d73/stream HTTP/1.1
Host: wss://doppler.system.aorp.testanalytics.com:4443
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: [HIDDEN]
Origin: wss://doppler.system.aorp.testanalytics.com:4443
Authorization: [PRIVATE DATA HIDDEN]


WEBSOCKET RESPONSE: [2018-06-02T00:01:56Z]
HTTP/1.1 404 Not Found
Date: Sat, 02 Jun 2018 00:04:23 GMT
Content-Type: text/html
Content-Length: 224
Connection: keep-alive


WEBSOCKET ERROR: [2018-06-02T00:01:56Z]
Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.system.aorp.testanalytics.com:4443).. Retrying...
`

**Comment by ashwithahn** [comment] 2018-07-17 05:13
Hi could you please share solution for this, I am running into same error

WEBSOCKET RESPONSE
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Tue, 17 Jul 2018 05:09:38 GMT
Sec-Websocket-Version: 13
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: fb36312a-660e-432c-7a29-41cfb83bd85e
Content-Length: 12

Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.app-cloudfoundry.com:443).

**Comment by tariqsiddiqui** [comment] 2018-07-26 15:34
I am seeing the same issue. Any ideas?
