### ISSUE TITLE
Issue with diego enabler v1.2.2

### ISSUE THREAD

**Issue by plfx** [cloudfoundry/cli#997] opened 2016-11-09 01:08 UTC
* Command  
`cf enable-diego some-app`

* What occurred, incl. error and/or stack trace
```
Setting pivotal-account-green Diego support to true

REQUEST: [2016-11-09T00:24:53Z]
GET /v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/apps?q=name%3Apivotal-account-green&inline-relations-depth=1 HTTP/1.1
Host: api.identity.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / linux



RESPONSE: [2016-11-09T00:24:53Z]
HTTP/1.1 200 OK
Connection: close
Content-Length: 6292
Content-Type: application/json;charset=utf-8
Date: Wed, 09 Nov 2016 00:24:53 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 8311387e-3ea8-483e-55af-9ecd43183b3b
X-Vcap-Request-Id: 8311387e-3ea8-483e-55af-9ecd43183b3b::63c5f9f5-b0e3-4e0d-ab31-108059d05e58

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "19eef147-9673-4f79-8643-2a3f8d85e829",
        "url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829",
        "created_at": "2016-11-08T23:12:13Z",
        "updated_at": "2016-11-09T00:24:52Z"
      },
      "entity": {
        "name": "pivotal-account-green",
        "production": false,
        "space_guid": "d6cadfdc-2208-42d5-8460-95c66c3e62f6",
        "stack_guid": "5a8875a4-6a56-470f-ad11-39632fad646a",
        "buildpack": null,
        "detected_buildpack": null,
        "detected_buildpack_guid": null,
        "environment_json": {
          "APP_ROUTE": "https://account.identity.cf-app.com",
          "CF_TARGET": "https://api.identity.cf-app.com",
          "DB_PASSWORD":"[PRIVATE DATA HIDDEN]",
          "DB_URL": "jdbc:mysql://pivotal-account.cbx2vdaeo2ex.us-east-1.rds.amazonaws.com:3306/pivotal_account?verifyServerCertificate=false&useSSL=false&requireSSL=false",
          "DB_USERNAME": "admin",
          "ENABLE_GOOGLE_ANALYTICS": "false",
          "ENCRYPTION_KEY": "1234567890123456",
          "JAVA_OPTS": "-Dspring.profiles.active=production",
          "NOTIFICATIONS_LOCATION": "https://notifications.identity.cf-app.com",
          "NOTIFICATIONS_UI_LOCATION": "https://notifications-ui.run.pivotal.io",
          "OAUTH_CLIENT_ID": "account",
          "OAUTH_CLIENT_SECRET": "account_secret",
          "SKIP_SSL_VALIDATION": "true",
          "UAA_LOCATION": "https://login.identity.cf-app.com",
          "WHITE_LABEL_CONFIG": "{\"companyName\":\"Pivotal\",\"logo\":\"/images/pivotal_logo.png\",\"smallSquare\":\"/images/pivotal-logo-mobile.png\",\"legalText\":\"©2016 Pivotal Software, Inc. All Rights Reserved.\",\"legalLinks\":[{\"name\":\"Privacy Policy\",\"href\":\"https://run.pivotal.io/policies/privacy-policy/\"},{\"name\":\"Terms of Service\",\"href\":\"https://run.pivotal.io/policies/terms-of-service\"}]}"
        },
        "memory": 1024,
        "instances": 1,
        "disk_quota": 1024,
        "state": "STOPPED",
        "version": "487cffdd-a353-445a-ab17-93830dc9c706",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": null,
        "package_state": "PENDING",
        "health_check_type": "port",
        "health_check_timeout": 180,
        "staging_failed_reason": null,
        "staging_failed_description": null,
        "diego": true,
        "docker_image": null,
        "package_updated_at": "2016-11-09T00:24:21Z",
        "detected_start_command": "",
        "enable_ssh": true,
        "docker_credentials_json": {
          "redacted_message": "[PRIVATE DATA HIDDEN]"
        },
        "ports": [
          8080
        ],
        "space_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6",
        "space": {
          "metadata": {
            "guid": "d6cadfdc-2208-42d5-8460-95c66c3e62f6",
            "url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6",
            "created_at": "2016-06-07T23:41:20Z",
            "updated_at": null
          },
          "entity": {
            "name": "pivotal-account-space",
            "organization_guid": "136b57ba-2137-4f1f-bb32-85481ceaa69b",
            "space_quota_definition_guid": null,
            "isolation_segment_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/136b57ba-2137-4f1f-bb32-85481ceaa69b",
            "developers_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/developers",
            "managers_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/managers",
            "auditors_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/auditors",
            "apps_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/apps",
            "routes_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/routes",
            "domains_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/domains",
            "service_instances_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/service_instances",
            "app_events_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/app_events",
            "events_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/events",
            "security_groups_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6/security_groups"
          }
        },
        "stack_url": "/v2/stacks/5a8875a4-6a56-470f-ad11-39632fad646a",
        "stack": {
          "metadata": {
            "guid": "5a8875a4-6a56-470f-ad11-39632fad646a",
            "url": "/v2/stacks/5a8875a4-6a56-470f-ad11-39632fad646a",
            "created_at": "2015-06-10T19:44:21Z",
            "updated_at": null
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "Cloud Foundry Linux-based filesystem"
          }
        },
        "routes_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/routes",
        "routes": [
          {
            "metadata": {
              "guid": "0729f6fa-0870-4572-bd26-c3cab9041fe9",
              "url": "/v2/routes/0729f6fa-0870-4572-bd26-c3cab9041fe9",
              "created_at": "2016-06-07T23:41:22Z",
              "updated_at": null
            },
            "entity": {
              "host": "pivotal-account-green",
              "path": "",
              "domain_guid": "6c4576ab-6e11-4fcc-b8e7-f2484a164db2",
              "space_guid": "d6cadfdc-2208-42d5-8460-95c66c3e62f6",
              "service_instance_guid": null,
              "port": null,
              "domain_url": "/v2/shared_domains/6c4576ab-6e11-4fcc-b8e7-f2484a164db2",
              "space_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6",
              "apps_url": "/v2/routes/0729f6fa-0870-4572-bd26-c3cab9041fe9/apps",
              "route_mappings_url": "/v2/routes/0729f6fa-0870-4572-bd26-c3cab9041fe9/route_mappings"
            }
          }
        ],
        "events_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/events",
        "service_bindings_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/service_bindings",
        "service_bindings": [

        ],
        "route_mappings_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/route_mappings"
      }
    }
  ]
}

REQUEST: [2016-11-09T00:24:53Z]
GET /v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/summary HTTP/1.1
Host: api.identity.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / linux



RESPONSE: [2016-11-09T00:24:53Z]
HTTP/1.1 200 OK
Connection: close
Content-Length: 2506
Content-Type: application/json;charset=utf-8
Date: Wed, 09 Nov 2016 00:24:53 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 1ef31659-9963-4a9b-6e33-151fb0a67921
X-Vcap-Request-Id: 1ef31659-9963-4a9b-6e33-151fb0a67921::cb736961-5a83-4b72-9c97-3a86c3b67edf

{"guid":"19eef147-9673-4f79-8643-2a3f8d85e829","name":"pivotal-account-green","routes":[{"guid":"0729f6fa-0870-4572-bd26-c3cab9041fe9","host":"pivotal-account-green","port":null,"path":"","domain":{"guid":"6c4576ab-6e11-4fcc-b8e7-f2484a164db2","name":"identity.cf-app.com"}}],"running_instances":0,"services":[],"available_domains":[{"guid":"6c4576ab-6e11-4fcc-b8e7-f2484a164db2","name":"identity.cf-app.com","router_group_guid":null,"router_group_type":null},{"guid":"d358a5bf-1281-4932-998a-212694043905","name":"c9616df3-6f4c-4f05-4a6a-7b60caa228c1.identity.cf-app.com","router_group_guid":null,"router_group_type":null}],"production":false,"space_guid":"d6cadfdc-2208-42d5-8460-95c66c3e62f6","stack_guid":"5a8875a4-6a56-470f-ad11-39632fad646a","buildpack":null,"detected_buildpack":null,"detected_buildpack_guid":null,"environment_json":{"APP_ROUTE":"https://account.identity.cf-app.com","CF_TARGET":"https://api.identity.cf-app.com","DB_PASSWORD":"[PRIVATE DATA HIDDEN]","DB_URL":"jdbc:mysql://pivotal-account.cbx2vdaeo2ex.us-east-1.rds.amazonaws.com:3306/pivotal_account?verifyServerCertificate=false&useSSL=false&requireSSL=false","DB_USERNAME":"admin","ENABLE_GOOGLE_ANALYTICS":"false","ENCRYPTION_KEY":"1234567890123456","JAVA_OPTS":"-Dspring.profiles.active=production","NOTIFICATIONS_LOCATION":"https://notifications.identity.cf-app.com","NOTIFICATIONS_UI_LOCATION":"https://notifications-ui.run.pivotal.io","OAUTH_CLIENT_ID":"account","OAUTH_CLIENT_SECRET":"account_secret","SKIP_SSL_VALIDATION":"true","UAA_LOCATION":"https://login.identity.cf-app.com","WHITE_LABEL_CONFIG":"{\"companyName\":\"Pivotal\",\"logo\":\"/images/pivotal_logo.png\",\"smallSquare\":\"/images/pivotal-logo-mobile.png\",\"legalText\":\"©2016 Pivotal Software, Inc. All Rights Reserved.\",\"legalLinks\":[{\"name\":\"Privacy Policy\",\"href\":\"https://run.pivotal.io/policies/privacy-policy/\"},{\"name\":\"Terms of Service\",\"href\":\"https://run.pivotal.io/policies/terms-of-service\"}]}"},"memory":1024,"instances":1,"disk_quota":1024,"state":"STOPPED","version":"487cffdd-a353-445a-ab17-93830dc9c706","command":null,"console":false,"debug":null,"staging_task_id":null,"package_state":"PENDING","health_check_type":"port","health_check_timeout":180,"staging_failed_reason":null,"staging_failed_description":null,"diego":true,"docker_image":null,"package_updated_at":"2016-11-09T00:24:21Z","detected_start_command":"","enable_ssh":true,"docker_credentials_json":{"redacted_message":"[PRIVATE DATA HIDDEN]"},"ports":null}

REQUEST: [2016-11-09T00:24:53Z]
GET /v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/instances HTTP/1.1
Host: api.identity.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / linux



RESPONSE: [2016-11-09T00:24:53Z]
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 102
Content-Type: application/json;charset=utf-8
Date: Wed, 09 Nov 2016 00:24:53 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: dbf08cd1-2feb-461a-46b3-97d9ca2be85f
X-Vcap-Request-Id: dbf08cd1-2feb-461a-46b3-97d9ca2be85f::87e04176-7bdd-4542-ad8e-496fd4bef11c

{
  "code": 170002,
  "description": "App has not finished staging",
  "error_code": "CF-NotStaged"
}


REQUEST: [2016-11-09T00:24:53Z]
GET /v2/stacks/5a8875a4-6a56-470f-ad11-39632fad646a HTTP/1.1
Host: api.identity.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / linux



RESPONSE: [2016-11-09T00:24:53Z]
HTTP/1.1 200 OK
Connection: close
Content-Length: 305
Content-Type: application/json;charset=utf-8
Date: Wed, 09 Nov 2016 00:24:53 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 999d88bf-f90f-451e-79fc-976cd333008d
X-Vcap-Request-Id: 999d88bf-f90f-451e-79fc-976cd333008d::909892b8-a451-4a9a-8026-2ba2614bf33f

{
  "metadata": {
    "guid": "5a8875a4-6a56-470f-ad11-39632fad646a",
    "url": "/v2/stacks/5a8875a4-6a56-470f-ad11-39632fad646a",
    "created_at": "2015-06-10T19:44:21Z",
    "updated_at": null
  },
  "entity": {
    "name": "cflinuxfs2",
    "description": "Cloud Foundry Linux-based filesystem"
  }
}

REQUEST: [2016-11-09T00:24:53Z]
PUT /v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829 HTTP/1.1
Host: api.identity.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / linux

{"diego":true}

RESPONSE: [2016-11-09T00:24:53Z]
HTTP/1.1 201 Created
Connection: close
Content-Length: 2942
Content-Type: application/json;charset=utf-8
Date: Wed, 09 Nov 2016 00:24:53 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 238175bc-9a48-474b-4768-74a97eb9de69
X-Vcap-Request-Id: 238175bc-9a48-474b-4768-74a97eb9de69::a364c3a9-c038-4ab3-bb86-d78baac8d50c

{
  "metadata": {
    "guid": "19eef147-9673-4f79-8643-2a3f8d85e829",
    "url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829",
    "created_at": "2016-11-08T23:12:13Z",
    "updated_at": "2016-11-09T00:24:53Z"
  },
  "entity": {
    "name": "pivotal-account-green",
    "production": false,
    "space_guid": "d6cadfdc-2208-42d5-8460-95c66c3e62f6",
    "stack_guid": "5a8875a4-6a56-470f-ad11-39632fad646a",
    "buildpack": null,
    "detected_buildpack": null,
    "detected_buildpack_guid": null,
    "environment_json": {
      "APP_ROUTE": "https://account.identity.cf-app.com",
      "CF_TARGET": "https://api.identity.cf-app.com",
      "DB_PASSWORD":"[PRIVATE DATA HIDDEN]",
      "DB_URL": "jdbc:mysql://pivotal-account.cbx2vdaeo2ex.us-east-1.rds.amazonaws.com:3306/pivotal_account?verifyServerCertificate=false&useSSL=false&requireSSL=false",
      "DB_USERNAME": "admin",
      "ENABLE_GOOGLE_ANALYTICS": "false",
      "ENCRYPTION_KEY": "1234567890123456",
      "JAVA_OPTS": "-Dspring.profiles.active=production",
      "NOTIFICATIONS_LOCATION": "https://notifications.identity.cf-app.com",
      "NOTIFICATIONS_UI_LOCATION": "https://notifications-ui.run.pivotal.io",
      "OAUTH_CLIENT_ID": "account",
      "OAUTH_CLIENT_SECRET": "account_secret",
      "SKIP_SSL_VALIDATION": "true",
      "UAA_LOCATION": "https://login.identity.cf-app.com",
      "WHITE_LABEL_CONFIG": "{\"companyName\":\"Pivotal\",\"logo\":\"/images/pivotal_logo.png\",\"smallSquare\":\"/images/pivotal-logo-mobile.png\",\"legalText\":\"©2016 Pivotal Software, Inc. All Rights Reserved.\",\"legalLinks\":[{\"name\":\"Privacy Policy\",\"href\":\"https://run.pivotal.io/policies/privacy-policy/\"},{\"name\":\"Terms of Service\",\"href\":\"https://run.pivotal.io/policies/terms-of-service\"}]}"
    },
    "memory": 1024,
    "instances": 1,
    "disk_quota": 1024,
    "state": "STOPPED",
    "version": "487cffdd-a353-445a-ab17-93830dc9c706",
    "command": null,
    "console": false,
    "debug": null,
    "staging_task_id": null,
    "package_state": "PENDING",
    "health_check_type": "port",
    "health_check_timeout": 180,
    "staging_failed_reason": null,
    "staging_failed_description": null,
    "diego": true,
    "docker_image": null,
    "package_updated_at": "2016-11-09T00:24:21Z",
    "detected_start_command": "",
    "enable_ssh": true,
    "docker_credentials_json": {
      "redacted_message": "[PRIVATE DATA HIDDEN]"
    },
    "ports": [
      8080
    ],
    "space_url": "/v2/spaces/d6cadfdc-2208-42d5-8460-95c66c3e62f6",
    "stack_url": "/v2/stacks/5a8875a4-6a56-470f-ad11-39632fad646a",
    "routes_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/routes",
    "events_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/events",
    "service_bindings_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/service_bindings",
    "route_mappings_url": "/v2/apps/19eef147-9673-4f79-8643-2a3f8d85e829/route_mappings"
  }
}
FAILED
Error: unexpected end of JSON input

```

* What you expected to occur
Expected a message saying diego was enabled

* CLI Version  
6.22.2

* CC API Endpoint Version  
2.63.0

* Platform & Shell Details  
An errand VM on a bosh director of version 1.3215.3.0

* Any other relevant information  
You can see in the output that diego was successfully enabled, but the response could not be parsed. One of the intermediate responses is a 400 status.

**Comment by dkoper** [comment] 2016-11-09 01:48
Looks like a duplicate of https://github.com/cloudfoundry-incubator/Diego-Enabler/issues/6.
If it also doesn't work with CF trace disabled, could you please open an issue in the Diego-Enabler project's issue tracker?

**Closed by dkoper** 2016-11-09 01:48 UTC
Labels: unscheduled
