### ISSUE TITLE
`cf push` fails when file mode is invalid, but doesn't say which file was the cause

### ISSUE THREAD

**Issue by Rylon** [cloudfoundry/cli#1096] opened 2017-03-15 15:29 UTC
Hi!

When pushing an application which contains files with an invalid file mode the push fails, but even with CF_TRACE enabled no filename is given. This makes it trickier to debug, especially in environments where the working directory is maybe modified before pushing (eg/ some CI systems, etc).

In this example, we are pushing an app to Cloud Foundry via Travis CI.

## Command  

Just a regular `cf push`.

## What occurred

```
RESPONSE: [2017-03-15T09:23:16Z]
HTTP/1.1 200 OK
Connection: close
Content-Length: 575
Content-Type: application/json;charset=utf-8
Date: Wed, 15 Mar 2017 09:23:13 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 9366d1e1-f344-48f2-4580-fdc81a9d8ba3
X-Vcap-Request-Id: 9366d1e1-f344-48f2-4580-fdc81a9d8ba3::a837cd88-02af-4f69-b4cd-c2d2215715ea
{
  "metadata": {
    "guid": "c9ea82e5-6b13-42a2-b502-1e255016772f",
    "created_at": "2017-03-15T09:23:07Z",
    "url": "/v2/jobs/c9ea82e5-6b13-42a2-b502-1e255016772f"
  },
  "entity": {
    "guid": "c9ea82e5-6b13-42a2-b502-1e255016772f",
    "status": "failed",
    "error": "Use of entity>error is deprecated in favor of entity>error_details.",
    "error_details": {
      "code": 160003,
      "description": "The resource file mode is invalid: File mode '0444' is invalid. Minimum file mode is '0600'",
      "error_code": "CF-AppResourcesFileModeInvalid"
    }
  }
}
FAILED
Error processing app files: Error uploading application.
The resource file mode is invalid: File mode '0444' is invalid. Minimum file mode is '0600'
Logging out...
OK
```

## What you expected to occur

I would like to be given the filename of the resource causing the issue to make it easier to debug.

## CLI Version  

go-cli 6.25.0+787326d.2017-02-28 / linux

## CC API Endpoint Version  

API version: 2.61.0

## Platform & Shell Details  

Travis CI build agent Ubuntu 12.04.5 LTS

**Comment by dkoper** [comment] 2017-03-16 01:48
@zrob This is a CC error. Can you add a filename to the error message?

@Rylon, I cannot reproduce this. Can you provide the exact steps to reproduce the error?

My steps on Ubuntu 14:
```
diesk@cloud-cf:~/workspace/static-app$ cf -v
cf version 6.25.0+787326d.2017-02-28
diesk@cloud-cf:~/workspace/static-app$ chmod 0444 filemodefile.txt
diesk@cloud-cf:~/workspace/static-app$ ls -la filemodefile.txt
-r--r--r-- 1 diesk diesk 13 Mar 16 12:43 filemodefile.txt
diesk@cloud-cf:~/workspace/static-app$ cf p filemode  --no-manifest --no-route
Creating app filemode in org org / space space as admin...
OK

App filemode is a worker, skipping route creation
Uploading filemode...
Uploading app files from: /home/diesk/workspace/static-app
Uploading 1.6K, 9 files
Done uploading
OK

Starting app filemode in org org / space space as admin...
-----> Downloaded app package (4.0K)
-------> Buildpack version 1.3.14
Using Nginx version 1.11.6
Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/afb96925-31ad-4ff6-896f-ce3c690d48ae_6b86ccde7bbb7c24f7e9d023c1eb3adc778eb633/dependencies/https___buildpacks.cloudfoundry.org_dependencies_nginx_nginx-1.11.6-linux-x64.tgz]
-----> Using root folder
-----> Copying project files into public/
-----> Setting up nginx

-----> Uploading droplet (2.7M)

1 of 1 instances running

App started


OK

App filemode was started using this command `sh boot.sh`

Showing health and status for app filemode in org org / space space as admin...
OK

requested state: started
instances: 1/1
usage: 256M x 1 instances
urls:
last uploaded: Thu Mar 16 01:46:49 UTC 2017
stack: cflinuxfs2
buildpack: staticfile 1.3.14

     state     since                    cpu     memory         disk      details
#0   running   2017-03-16 12:47:03 PM   38.9%   5.6M of 256M   0 of 1G
```

**Comment by Rylon** [comment] 2017-03-20 11:39
hi @dkoper unfortunately we weren't able to reproduce it "on demand" either, which is why we decided to ask if the filename could be logged, to help debug it 😁

It was actually encountered only by one of our teams who were using Travis CI, and they determined it was because Travis creates a `vendor/bundle` folder, and some of the files within that folder had these incorrect permissions.

They worked around it by adding that folder to `.cfignore`, if that helps?

Thanks!

**Comment by zrob** [comment] 2017-03-22 16:42
we can take a look at updating the error message.

in the meantime you should be able to search the trace log for the invalid file mode `0444` in your case and it should include the request body with the filename

**Comment by Rylon** [comment] 2017-03-23 11:07
Thanks @zrob 

I actually tried CF_TRACE already, but the only output regarding files being uploaded seems to be a list of SHA1s and sizes.

Searching specifically for the filemode, I only see the error at the end.

We're running API version: 2.61.0 on CF release v241, so maybe this is the reason?

**Comment by filipre** [comment] 2017-03-27 09:46
I am getting this error as well. Is it possible that none of the own files causes this error? I just checked all my files and none of them have a permission below `600`.

**Comment by dkoper** [comment] 2017-04-19 10:40
@filipre And the CF trace shows the CLI is not setting `mode` in the multi-part body of /v2/apps/:guid/bits? Or if it does, not setting it to anything below `600`?

**Comment by filipre** [comment] 2017-04-19 14:28
Thanks for your question, @dkoper ! Mhh I don't know anymore. However, I noticed that this was rather caused by our build pipeline (using some magic Atlassian plugins) than by my project. I was able to resolve this by putting my files into a new folder and letting the cf plugin push that but I couldn't explain why this worked.

To come back to the issue, Is it in general possible to provide a file name for the error message below? I guess this could solve a lot of confusion "where" the error could be. And if it is not possible, would it make sense to give a different error message (and maybe to refer to the trace log mentioned above)?

```
The resource file mode is invalid: File mode '0444' is invalid. Minimum file mode is '0600'"
```

**Comment by dkoper** [comment] 2017-05-24 03:51
@Rylon @filipre We are in the process of refactoring our `push` command, which includes a re-implementation of the logic involved on the CLI side. We can investigate further on the CLI side if the issue resurfaces post-refactor.
In the meantime, I'll close this issue, but move [the linked story](https://www.pivotaltracker.com/story/show/141783543) to the capi tracker for consideration of updating the current error message.

**Closed by dkoper** 2017-05-24 03:51 UTC
Labels: unscheduled

**Comment by aashah** [comment] 2017-06-22 23:44
We must have messed up referencing the issue in our commit, but we improved the error message to include the filepath in commit: https://github.com/cloudfoundry/cloud_controller_ng/commit/9f4982419d6ee3bfe4e9cda65337f4ef337d071a

Thanks,
Aakash & @anniesing 
CAPI Community Pair
