### ISSUE TITLE
cf ssh hangs in Git for Windows Bash

### ISSUE THREAD

**Issue by amcoho** [cloudfoundry/cli#1476] opened 2018-10-15 02:50 UTC
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

After successful login using cf login, cf ssh [app_name] hangs in the bash terminal of Git for Windows. 

```
XXXX@PC-E8410 MINGW32 ~/projects/recallinfolink/recall.worker (develop)
$ cf login -u first.last@example.com -p password
API endpoint: https://api.run.pivotal.io
Authenticating...
OK

Targeted org Example Company

Select a space (or press enter to skip):
1. Production
2. QA

Space> 2
Targeted space QA



API endpoint:   https://api.run.pivotal.io (API version: 2.123.0)
User:           first.last@example.com
Org:            ExampleCompany
Space:          QA

XXXX@PC-E8410 MINGW32 ~/projects/recallinfolink/recall.worker (develop)
$ cf ssh qa-worker-communication
```

- Windows 7, Git for Windows 2.16.1.4
- cf.exe version 6.38.0+7ddf0aadd.2018-08-07

**Comment by abbyachau** [comment] 2018-10-22 19:29
Hi @amcoho could you provide the verbose output of the error you are seeing when you run `ssh`? Also please review the [known issue](https://github.com/cloudfoundry/cli#known-issues) with ssh'ing into a windows machine.

**Comment by amcoho** [comment] 2018-10-24 02:10
[cf_ssh_verbose.txt](https://github.com/cloudfoundry/cli/files/2508738/cf_ssh_verbose.txt)
 verbose output is attached.

cf logs does not work either, it just hangs:

`$ cf logs qa-worker-communication
Retrieving logs for app qa-worker-communication in org RecallInfoLink / space QA                                                                                                     as user@domain.com...`

**Comment by Ema93sh** [comment] 2018-10-24 17:56
Hi @amcoho are you able to use PowerShell instead? 

We found other reports that `ssh` doesn't work well in MINGW32/MINGW64. We tested, and we were able to reproduce the issue where `cf ssh` hangs from these shells, but `cf ssh` works fine from PowerShell. We have updated our [known issues](https://github.com/cloudfoundry/cli#known-issues) to warn people to use PowerShell instead of MINGW.

We're closing this issue, since using PowerShell seems like a very reasonable workaround. Please let us know if you have a use case where PowerShell cannot be used.

**Closed by Ema93sh** 2018-10-24 17:56 UTC
Labels: scheduled
