### ISSUE TITLE
Default values for variable substitution

### ISSUE THREAD

**Issue by ihrigb** [cloudfoundry/cli#1514] opened 2018-12-03 10:04 UTC
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.**

For variable substitution, we could use default values. Variable files would of course overwrite them. Notation could be after a separator, like a colon:

**What's the user value of this feature request?**
Manifests can provide default values, which can be overwritten by specific var files for e.g. certain environments.

**Who is the functionality for?**
Anyone deploying applications with manifests could use this feature.

**How often will this functionality be used by the user?**
With each deployment, if functionality is used.

**Who else is affected by the change?**
CLI, Doc

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
`((<variable>[:<defaltValue>]))`

Example from docs:
```yaml
---
applications:
- name: test-app
  instances: ((instances:1))
  memory: ((memory:2G))
  buildpack: go_buildpack
  env:
    GOPACKAGENAME: go_calls_ruby
  command: go_calls_ruby
```

**Describe alternatives you've considered**
Specifying each variable in each var file, although there is a common default.

**Additional context**
n/a

**Comment by tjvman** [comment] 2018-12-04 18:17
Implementing this feature would require changes in the underlying interpolation library which is part of the [BOSH CLI](https://github.com/cloudfoundry/bosh-cli/tree/master/director/template), so you may want to open an issue there to see if the maintainers are interested in this functionality.

**Comment by abbyachau** [comment] 2018-12-07 00:09
cc @charleshansen @tcdowney for capi server side manifest

**Comment by ihrigb** [comment] 2018-12-07 20:20
See https://github.com/cloudfoundry/bosh-cli/issues/502

**Comment by abbyachau** [comment] 2019-04-24 19:59
@ihrigb thanks for creating an issue with `bosh-cli` - it looks like the issue is still open. I'm closing this issue because it has a dependency before we could consider implementation. Please do not hesitate to reopen/create an issue with us once the `bosh-cli` issue moves forward. Thanks.

**Closed by abbyachau** 2019-04-24 19:59 UTC
Labels: enhancement, unscheduled
