### ISSUE TITLE
No tags on user-provided services 

### ISSUE THREAD

**Issue by dotchev** [cloudfoundry/cli#1110] opened 2017-04-01 12:52 UTC
## Command  

```
$ cf cups my-db-mine -p '{"username":"admin","password":"pa55woRD"}'
Creating user provided service my-db-mine in org trial / space u333 as u333...
OK
$ cf update-service my-db-mine -t "ala, bala"
Updating service instance my-db-mine as u333...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

## What you expected to occur

At least a better error message.

Even better allow for tags also on user-provided services.

## CLI Version  

`cf version 6.22.2+a95e24c-2016-10-27`

## CC API Endpoint Version  

`API version: 2.75.0`

## CF Trace

```
$ cf update-service my-db-mine -t "ala, bala" -v

REQUEST: [2017-04-01T15:41:18+03:00]
GET /v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/service_instances?return_user_provided_service_instances=true&q=name%3Amy-db-mine&inline-relations-depth=1 HTTP/1.1
Host: (hidden)
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / darwin



RESPONSE: [2017-04-01T15:41:18+03:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 3059
Content-Type: application/json;charset=utf-8
Date: Sat, 01 Apr 2017 12:41:18 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 9e4af7dc-2924-44ac-714f-3e3525085c62
X-Vcap-Request-Id: 9e4af7dc-2924-44ac-714f-3e3525085c62::a29cc685-7d27-4373-b29b-93c5465fcd1b

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "7904c61e-8b2f-4380-adbc-1268dbc3ed18",
        "url": "/v2/user_provided_service_instances/7904c61e-8b2f-4380-adbc-1268dbc3ed18",
        "created_at": "2017-04-01T12:36:00Z",
        "updated_at": "2017-04-01T12:36:00Z"
      },
      "entity": {
        "name": "my-db-mine",
        "credentials": {
          "password":"[PRIVATE DATA HIDDEN]",
          "username": "admin"
        },
        "space_guid": "0ac1fe96-ccc0-4256-a9ac-5e47dc839f52",
        "type": "user_provided_service_instance",
        "syslog_drain_url": "",
        "route_service_url": "",
        "space_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52",
        "space": {
          "metadata": {
            "guid": "0ac1fe96-ccc0-4256-a9ac-5e47dc839f52",
            "url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52",
            "created_at": "2016-07-22T06:00:51Z",
            "updated_at": "2016-07-22T06:00:51Z"
          },
          "entity": {
            "name": "u333",
            "organization_guid": "74d1bd47-6064-4b3f-b52e-6a6e4dd398cb",
            "space_quota_definition_guid": "f89e0647-d685-41c1-9ea6-e52f5d8a3669",
            "isolation_segment_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/74d1bd47-6064-4b3f-b52e-6a6e4dd398cb",
            "space_quota_definition_url": "/v2/space_quota_definitions/f89e0647-d685-41c1-9ea6-e52f5d8a3669",
            "developers_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/developers",
            "managers_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/managers",
            "auditors_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/auditors",
            "apps_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/apps",
            "routes_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/routes",
            "domains_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/domains",
            "service_instances_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/service_instances",
            "app_events_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/app_events",
            "events_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/events",
            "security_groups_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/security_groups",
            "staging_security_groups_url": "/v2/spaces/0ac1fe96-ccc0-4256-a9ac-5e47dc839f52/staging_security_groups"
          }
        },
        "service_bindings_url": "/v2/user_provided_service_instances/7904c61e-8b2f-4380-adbc-1268dbc3ed18/service_bindings",
        "service_bindings": [

        ],
        "service_keys_url": "/v2/user_provided_service_instances/7904c61e-8b2f-4380-adbc-1268dbc3ed18/service_keys",
        "service_keys": [

        ],
        "routes_url": "/v2/user_provided_service_instances/7904c61e-8b2f-4380-adbc-1268dbc3ed18/routes",
        "routes": [

        ]
      }
    }
  ]
}
Updating service instance my-db-mine as u333...

REQUEST: [2017-04-01T15:41:18+03:00]
PUT /v2/service_instances/7904c61e-8b2f-4380-adbc-1268dbc3ed18?accepts_incomplete=true HTTP/1.1
Host: (hidden)
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / darwin

{"tags":["ala","bala"]}

RESPONSE: [2017-04-01T15:41:18+03:00]
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 99
Content-Type: application/json;charset=utf-8
Date: Sat, 01 Apr 2017 12:41:18 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 77f5498c-f280-46f7-791d-09d8e65729bc
X-Vcap-Request-Id: 77f5498c-f280-46f7-791d-09d8e65729bc::eeb0e60a-67eb-4a76-bcff-fbd3b7d99028

{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

## Platform & Shell Details  

Mac OS X 10.12.4
Terminal 2.7.2

**Comment by dkoper** [comment] 2017-04-01 22:36
@zrob 500?

**Comment by zrob** [comment] 2017-05-22 17:45
The issue is the request to manage the user provided service resource is going to `/v2/service_instances` rather than `/v2/user_provided_service_instances`.  The cli could direct to the correct endpoint based on `type`.

Story to improve the error message: https://www.pivotaltracker.com/story/show/145872931

As for the request to support tags, that request could be made to the https://github.com/cloudfoundry/cloud_controller_ng repo.

**Comment by dkoper** [comment] 2017-05-24 03:27
@dotchev We'll improve the message on the CLI as well, when we refactor `update-service`.

**Comment by abbyachau** [comment] 2018-05-25 18:18
@dotchev thanks for creating this issue. Closing this issue because it appears we do throw a more succinct message when attempting to use the `-t` flag with `cf cups`. For example:
```
$ ./cf cups dodo -t "la"
Incorrect Usage: unknown flag `t'
``` 
We also have a pull request for supporting tags for user provided services [#1384](https://github.com/cloudfoundry/cli/pull/1384), so I'm marking this issue as a dupe. Please track the pull request, thank you again.

**Closed by abbyachau** 2018-05-25 18:18 UTC
Labels: bug, pending-refactor, scheduled
