### ISSUE TITLE
cf fails with" mkdir P:: The system cannot find the path specified."

### ISSUE THREAD

**Issue by mwrothbe** [cloudfoundry/cli#1748] opened 2019-08-09 01:18 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
When installed for all users (Admin) on Win10, any CF command fails with:

> mkdir P:: The system cannot find the path specified.
> FAILED

CF commands work as expected when installed for current user, but then admin shell cannot reach the exe.
**What happened**
'CF' commands used to work on my machine installed for all users.  Suddenly any CF command results in the error above.  I don't know what changed to make this happen.  I have had a P network drive the entire time.  I do not use it for CF and I don't remember ever setting it up in CF installation.  I've uninstalled CF, deleted .cf folders in my user home and on the P drive.  But after reinstalling with latest version, the failure persists. I've tried setting the CF_HOME variable to a different directory, but no change.

**Expected behavior**
Administrative install should work.

**To Reproduce**
Not clear how a different machine wold reproduce.  if I type 'CF' I get the fail message.

**Provide more context**
Win10, 6.46.0_win64

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by mwrothbe** [comment] 2019-08-12 13:55
Any comment or pointers?  I'm still dead in the water with CF CLI.

**Comment by abbyachau** [comment] 2019-08-13 19:13
Hi @mwrothbe thanks for raising this. We'll review as soon as we can - in the meantime, you could try #General on Cloud Foundry Slack to see if there's anyone has any tips.

**Comment by a-b** [comment] 2019-08-21 17:41
We tried to reproduce your problem on Windows v.1905 VM, and we were unable to reproduce it:
1. Install `cf` with installer with Admin for All Users
1. We uninstall `cf` using provided uninstaller executable
1. Checked config file for the presence any path

Do you still have this issue? If the answer is yes, can you please provide detailed steps to reproduce.

**Comment by abbyachau** [comment] 2019-09-18 17:31
Hi @mwrothbe thanks for creating this issue. Since we were not able to reproduce it, and there hasn't been any activity recently, I'm closing this issue. Please reach out to #general on Cloud Foundry Slack to see if any one there could further assist you. Sorry we were not able to help more.

**Closed by abbyachau** 2019-09-18 17:31 UTC
Labels: unscheduled

**Comment by ingoschaal** [comment] 2019-10-02 12:34
hi
i had same problem mkdir u:: The system cannot find the path specified
this solution works for me
https://letsgivebackblog.wordpress.com/2017/12/04/cloudfoundry-command-line-error-the-system-cannot-find-the-path-specified/

**Comment by hoegaarden** [comment] 2019-11-07 16:28
We just saw the same issue at a customer where they supposedly didn't have write access to wherever the windows cli want's to place the config. As the linked article in [the above comment](https://github.com/cloudfoundry/cli/issues/1748#issuecomment-537471470) suggests, we could work around by setting `%CF_HOME%` to something else.

I am not sure about the customer's setup, but I assume they have the `%HOMEDRIVE%` on a network share and that might bring some issues maybe?

Can we please re-open this issue?

I think it would be great if instead of printing this cryptic (and confusing: mkdir on windows? what's happening!? :smirk:) to present the user with a more meaningful message. This error could probably just be caught and bubbled up as something like: `Could not write config to "c:\some\path", consider setting CF_HOME to place your configuration elsewhere.`?

**Comment by draschke** [comment] 2020-04-11 11:24
@ingoschaal thanks for this link. this solved my issue: SET HOMEDRIVE=C:
