### ISSUE TITLE
Feature Request: add timeout option to cf login

### ISSUE THREAD

**Issue by pratikmallya** [cloudfoundry/cli#815] opened 2016-04-13 12:26 UTC
E.g. when accessing private clouds over vpn, it often takes very long. The user should be able to specify the timeout to login successfully without timing out.

**Comment by dkoper** [comment] 2016-05-27 06:52
There are several places where a command can time out. Rather than making them all configurable, which will not likely be easy to use for most people without deep TCP level knowledge, we should address the causes of the time out. E.g. why is your connection over the vpn slow.

**Comment by dkoper** [comment] 2016-06-11 01:52
Closing as we're not going to make all timeouts configurable.

**Closed by dkoper** 2016-06-11 01:52 UTC
Labels: enhancement
