### ISSUE TITLE
Cannot use Cloud Foundry command line

### ISSUE THREAD

**Issue by jemartineza** [cloudfoundry/cli#1027] opened 2016-12-08 20:24 UTC
* Command  
cf login

* What occurred, incl. error and/or stack trace
←[31;1mFAILED←[0m
Error read/writing config:  unexpected end of JSON input

* What you expected to occur
Open promt API>

* CLI Version  
_cf-cli-installer_6.22.2_winx64

* Platform & Shell Details  
Windows 8.1 64-bit

* Any other relevant information  
I reinstalled several times. Even I downloaded the binary and show the same error all the time

**Comment by AdrianLThomas** [comment] 2016-12-13 20:08
Hi,
I've been having the same issue but managed to resolve it.

The issue was that the cf.exe config was reading from an empty / 0kb file located here:
C:\Users\<Your.Username>\.cf\config.json

I deleted this file and it was recreated and the command line continued to work as normal. I guess if you do have some valid config in there then it may be worth making a backup of it first.

**Comment by jemartineza** [comment] 2016-12-13 21:29
Great Adrian!!

I renamed the file, executed the command and it works again

Thank you very much!

Ernesto

**Comment by dkoper** [comment] 2016-12-13 21:49
@jemartineza @AdrianLThomas We've had a similar report quite recently. If you can figure out why your config.json got empty/corrupted/stopped working, please let us know. Maybe there is a plugin, or even a cf CLI corner case that corrupts it and we should address that.

Cheers,
Dies Koper
CF CLI PM

**Comment by AdrianLThomas** [comment] 2016-12-14 12:32
@dkoper I think I started noticing the issue when I was setting a password in the HTTP_PROXY / HTTPS_PROXY environment variables. I had a special character in my password (a colon). I think from then on I started to see the issue (even after I had removed the environment variable.

Hope that helps,
Adrian

**Comment by dkoper** [comment] 2016-12-16 12:11
@AdrianLThomas I tried setting http_proxy with a password with a colon and doing a `cf login` on Windows 7 64 bit but could not reproduce the issue.

I don't think we have enough information to investigate deeper.

Closing. Feel free to reopen or submit a new issue if you run into it again and have reproducible steps for us, or at least more details for us to go from.

**Closed by dkoper** 2016-12-16 12:11 UTC
Labels: unscheduled

**Comment by arobinsongit** [comment] 2016-12-18 04:09
I also ran into this issue.  Relevant details below with initiating steps on my build

- Command

cf login

- What occurred, incl. error and/or stack trace
←[31;1mFAILED←[0m
Error read/writing config: unexpected end of JSON input

- What you expected to occur
Receive API endpoint> prompt

- CLI Version
_cf-cli-installer_6.22.2_winx64

- Platform & Shell Details
Windows 10 Pro 64 bit with recent updates

- Recreate Steps
0. Created CF_HOME environment variable pointed to D:\CF_HOME (folder previously created but empty)
1. open command prompt
2. C:\WINDOWS\system32>cf login
3.  Receive API endpoint> prompt
4. CTRL+C
5. C:\WINDOWS\system32>cf logout
6. [31;1mFAILED[0m
Error read/writing config:  unexpected end of JSON input
7. C:\WINDOWS\system32>cf login
[31;1mFAILED[0m
Error read/writing config:  unexpected end of JSON input
8. Inspect config.json in D:\CF_HOME\.cf
9. config.json file is empty - 0 kb
10. Delete config.json
11. C:\WINDOWS\system32>cf login
12.  Receive API endpoint> prompt
13. Inspect config.json --> json file is populated.  See attachment.
[Step13-config.json.txt](https://github.com/cloudfoundry/cli/files/659238/Step13-config.json.txt)
14. Repeat cf login with CTRL+C combination twice

C:\WINDOWS\system32>cf login

API endpoint>
C:\WINDOWS\system32>cf login

API endpoint>
C:\WINDOWS\system32>

15. No further issues encountered.  config.json remains valid.

- Any other relevant information
It seems that if config.json does not exist and you CTRL+C on the first cf login attempt a blank config.json file is written.  On subsequent cf login attempts the system attempts to read config.json but it is blank and so it throws the referenced error.

Hope this helps with the recreation for bug fix.
