### ISSUE TITLE
cf unbind-service doesn't strip colors from output when piped

### ISSUE THREAD

**Issue by lflux** [cloudfoundry/cli#1237] opened 2017-10-03 22:15 UTC
## Command  

`cf unbind-service`

## What occurred

`cf unbind-service spring-music test-service  | cat`  does not strip output colors, unlike `cf bind-service`

![screen shot 2017-10-03 at 3 13 09 pm](https://user-images.githubusercontent.com/184966/31151698-82275036-a84d-11e7-98e0-64785973d1d7.png)

## What you expected to occur

ANSI colors to be stripped from the output when piped

## CLI Version  

`cf version 6.32.0+0191c33d9.2017-09-26`

## CC API Endpoint Version  

`api version:    2.96.0`

## Platform & Shell Details  
OSX 10.12.6 iTerm

**Comment by dkoper** [comment] 2017-10-04 02:21
Good catch! We'll fix it.

**Comment by tylerphelan** [comment] 2017-12-06 22:29
@dkoper Any updates on this?

**Comment by dkoper** [comment] 2017-12-06 22:50
The issue is not so much with this particular command, but with a lot of commands because the tty auto-detection process has issues. All of this should be fixed as part of a story where we introduce a new `auto` value for `cf config --color`, but we haven't reached that story yet (other higher priority features keep pushing it back).
In the meantime, you should be able to suppress color using either `cf config --color false`, or simply `CF_COLOR=false cf unbind-service spring-music test-service | cat`.

**Comment by youreddy** [comment] 2018-01-16 19:15
@dkoper We're currently using the CF_COLOR=false workaround in our tests which works for now. However it's not ideal since new team members can't easily discover this problem around bind-service. Can you provide us the link to the story you mentioned?

**Comment by dkoper** [comment] 2018-02-10 04:31
@youreddy This one: https://www.pivotaltracker.com/story/show/119446319

**Comment by XenoPhex** [comment] 2018-04-30 19:03
Looks like this has been fixed in the latest version of the CF CLI.

**Closed by XenoPhex** 2018-04-30 19:03 UTC
Labels: bug, scheduled
