### ISSUE TITLE
Folder with .gitignore gets not pushed

### ISSUE THREAD

**Issue by ninifi** [cloudfoundry/cli#1711] opened 2019-07-03 12:09 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
When I `cf push` an app with a folder that only contains a `.gitignore` file the folder gets not pushed. It seems that [this stackoverflow issue](https://stackoverflow.com/questions/56786657/empty-folder-with-gitignore-in-it-wont-be-pushed-with-cf-cli) is about the same problem.

**What happened**
The folder gets not pushed. No error or something.

**Expected behavior**
I expect that the folder gets pushed as described in the [release notes of the version 6.34](https://github.com/cloudfoundry/cli/releases/tag/v6.34.0).
> Folders containing only a .gitignore file are now included.

It has been requested by [this issue](https://github.com/cloudfoundry/cli/issues/993).

**To Reproduce**
mkdir test
cd test
mkdir shouldBePushed
touch shouldBePushed/.gitignore
touch index.html

Then you can just push the app.

**Provide more context**
- Windows 10 git-bash, macOS High Sierra Hyper
- CLI Version 6.45
- API Version 2.134.0

**Comment by acrmp** [comment] 2019-07-04 22:29
Hi @ninifi,

Thanks for raising this issue. The following seems to work for me with CF CLI 6.45.0 (the `shouldBePushed` directory exists in the container):

```
$ mkdir test && cd test && mkdir shouldBePushed && touch shouldBePushed/.gitignore && touch index.html
$ cf push -b staticfile_buildpack some-app
$ cf ssh some-app --command 'ls app/public'
index.html
shouldBePushed
```

Can you try these steps and see if they work for you? Perhaps this is somehow related to the buildpack
you are using?

Thanks,

Andrew.

**Comment by ninifi** [comment] 2019-07-05 06:58
@acrmp thanks for your response.

Unfortunately this does not solve the problem for me. After running your commands I only get `index.html` as response from `cf ssh some-app --command 'ls app/public`. I already used the staticfile buildpack before.

Even if I create a `.cfignore` in my test folder with the line `!/shouldBePushed` as mentioned in [this ](https://github.com/cloudfoundry/cli/issues/993) issue - it does not help.

**Comment by acrmp** [comment] 2019-07-05 21:43
Hi @ninifi,

I re-tested with CF CLI 6.45.0 against your API version (2.134.0 - specifically cf-deployment v8.1.0) and it is still working for me.

Can you try enabling debug logging to see if the cli is including `shouldBePushed` in the set of resources sent to the server?

```
$ CF_LOG_LEVEL=debug cf push -b staticfile_buildpack some-app 2>&1 | grep -C20 'Comparing local files to remote cache...'
```

Thanks,

Andrew.

**Comment by ninifi** [comment] 2019-07-10 07:22
Hi @acrmp 

I get the following output:

```
routes:
    test-dev.scapp.swisscom.com

Updating app test-dev...
time="2019-07-10T09:19:04+02:00" level=debug msg="starting apply go routine"
time="2019-07-10T09:19:04+02:00" level=info msg="received apply event: setting up application"
time="2019-07-10T09:19:04+02:00" level=debug msg="ignoring event" event="setting up application"
time="2019-07-10T09:19:04+02:00" level=debug msg="updating application"
time="2019-07-10T09:19:04+02:00" level=debug msg="updating application with these settings" application="App Name: 'test-dev', Buildpack (true, 'staticfile_buildpack'), Command: (false, ''), Detected B
uildpack: (true, 'staticfile'), Detected Start Command: (true, '$HOME/boot.sh'), Disk Quota: '1024', Docker Image: '', Health Check HTTP Endpoint: '', Health Check Timeout: '0', Health Check Type: 'por
t', Instances: (true, '1'), Memory: '1024', Space GUID: '3851830e-5c10-42cf-84a0-f986c9ad2745', Stack GUID: 'c4e4f4e5-0c26-4735-ac83-5afb8b88d5bc', State: ''"
time="2019-07-10T09:19:06+02:00" level=info msg="received apply event: updated application"
time="2019-07-10T09:19:06+02:00" level=debug msg="ignoring event" event="updated application"
time="2019-07-10T09:19:06+02:00" level=debug msg="desired application: pushaction.Application{Application:v2action.Application{Buildpack:types.FilteredString{IsSet:true, Value:\"staticfile_buildpack\"}
, Command:types.FilteredString{IsSet:false, Value:\"\"}, DetectedBuildpack:types.FilteredString{IsSet:false, Value:\"\"}, DetectedStartCommand:types.FilteredString{IsSet:false, Value:\"\"}, DiskQuota:t
ypes.NullByteSizeInMb{IsSet:true, Value:0x400}, DockerCredentials:ccv2.DockerCredentials{Username:\"\", Password:\"\"}, DockerImage:\"\", EnvironmentVariables:map[string]string(nil), GUID:\"39475095-57
ac-4fc7-b1d3-43d8749ae2a7\", HealthCheckTimeout:0x0, HealthCheckType:\"port\", HealthCheckHTTPEndpoint:\"\", Instances:types.NullInt{IsSet:true, Value:1}, Memory:types.NullByteSizeInMb{IsSet:true, Valu
e:0x400}, Name:\"test-dev\", PackageState:\"PENDING\", PackageUpdatedAt:time.Time{wall:0x0, ext:63698339846, loc:(*time.Location)(nil)}, SpaceGUID:\"3851830e-5c10-42cf-84a0-f986c9ad2745\", StackGUID:\"
c4e4f4e5-0c26-4735-ac83-5afb8b88d5bc\", StagingFailedDescription:\"\", StagingFailedReason:\"\", State:\"STARTED\"}, Buildpacks:[]string{\"staticfile_buildpack\"}, Stack:v2action.Stack{GUID:\"c4e4f4e5-
0c26-4735-ac83-5afb8b88d5bc\", Name:\"cflinuxfs3\", Description:\"Cloud Foundry Linux-based filesystem (Ubuntu 18.04)\"}}"
time="2019-07-10T09:19:06+02:00" level=info msg="creating routes"
time="2019-07-10T09:19:06+02:00" level=info msg="received apply event: creating and mapping routes"
time="2019-07-10T09:19:06+02:00" level=debug msg="already exists, skipping" route=test-dev.scapp.swisscom.com
Mapping routes...
time="2019-07-10T09:19:06+02:00" level=info msg="mapping routes"
time="2019-07-10T09:19:06+02:00" level=debug msg="route test-dev.scapp.swisscom.com already bound to app"
time="2019-07-10T09:19:06+02:00" level=debug msg="mapping routes complete"
time="2019-07-10T09:19:06+02:00" level=info msg="received apply event: resource matching"
Comparing local files to remote cache...
time="2019-07-10T09:19:06+02:00" level=debug msg="sending resource match stats" chunks=1 resources_to_match=1 total_resources=2
time="2019-07-10T09:19:06+02:00" level=debug msg="total number of matched resources" matched_resource_count=0
time="2019-07-10T09:19:06+02:00" level=info msg="creating archive"
time="2019-07-10T09:19:06+02:00" level=info msg="zipping source files from directory" sourceDir="C:\\Users\\tgdroni6\\PhpstormProjects\\test"
time="2019-07-10T09:19:06+02:00" level=debug msg="zipping file" fullPath="C:\\Users\\tgdroni6\\PhpstormProjects\\test\\index.html"
time="2019-07-10T09:19:06+02:00" level=debug msg="resource file info" file-mode=-rw-rw-rw-
time="2019-07-10T09:19:06+02:00" level=debug msg="setting mode for file" destPath=index.html mode=-rwxrw-rw- srcPath="C:\\Users\\tgdroni6\\PhpstormProjects\\test\\index.html"
time="2019-07-10T09:19:06+02:00" level=debug msg="zipping file" fullPath="C:\\Users\\tgdroni6\\PhpstormProjects\\test\\shouldBePushed"
time="2019-07-10T09:19:06+02:00" level=debug msg="resource file info" file-mode=drwxrwxrwx
time="2019-07-10T09:19:06+02:00" level=debug msg="setting mode for file" destPath=shouldBePushed/ mode=drwxr-xr-x srcPath="C:\\Users\\tgdroni6\\PhpstormProjects\\test\\shouldBePushed"
time="2019-07-10T09:19:06+02:00" level=info msg="zip file created" zip_file_location="C:\\Users\\tgdroni6\\AppData\\Local\\Temp\\cf-cli-058697131" zipped_file_count=2
time="2019-07-10T09:19:06+02:00" level=debug msg="archive created" archivePath="C:\\Users\\tgdroni6\\AppData\\Local\\Temp\\cf-cli-058697131"
time="2019-07-10T09:19:06+02:00" level=info msg="uploading archive"
time="2019-07-10T09:19:06+02:00" level=info msg="received apply event: creating archive"
Packaging files to upload...
time="2019-07-10T09:19:06+02:00" level=debug msg="uploading app bits" appGUID=39475095-57ac-4fc7-b1d3-43d8749ae2a7 archiveSize=285
time="2019-07-10T09:19:06+02:00" level=debug msg="new progress bar" file_size=285
time="2019-07-10T09:19:06+02:00" level=info msg="received apply event: uploading application with archive"
Uploading files...
time="2019-07-10T09:19:06+02:00" level=debug msg="starting progress bar"
```

But the folder is still not uploaded to the public folder.

Nicola

**Comment by acrmp** [comment] 2019-07-23 22:21
Hi @ninifi,

Thanks for the additional debug output. It seems from your output as though the CLI is including `shouldBePushed` in the set of files uploaded to the server.

Is your CloudFoundry foundation based on cf-deployment? If so which version is it using? Can you also share the version of the staticfile buildpack output when you run `cf buildpacks`?

Thanks,

Andrew.

**Comment by abbyachau** [comment] 2019-08-01 23:32
Hi @ninifi thanks for creating this issue. I'm closing this since we were unable to reproduce the issue. If you continue to have this issue, please use Cloud Foundry Slack #General to see if anyone can help triage there. Thanks again.

**Closed by abbyachau** 2019-08-01 23:32 UTC
Labels: unscheduled
