### ISSUE TITLE
cf create-app-manifest crashes

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#549] opened 2015-08-17 04:08 UTC
crash info is below.

```
$ cf create-app-manifest demoimages -p .
Creating an app manifest from current settings of app demoimages ...



	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		/usr/local/bin/cf create-app-manifest demoimages -p .

	using this version of the CLI:

		6.12.2-3c9cbd3

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0xe1b6a8, 0xc208114630)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc208216c60, 0xc2088252f0, 0x24, 0xc20882cbe0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x85
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc208216c60, 0xe1d178, 0xc20821ecc0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4d2
	main.main()
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/

$ cf curl /v2/info
{
   "name": "vcap",
   "build": "2222",
   "support": "http://support.cloudfoundry.com",
   "version": 2,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.33.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "logging_endpoint": "wss://loggregator.run.pivotal.io:4443",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "user": "fddc8de4-cd75-4987-8056-bed811df484e"
}

```

**Comment by afeld** [comment] 2015-08-27 06:31
Duplicate of #536.

**Comment by simonleung8** [comment] 2015-09-02 00:09
Thanks for filing the bug, we have a story in the tracker and will be fixed in the next release.

https://www.pivotaltracker.com/story/show/101367528

**Closed by simonleung8** 2015-09-02 00:09 UTC
