### ISSUE TITLE
cf services shows upgrade available incorrectly

### ISSUE THREAD

**Issue by pnikonowicz** [cloudfoundry/cli#1757] opened 2019-08-19 20:18 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**To Reproduce**

update a service broker so that a service upgrade is available. 
run `cf s`
verify that an upgrade is available
example:
```
Getting services in org test_org / space test_space as admin...

name                  service        plan          bound apps   last operation     broker              upgrade available
extra-small-service   p-cloudcache   extra-small                update succeeded   cloudcache-broker   yes
test1                 p-cloudcache   dev-plan                   update succeeded   cloudcache-broker   yes
```

run `cf upgrade-service <service_name> -c '{<some json here>}'`
watch the service update `watch --color cf s`
when the service finishes updating run `cf s`

Expected: 
either an upgrade should no longer be available, or the cf cli should have never allowed the `-c` option to succeed without the `--upgrade` flag

Actual:
the `cf s` command shows that the service that was just updated has an upgrade available. 

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
Mac OS X

- version of the CLI you are running
cf version 6.46.0+29d6257f1.2019-07-09

- version of the CC API Release you are on

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by waterlink** [comment] 2019-08-20 16:26
@pnikonowicz 

Hey, thank you for reporting this issue!

I’m curious, could you explain in more detail, why you’re expecting to see upgrade happen if you’re not providing the `--upgrade` flag?

To my knowledge, the upgrade-one feature is designed in a way, that `--upgrade` and `-c` are independent, and if `--upgrade` is not provided, then Cloud Controller is not going to tell the broker to update the version of `maintenance_info`. (see the OSBAPI spec here: https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-6)

**Comment by pnikonowicz** [comment] 2019-08-21 13:41
That appears to be what happens. But because there is only one broker at any time, when a service instance is updated, the service instance is using the new broker and not an older broker. Therefore the service instance is updated to the newest broker. 

For our service broker (PCC), we have each broker contain a static version number that is stored in `maintenance_info` that appears to be returned to the cli. 

To be clear, we are not expecting an upgrade to happen, but we are expecting the cli to represent accurately the state of our cf foundation. In this case, the cli is stating that there is an upgrade available when there is not.

**Comment by pnikonowicz** [comment] 2019-08-21 22:01
If I understand you correctly, this wouldn't be a bug in the cli because the cli just tells the Cloud Controller what was entered. It's up to the service broker to interpret that message correctly. Is this correct? If so, we can close this issue.

**Comment by waterlink** [comment] 2019-08-27 12:33
I’m afraid that in the CLI, right now, there is logic specifically preventing `-c` (or `-p`) and `--upgrade` combination of arguments.

In the Cloud Controller, it is possible to pass `parameters` and `maintenance_info` at the same time.

Is your situation that the broker will automatically update the `maintenance_info` if any kind of `parameters` are passed (even if `maintenance_info` is not provided) in the PATCH request? (perhaps because it does a new bosh deployment and that just upgrades to latest release?)

Because if it is true, then to support that we’d need a way for CF to be informed of this change, or the broker should make `parameters` change without `maintenance_info` update not possible. Otherwise, information in CF and service broker will get out of sync. Of course, in this scenario, CLI should allow combination of `-c` and `--upgrade`.

What are your thoughts or questions given the information above?

**Comment by waterlink** [comment] 2019-08-28 09:29
I double-checked the behaviour of ODB and it’s going to reject the request to update the parameters if the maintenance_info of the service instance is outdated. In your scenario, the CLI user will have to perform `cf update-service my-service --upgrade` before they can do `cf update-service my-service -c '...'`.

So, here is what I’d expect to happen:

```
1. run `cf upgrade-service <service_name> -c '{<some json here>}'`
2. watch the service update `watch --color cf s`
3. when the service finishes updating run `cf s`

Expected:
4. the service still has an update available
5. the service last operation status is `update failed`
6. when looking at the details of the failure with `cf service <service_name>`
7. it has a descriptive message that the service instance need to be upgraded first
```

Does it sound right to you? From this perspective, is that what’s happening or there is a difference between Expected and Actual?

**Comment by pnikonowicz** [comment] 2019-09-05 19:46
Here is the result of the steps that you outlined. Notice at the end that the update **succeeded** but there is still a service update marked as available. 

initial status:
```
└─▪ cf s
Getting services in org test_org / space test_space as admin...

name                  service        plan          bound apps   last operation     broker              upgrade available
extra-small-service   p-cloudcache   extra-small                create succeeded   cloudcache-broker   yes
```

>1. run `cf upgrade-service <service_name> -c '{<some json here>}'`
```
└─▪ cf update-service extra-small-service -c '{"restart":true}'
Updating service instance extra-small-service as admin...
OK

Getting services in org test_org / space test_space as admin...

name                  service        plan          bound apps   last operation       broker              upgrade available
extra-small-service   p-cloudcache   extra-small                update in progress   cloudcache-broker   yes
```
> 2. watch the service update `watch --color cf s`
> 3. when the service finishes updating run `cf s`
```
Getting services in org test_org / space test_space as admin...

name                  service        plan          bound apps   last operation     broker              upgrade available
extra-small-service   p-cloudcache   extra-small                update succeeded   cloudcache-broker   yes
```

> Expected:
> 4. the service still has an update available

It does, but it should not because the service was just updated

> 5. the service last operation status is `update failed`

Service update succeeded

> 6. when looking at the details of the failure with `cf service <service_name>`

there is no error listed
```
Showing available upgrade details for this service...

upgrade description:

TIP: You can upgrade using 'cf update-service extra-small-service --upgrade'
```

**Comment by waterlink** [comment] 2019-09-16 11:58
> > Expected:
> > 4. the service still has an update available

> It does, but it should not because the service was just updated

@pnikonowicz 

I don’t understand why do you think so…

"Update" and "Upgrade" are slightly different concepts.

While the service was "updated" (its "-c" parameters changed), the service shouldn’t have been "upgraded" (because "--upgrade") wasn’t passed. Only by passing "--upgrade" shall "maintenance_info" version be updated.

If your broker is doing an maintenance upgrade when one passes "-c"—this is an unexpected behaviour.

**Comment by pnikonowicz** [comment] 2019-09-24 21:03
PCC uses the ODB broker so most of this is handled for us. But in order to get the upgrade available to show as `yes`, we need to register a new broker with cf. 

This means that any activity with the broker from that point on is essentially an upgrade. 

I suppose another way to verify this is: 
1. do the `cf update-service` without the upgrade flag. 
2. download the service instance manifest
3. do the `cf update-service` with the upgrade flag
4. download the service instance manifest again. 

I would expect the two manifests to be equal. That's because they are using the new broker both times.

**Comment by blgm** [comment] 2019-09-26 13:45
I think another way to look at it is this:
1) A service instance is created when the ODB adapter is a v1
2) The ODB adapter is updated to v2, and the broker is re-registered
3) `cf s` shows that an update is available
4) `cf update-service s1 -c ....` is run
5) The ODB adapter is asked to generate a new manifest with the new `-c ...` config. Because the adapter is a v2 adapter, the service instance is updated to v2. Why? Because adapters always generate a manifest of the latest version.
6) The service instance shows that an update is still available, but in reality it is not

Subsequently, if `cf update-service s1 --upgrade` is run, it will update the Cloud Controller database, but the service instance will not be upgraded, because this has already happened as a side-effect of (4)

I think there is agreement here that step (4) should not have succeeded. Changes to the service instance should be blocked until the service instance is upgraded. Otherwise the results of any changes are hard to reason about, and leave the Cloud Controller database inconsistent with the state of the world.

**Comment by waterlink** [comment] 2019-09-26 15:08
@blgm @pnikonowicz 

To make the step (4) fail, we’d have to modify logic on ODB side, wouldn’t we?

**Comment by pnikonowicz** [comment] 2019-10-04 15:06
Not necessarily. 

The -c flag is a flag for the cf-cli. I suppose the logic follows:

```
if cliFlag.contains('-c') AND cloudControllerService.getStatus().isUpdateAvailable() {
    panic("you cannot do a -c flag when and update is available. please update your service first with the --upgrade cli flag")
}
```

**Comment by waterlink** [comment] 2019-10-07 13:08
Hmm, in that case it’d be better if Cloud Controller had that check during the execution of the update action. That is because we want to keep the CLI command to never check whether update is available or not, and just defer the decision to CloudController. At least, that was the original plan when implementing the update-one feature, architecture-wise.

**Comment by waterlink** [comment] 2019-10-15 10:51
@pnikonowicz 

We have initially made this change in CAPI, but after more thinking, and taking OSBAPI and other brokers (non-ODB) in consideration, we decided to make that decision in ODB instead, and only add all relevant information to the PATCH request from CAPI to broker, so that the broker can make a decision to accept or reject it.

Here is the tracker story: https://www.pivotaltracker.com/story/show/169087442

**Comment by waterlink** [comment] 2019-10-15 14:11
Here is the story for ODB side: https://www.pivotaltracker.com/story/show/169123444

**Comment by abbyachau** [comment] 2019-11-05 18:41
Closing this issue because it was implemented on the API side. Thanks.

**Closed by abbyachau** 2019-11-05 18:41 UTC
Labels: accepted, sapi
