### ISSUE TITLE
Be smart about printing output to non-ttys

### ISSUE THREAD

**Issue by krishicks** [cloudfoundry/cli#864] opened 2016-06-17 17:01 UTC
All commands that output tabular/list data, e.g. `cf spaces` should _not_ include informational text, colors, or headers. It should only include the values the command describes, e.g.:

```
Getting spaces in org system as admin...

name
system
notifications-with-ui
autoscaling
iaas-brokers
```

Should become:

```
system
notifications-with-ui
autoscaling
iaas-brokers
```

This will allow piping the output or redirecting it to a file without having to remove headers, as in the following: 

```
cf spaces | tail -n+4
```

and

```
cf spaces | tail -n+4 > cf-spaces
```

https://github.com/mattn/go-isatty

See how `fly` uses it: https://github.com/concourse/fly/blob/d5d94b7de95b9ddf192378fa0416846d1016dbf6/ui/table.go#L34

**Comment by dkoper** [comment] 2016-06-21 02:30
Thanks Kris, that's a great idea!
When we introduced ansi coloring for Windows, colors were also removed from non-ttys, which turned out to be a decremented UX for certain cases (#840). We should explore the impact of such a breaking change.
I'm also concerned this means `cf some-command-with-long-output > some-file.txt` won't give the same output to copy & paste into e.g. a bug report.
Not sure why you included the `go-isatty` link. Is that an implementation suggestion? There wasn't much in terms of descriptions there.

**Comment by krishicks** [comment] 2016-06-21 10:55
I don't consider removal of colors to be a breaking change in a non-TTY use-case; if anything it's a breaking change to *add* colors as they add a bunch of garbage (read: colors) to the output. That colors existed for non-TTYs is a bug.

For a bug report that is not an error, it's more reliable to record a screenshot rather than copy/paste the output because doing so means information is lost, e.g. colors and formatting of spaces/tabs may be lost          ; a screenshot should be preferred in this case.

For a bug report that is an error, it should be printed to stderr so as not be affected by piping or redirecting unless forced to do so.

**Comment by XenoPhex** [comment] 2018-04-12 21:28
Closing as a dupe of #851.

We plan on eventually adding support for TTY detection in the CF CLI output, however it's super low priority right now. We'll keep this issue in mind when we have the opportunity to schedule some of that work.

**Closed by XenoPhex** 2018-04-12 21:28 UTC
Labels: enhancement, unscheduled
