### ISSUE TITLE
Consider support for HTTP proxy authentication incl windows NTLM 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#577] opened 2015-09-14 07:37 UTC
Some CLI users are behind a corporate firewall requiring NTLM authentication. The current workaround for these users to allow connecting to public CloudFoundry instances such as IBM bluemix or pivotal PWS, it to install a local http proxy such as CNTLM which exposes a local http proxy without authentication support.

This has the following drawbacks:
- requires a set up task by every CL user
- local http proxy such as cntlm are sometimes unreliable and may interfere with CF CLI requests, in particular for high request rates over HTTP persistent connection, see [bug 61](http://sourceforge.net/p/cntlm/bugs/61/) as an example

More details about NTLM authentication protocol
https://msdn.microsoft.com/en-us/library/ms789031%28v=vs.110%29.aspx
https://msdn.microsoft.com/en-us/library/dd925287%28v=office.12%29.aspx

This problem is not visible to cf users using UIs since most browsers support ntlm proxy authentication
https://www.chromium.org/developers/design-documents/http-authentication
https://support.mozilla.org/en-US/questions/926378 and detailed docs about [network.automatic-ntlm-auth.allow-proxies](http://kb.mozillazine.org/Network.automatic-ntlm-auth.allow-proxies)
http://stackoverflow.com/questions/5541365/configure-ntlm-for-opera-and-safari-and-chrome

Potential fix steps:
* add support for http proxy NTLM authentication to use current windows session. See [curl -U option](http://curl.haxx.se/docs/manpage.html#-u) for inspiration. This could be enabled through a ``cf config enable_automatic_ntml_proxy_auth true`` command
* add support for general http proxy authentication by specifying a proxy login/password (e.g. by a refinement of the HTTP_PROXY environment variable in the form of ``protocol://username:password@host:port/``  through a common
http://curl.haxx.se/docs/manpage.html#--proxy-ntlm

Example NTLM go-lang lib https://github.com/ThomsonReutersEikon/go-ntlm

I realize this enhancement suggestion may be too specific to specific user base. Feel free to close the issue if you feel so.

Some background on rationale for some organizations to use NTLM authentication for outgoing internet access http proxies:
* some industry sectors / countries have regulations that require to trace external internet traffic back to originated user accounts (e.g. SOX, or EU/FR laws)
* some computers can be run by multiple user accounts, so host IP address/mac address is not authentifying user account who triggered outgoing internet traffic 
* rather than requesting every single users to provide a named login/password in an http proxy basic auth, some orgs rely on microsoft windows current user session to authenticate the user

**Comment by dkoper** [comment] 2015-10-31 21:20
Hi Guillaume,

I don't think it's too specific, but our backlog is long. We'd welcome a PR!

Regards,
Dies Koper
* CLI team

**Comment by dkoper** [comment] 2015-11-04 22:53
Closing this feature request, priority will be managed in the tracker story (linked above).

* CLI team

**Closed by dkoper** 2015-11-04 22:53 UTC
Labels: enhancement, user experience

**Comment by melo0187** [comment] 2016-02-02 13:31
@gberche-orange thank you very much for reporting this issue and for mentioning the CNTLM workaround, too. Since the issue is still sitting there in Pivotal Tracker I went ahead and figured out how to use CNTLM to work around this issue for now. Thanks again!

**Comment by gogolok** [comment] 2017-05-30 07:57
Hey @dkoper, we at https://github.com/anynines started working on supporting HTTP proxy with NTLM authorization. We're currently working on a prototype for a customer.

Is there someone from your team we can discuss our PR with in the near future?
Or should we just use the GitHub PR mechanism and then discuss the prototype (naive implementation) how to proceed with the PR so it gets accepted?
