### ISSUE TITLE
cf login fails on v6.45.0

### ISSUE THREAD

**Issue by cx0der** [cloudfoundry/cli#1702] opened 2019-06-26 07:59 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I was trying to login using `cf login -a https://api.ng.bluemix.net --sso`

**What happened**
Got the following error message
FAILED
Error performing request: Get https://api.ng.bluemix.net/v2/info: read tcp 9.193.107.23:43406->184.31.216.214:443: read: connection reset by peer

**Expected behavior**
Login is successful

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf login -a https://api.ng.bluemix.net --sso -v`
```
API endpoint: https://api.ng.bluemix.net

REQUEST: [2019-06-26T12:31:55+05:30]
GET /v2/info HTTP/1.1
Host: api.ng.bluemix.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.45.0+5f9ff16f9.2019-06-03 / linux

FAILED
Error performing request: Get https://api.ng.bluemix.net/v2/info: read tcp 9.193.107.23:34134->23.207.156.43:443: read: connection reset by peer
```

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm) Fedora 29 zsh
- version of the CLI you are running cf version 6.45.0+5f9ff16f9.2019-06-03
- version of the CC API Release you are on

**Comment by abbyachau** [comment] 2019-06-26 20:11
Hi @cx0der thanks for creating this. Did you review possibly related issues, for example: https://github.com/cloudfoundry/cli/issues/1135?

**Comment by cx0der** [comment] 2019-06-27 08:38
@abbyachau Before creating this issue, I searched for both open and closed issues and found #1643 closer to what I was facing. But that issue was closed without much of a solution.
In the referenced issue, they were able to login, in my case login fails without much info or help on how to proceed further.
Since I was facing issues with cf-cli I went ahead and installed the ibmcloud cli tools which ships a older version of cf-cli.
```
$ pwd
/usr/local/ibmcloud/bin/cfcli
$ ./cf -v
cf version 6.41.0+dd4c76cdd.2018-11-28
$ ./cf login -a api.ng.bluemix.net --sso
API endpoint: api.ng.bluemix.net

One Time Code (Get one at https://identity-1.eu-central.iam.cloud.ibm.com/cloudfoundry/login/us-south/passcode )> 
Authenticating...
OK


                
API endpoint:   https://api.ng.bluemix.net (API version: 2.128.0)
```
Using this version I was able to login.

**Comment by abbyachau** [comment] 2019-07-01 23:21
@cx0der thank you for the response, and for checking other issues before creating this one. The eng will review soon, please bear with us until we are able to get to this issue. Thanks.

**Comment by acrmp** [comment] 2019-07-04 21:28
Hi @cx0der,

Thanks for raising this issue. I tested with 6.45.0 (also on linux) and the request to retrieve `/v2/info` against bluemix was successful.

Would you be able to re-test with the 6.45.0 CLI and see if the issue is still present? I see from the IBM status page that there may have been a bluemix incident at around the time of your initial problems.
https://cloud.ibm.com/status?selected=history

Thanks,

Andrew.

**Comment by cx0der** [comment] 2019-07-05 09:46
Retried it now and it still failed.
```
CF_TRACE=1 cf login -a api.ng.bluemix.net --sso
API endpoint: api.ng.bluemix.net

REQUEST: [2019-07-05T15:12:56+05:30]
GET /v2/info HTTP/1.1
Host: api.ng.bluemix.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.45.0+5f9ff16f9.2019-06-03 / linux

FAILED
Error performing request: Get https://api.ng.bluemix.net/v2/info: read tcp 9.193.107.23:40554->184.31.216.214:443: read: connection reset by peer
```

**Comment by acrmp** [comment] 2019-07-05 19:24
Thanks for re-testing @cx0der.

What do you get if you try to use `curl` instead?
```
$ curl 'https://api.ng.bluemix.net/v2/info'
```

You might also try testing with 6.45.0 from another network. It seems like your connection attempt is failing despite there being something listening on that host and port.

**Comment by cx0der** [comment] 2019-07-08 08:11
This is the output that I get while running `curl 'https://api.ng.bluemix.net/v2/info'`

```
$ curl 'https://api.ng.bluemix.net/v2/info'
{"name":"IBM Cloud","build":"6.8.0","support":"http://ibm.biz/bluemix-supportinfo","version":0,"description":"IBM Bluemix","authorization_endpoint":"https://iam.cloud.ibm.com/cloudfoundry/login/us-south","token_endpoint":"https://uaa.us-south.cf.cloud.ibm.com","min_cli_version":null,"min_recommended_cli_version":null,"app_ssh_endpoint":"ssh.us-south.cf.cloud.ibm.com:2222","app_ssh_host_key_fingerprint":"c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da","app_ssh_oauth_client":"ssh-proxy","doppler_logging_endpoint":"wss://doppler.us-south.cf.cloud.ibm.com:443","api_version":"2.128.0","osbapi_version":"2.14"}%
```

**Comment by acrmp** [comment] 2019-07-24 00:34
Hi @cx0der,

Thanks for sharing the curl output. We weren't able to reproduce the issue locally so it's a little difficult to debug but here are some further ideas you could try:

1. As mentioned above, you could try to test with 6.45.0 from another network
2. One difference between 6.45.0 and 6.41.0 is that they are compiled with different versions of Go (1.12 vs 1.11). You could try testing with v6.43.0 which is the last version of the CLI that was compiled with Go 1.11.
3. You could review your proxy settings if you have a proxy configured.

Thanks,

Andrew.

**Comment by cx0der** [comment] 2019-07-24 10:03
So I uninstalled v6.45.0 and installed v6.41.0 using the rpm from the releases page. Using this version, I am able to login without issues.

All the testing has been from within IBM India office network.

**Comment by cx0der** [comment] 2019-07-24 10:09
Uninstalled v6.41.0 from previous step and installed v6.43.0 using rpm from the release page and it worked as expected.

```
cf -v
cf version 6.43.0+815ea2f3d.2019-02-20
➜  ~ cf login -a https://api.ng.bluemix.net --sso                   
API endpoint: https://api.ng.bluemix.net

One Time Code (Get one at https://identity-1.eu-central.iam.cloud.ibm.com/cloudfoundry/login/us-south/passcode )> 
Authenticating...
OK


                
API endpoint:   https://api.ng.bluemix.net (API version: 2.128.0)

```

I did not have proxy configured in all the reported scenarios.

**Comment by cx0der** [comment] 2019-07-24 10:21
More testing results
Installed v6.46.0 from the release rpm, works as expected

```
cf -v
cf version 6.46.0+29d6257f1.2019-07-09
➜  ~ cf login -a https://api.ng.bluemix.net --sso                   
API endpoint: https://api.ng.bluemix.net

One Time Code (Get one at https://identity-2.ap-south.iam.cloud.ibm.com/cloudfoundry/login/us-south/passcode )> 
Authenticating...
OK


                
API endpoint:   https://api.ng.bluemix.net (API version: 2.128.0)
```

Uninstalled this and installed from v6.45.0 using the rpm from release page and works without problems!

```
cf -v                                                          
cf version 6.45.0+5f9ff16f9.2019-06-03
➜  ~ cf login -a https://api.ng.bluemix.net --sso                   
API endpoint: https://api.ng.bluemix.net

One Time Code (Get one at https://identity-1.eu-central.iam.cloud.ibm.com/cloudfoundry/login/us-south/passcode )> 
Authenticating...
OK


                
API endpoint:   https://api.ng.bluemix.net (API version: 2.128.0)
```

When I reported the issue, I used the cloudfoundry dnf repo to install cf-cli. Was there a difference between the rpm served from the github release and cloudfoundry repo? Contents of the repo

```
cat /etc/yum.repos.d/cloudfoundry-cli.repo 
[cloudfoundry-cli]
name=Cloud Foundry CLI
baseurl=https://packages.cloudfoundry.org/fedora
enabled=1
gpgcheck=1
gpgkey=https://packages.cloudfoundry.org/fedora/cli.cloudfoundry.org.key

```

**Comment by acrmp** [comment] 2019-07-26 02:49
Hi @cx0der,

Glad to hear that `cf login` is working for you with the current version of the cf-cli. I can't explain why there might have been problems with 6.45.0 from the repo versus the binary from the releases page.

We can confirm that they are the same binary with:

```
$ curl -sL 'https://packages.cloudfoundry.org/fedora/releases/v6.45.0/cf-cli-installer_6.45.0_x86-64.rpm' | rpm2archive | tar zxO ./usr/bin/cf | md5sum
81d5326efd3828003c0238cae730e062  -

$ curl -sL 'https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.45.0&source=github-rel' | tar zxO cf | md5sum
81d5326efd3828003c0238cae730e062  -
```

I'm going to close this issue as you are able to login successfully. Please do let us know if you learn anything else about why you might have been seeing this behaviour.

Thanks,

Andrew.

**Closed by acrmp** 2019-07-26 02:49 UTC
Labels: unscheduled
