### ISSUE TITLE
cf login fails with non-ascii password characters

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#560] opened 2015-08-27 13:39 UTC
Tested under windows 7, configured with french local with both MSDOS shell and cygwin, on both private cf instance and public pivotal.run.io

When the password contains an accentuated character `é` in our case, the UAA rejects the login. However, web UIs such as run.pivotal.io properly accept the login with the accentuated characters, which makes me suspect there is something related to the way the CLI sends the password. I'm suspecting the CLI suffers from a [Mojibake](https://en.wikipedia.org/wiki/Mojibake#English) bug when posting passwords to login endpoint. 

Further diagnostic follow. Hope this helps.

----

The CLI offers no way to this display the sent password even with CF_TRACE we get ``grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=...``

However here is a fiddler intercepted trace of the posted json when authenticating:

```
$ http_proxy=http://localhost:8888 cf auth userid 'é'
API endpoint: https://api.[...]
Authenticating...
FAILED
Credentials were rejected, please try again.
```

```
POST https://login.[...]/oauth/token HTTP/1.1
Host: login.[...]
User-Agent: go-cli 6.12.2-24abed3 / windows
Content-Length: 58
Accept: application/json
Authorization: Basic [...]
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

grant_type=password&password=%C3%A9&scope=&username=userid
```

We see that the password is encoded as %C3%A9 which in decimal correspond to two bytes with ascii values 195 169

As a comparison, the browsers when submitting the login form from webui such as run.pivotal.io URL encode the `é` character properly as ```password=%E9``` is single byte with 233 decimal value, as expected:

Unicode number: U+00E9 dec 233 see http://unicode-table.com/en/#00E9

%A9 is the value of é in the iso latin-1 cf http://www.ic.unicamp.br/~stolfi/EXPORT/www/ISO-8859-1-Encoding.html

This matches the symptoms of [Mojibake bug in english texts](https://en.wikipedia.org/wiki/Mojibake#English)

**Comment by camelpunch** [comment] 2015-11-02 16:33
Thanks for the report. Since it's now in Tracker, you can track its progress there.

**Comment by gberche-orange** [comment] 2015-11-02 21:39
@camelpunch @dkoper 
I see the following drawbacks when closing a reported issue while the associated story in the backlog has not been addressed/accepted for resolution:
- it is harder for CF CLI users to be aware of known limitations (it is pretty common practice to look at open issues for this purpose)
- CLI team might get duplicate issues from github, as reporters may think that's a regression
- CF CLI contributors are less likely to get support from the community (e.g. to validate the issue was indeed fixed) when this story will be tackled: there currently no way for community to watch a public pivotal tracker (i.e. be notified by email of progress of a story or comments added to it). 

Would you consider reopening this issue and closing when the story will be addressed in the backlog ?

Adding tags to issues such as "pr-welcome" or "p3-priority" might be a way to allow lower priority issues to not clutter the issues list while keeping the community engaged on reporting issues and validating fixed

Cf 

https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by dkoper** [comment] 2015-11-15 02:48
Reopened as requested.
You should be able to "watch" updates to stories in the public tracker. You do need to sign in (and sign-up is easy), and then click on the tickbox next to "Follow this story". Please try.

I wasn't able to create a new label - maybe I don't have the right permissions.

**Comment by gberche-orange** [comment] 2015-11-15 19:53
thanks @dkoper 

I believe even public pivotal trackers don't let non project members follow stories. I retried today with either signed-out or signed-in user (using Firefox 42.0 on windows). I had made the request to the pivotal tracker team for such feature for about 2 years without luck so far. I'd love to be wrong on this as this would be so much easier than regularly polling stories to be updated about their status.

**Comment by dkoper** [comment] 2015-11-18 02:34
I thought we validated that it was possible but received a reply from Tracker support that indeed it's not. Sorry about that. We'll change our strategy and not close GH issues in favor of Tracker.

**Comment by krishicks** [comment] 2016-02-25 23:19
@gberche-orange We looked into this and found that the CLI is doing the right thing; it's the web UI that is not.

We believe the problem is due to the login form not setting an accept-charset attribute, which means characters like `é` become something else; in this case, a non-accented `e`.

We've reached out to the Identity team for a solution.

**Comment by krishicks** [comment] 2016-02-25 23:30
Identity's story is here: https://www.pivotaltracker.com/n/projects/997278/stories/114531721

**Comment by staylor14** [comment] 2016-06-22 18:11
We believe that this is fixed in the latest release of UAA

The following commands all worked

    CF_TRACE=true cf auth internationalé passwordé

    curl -v -u "cf:" --data "grant_type=password&username=internationalé&password=passwordé" -H"Content-Type: application/x-www-form-urlencoded" -H"Accept:application/json" http://localhost:8080/uaa/oauth/toke

     uaac -t token owner get cf internationalé -s "" -p passwordé

All three commands yielded an access token

**Comment by fhanik** [comment] 2016-06-22 18:14
We believe this issue can be closed as not reproducible with the latest version

**Comment by dkoper** [comment] 2016-06-22 22:06
Closing as suggested. More details in the Identity story linked to above.
Feel free to re-open or create a new issue (possibly in the UAA tracker) if you still see issues with this.

**Closed by dkoper** 2016-06-22 22:06 UTC
Labels: bug
