### ISSUE TITLE
Deleting an app with routes should skip the routes which are mapped to other apps

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cli#1600] opened 2019-04-02 05:56 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
`cf delete -r appname` deletes all of routes including those which are mapped to other applications

**What happened**
Routes mapped to other applications are deleted

**Expected behavior**
Routes mapped to other applications should not be deleted

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. `cf map-route app1 -n hostname domain.com`
2. `cf map-route app2 -n hostname domain.com`
3. `cf delete -r app1`
4. `cf app app2` doesn't show hostname.domain.com being mapped

**Provide more context**
- cf version 6.43

**Comment by tjvman** [comment] 2019-04-08 20:56
Was able to reproduce by following the provided steps. Marking as a bug.

**Comment by tjvman** [comment] 2019-04-08 21:13
Noticed that this is a dupe of #751, which has some useful additional context around the problem, so I'm going to close this issue in favor of the existing one.

**Closed by tjvman** 2019-04-08 21:13 UTC
Labels: bug, unscheduled
