### ISSUE TITLE
docs: what is url to get latest cf7 7.X download?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1608] opened 2019-04-07 03:53 UTC
https://packages.cloudfoundry.org/stable?release=linux64-binary will redirect to the most recent cf-cli_6...tgz file.

How do I download the latest cf-cli_7...tgz file without explicitly stating a `version=7.0.0-beta.18` value? e.g. https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7 ?

**Comment by drnic** [comment] 2019-04-07 04:38
Perhaps https://github.com/cloudfoundry/cli/blob/master/ci/cli-v7/tasks/create-release.yml could create a `releases/latest/` folder that also contains the latest files

**Comment by drnic** [comment] 2019-04-07 05:55
For anyone who wants to easily find the cf7 files via github releases I've got a CI pipeline to push them to https://github.com/cloudfoundry-community/cf7-cli-releases/releases

**Comment by drnic** [comment] 2019-04-07 06:08
And have added `apt-get install cf7-cli` to our http://apt.starkandwayne.com

**Comment by drnic** [comment] 2019-04-07 20:53
Aside from all the aside comments, I'm still looking for something generic that can be used for `cf7` cli instead of https://github.com/concourse/cf-resource/blob/master/dockerfiles/alpine/Dockerfile#L5

**Comment by abbyachau** [comment] 2019-04-08 17:31
Hi @drnic, we have a [wiki page](https://github.com/cloudfoundry/cli/wiki/V7-Beta-Release) where you can download the latest CLI V7 beta. Please note that we've not encouraged users to use the V7 CLI beta yet because the beta release is under development - we are working to support the basic `cf7 push` functionality currently and using this command, as you've found, might have unexpected behavior.  

Please do not hesitate to get in touch if you have any questions.

**Comment by abbyachau** [comment] 2019-04-12 16:24
Hi @drnic I'm going to close this issue but don't hesitate to get in touch if you have any questions. Thanks.

**Closed by abbyachau** 2019-04-12 16:24 UTC
Labels: unscheduled
