### ISSUE TITLE
json: cannot unmarshal number 6442450944 into Go struct field .mem_quota of type int

### ISSUE THREAD

**Issue by NAGAI-Tsuyoshi** [cloudfoundry/cli#1371] opened 2018-04-27 07:30 UTC
## Command  

cf app myapp

myapp uses memory 6GB.

## What occurred

The following error was displayed.

  json: cannot unmarshal number 6442450944 into Go struct field .mem_quota of type int

## CLI Version  

6.26.0、6.32.0 32bit

## CC API Endpoint Version  

2.77.0

## Platform & Shell Details  

Windows 8

## Any other relevant information  

I do not have any problem in 64bit CLI.
In 32bit CLI, this issiue happens.
Is this a bug? Or is Windows 32bit CLI specifications?

**Comment by XenoPhex** [comment] 2018-04-30 17:47
@NAGAI-Tsuyoshi can you try running the same command on the latest version of the CF CLI with the 32 bit version?

**Comment by XenoPhex** [comment] 2018-04-30 17:55
Marking this as a duplicate of #1370.

**Closed by XenoPhex** 2018-04-30 17:55 UTC
Labels: unscheduled

**Comment by NAGAI-Tsuyoshi** [comment] 2018-05-01 00:05
I tried using the CLI 6.36.1 32bit version. The result was the same.
