### ISSUE TITLE
Retrieving log information from cf

### ISSUE THREAD

**Issue by srinivasan-git** [cloudfoundry/cli#1982] opened 2020-07-16 12:57 UTC
My application's database connection automatically closing after 15 to 20 days from started time.Last night again app lost its connectivity with database. I want to know which point the app is breaking. So I want to see yesterday logs from cf. It is taking too long time to retrieve logs. I also tried using grep. **Is there any other way to access logs?**.

I am not getting the expected output from **--recent**. It is printing last 30 mins to 1 hour log only.

command : cf log app_name | grep -v RTR

**taking too long time. But no output printed.**

**Comment by heyjcollins** [comment] 2020-07-23 00:01
Hi @srinivasan-git,

Thanks for reaching out to us.  

This sounds like an irritating problem and I'm sorry to hear you're not able to access the logs related to the failure.

The short response here is the cf CLI supports accessing app logs for real-time dev/debugging. Logs aren't stored on the platform long-term by design, so you'd need to set up log egress to another 3rd party system in order to view/search historical logs from your app.

Perhaps this will be helpful: https://help.papertrailapp.com/kb/hosting-services/cloud-foundry/. 

I'm going to close this issue now, but please feel free to reach out to us in the [**#cli slack channel**](https://cloudfoundry.slack.com/archives/C032824SM), or re-open with comments if you would like to continue our discussion.

**Closed by heyjcollins** 2020-07-23 00:01 UTC
Labels: unscheduled
