### ISSUE TITLE
Internal Server Error for release downloads hosted on pivotal.io

### ISSUE THREAD

**Issue by orbanbalage** [cloudfoundry/cli#392] opened 2015-03-25 10:48 UTC
Downloads from the https://github.com/cloudfoundry/cli/releases page are broken - Internal Server Error is displayed.

**Comment by goehmen** [comment] 2015-03-25 21:49
I'm not able to reproduce this.  Are you downloading a binary or installer file?  Which OS?

**Comment by orbanbalage** [comment] 2015-03-26 09:33
All installers & binaries from here:
https://github.com/cloudfoundry/cli/releases/tag/v6.10.0

On Wed, Mar 25, 2015 at 10:49 PM, greg oehmen <notifications@github.com>
wrote:

> I'm not able to reproduce this. Are you downloading a binary or installer
> file? Which OS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/392#issuecomment-86228878>.
>



-- 
Balázs

[image: View my profile on LinkedIn]View Balázs Orbán's profile
<http://www.linkedin.com/in/orbanbalage>
orbanbalage@gmail.com
+421 908 457 183

**Comment by littlbee** [comment] 2015-05-07 12:16
A warning should be put on the download page to use another browser than Chrome until something is fixed.

**Comment by jberkhahn** [comment] 2015-06-10 18:23
This seems to be resolved now. Closing this.

**Closed by jberkhahn** 2015-06-10 18:23 UTC

**Comment by orbanbalage** [comment] 2015-06-11 06:57
I'm on Chrome Version 43.0.2357.124 m
and the issue still persists.

**Comment by cjalmeida** [comment] 2015-08-08 19:42
I confirm the issue. Only in Chrome, Firefox working fine.

**Comment by orbanbalage** [comment] 2016-03-26 10:21
It works for me on Chrome on the Mac. Still need to re-test on Windows.
