### ISSUE TITLE
Link for windows zip download is broken

### ISSUE THREAD

**Issue by cacodev** [cloudfoundry/cli#1819] opened 2019-10-17 11:01 UTC
Attempting to download the CLI for windows and receiving this error:

![image](https://user-images.githubusercontent.com/4412526/67003424-e85d1900-f0ab-11e9-862e-0480d60dc591.png)

**Comment by abbyachau** [comment] 2019-10-17 16:32
Hi there @cacodev thanks for reaching out. It doesn't look like we published the release so I can't point you to the documentation but we have excluded the Windows release in this release because of cert renewal timelines were taking longer than expected. We received confirmation that we have the cert now so will be releasing soon again with Windows support.

**Comment by cacodev** [comment] 2019-10-17 17:54
how long is "soon"?  I have a handful of CI processes that rely on being able to pull the latest cf.exe and I'd like to know if we have to fix those or this will be fixed within a few hours

**Comment by abbyachau** [comment] 2019-10-17 22:43
Hi @cacodev sorry about that - it won't be fixed in a few hours. We hope to have Windows support by next week. We've marked the `6.47.0` as a pre-release.

**Comment by abbyachau** [comment] 2019-10-18 18:19
Updates here for Windows support: https://github.com/cloudfoundry/cli/issues/1820#issuecomment-543828008

**Comment by abbyachau** [comment] 2019-10-21 23:58
@cacodev we've released today again without Windows support - sorry about that. There was a major regression we applied a fix for see issue #1820. The team is currently working on updating our Windows installers now - we hope to get a Windows release out soon (by this week). 

Please let us know if you have any feedback/concerns, thank you.

**Comment by abbyachau** [comment] 2019-10-22 17:31
Hi @cacodev the engs are still working on a release for Windows support. In the meantime, we plan on adding a redirect for Windows to point to 6.46.1, which is the latest known working version.  Here is the story to track: https://www.pivotaltracker.com/story/show/169295723 for the redirect. Let us know if you have any feedback. Thanks. Sorry again about the disruption.

**Comment by abbyachau** [comment] 2019-10-22 19:23
A quick update: we are still working on Windows Support. In the meantime, the cf CLI eng team applied a temporary fix for the Windows issue: links for the latest Windows version temporarily redirects to use cf CLI 6.46.1 which is the last known working version. 

The Linux and OSX installers/binaries are still pointing at cf CLI 6.47.1, which fixes the aforementioned regression for login. Once we have the new Windows cert working, we will release Windows support which will be on par with cf CLI 6.47.1. 

Please reach out if you have any questions or concerns, thanks.

Abby

**Comment by abbyachau** [comment] 2019-10-24 16:29
Hey @cacodev we released [cf CLI 6.47.1](https://github.com/cloudfoundry/cli/releases/tag/v6.47.1) yesterday with Windows support. Sorry again about the interruption. Please let us know if you have any feedback, thanks.

**Comment by abbyachau** [comment] 2019-10-24 21:30
Closing this issue as fixed, please provide any feedback you may have. Thanks.

**Closed by abbyachau** 2019-10-24 21:30 UTC
Labels: unscheduled
