### ISSUE TITLE
Server error, status code: 504, error code: 10001 while cf delete <app>

### ISSUE THREAD

**Issue by kumarganesh2814** [cloudfoundry/cli#1657] opened 2019-05-28 16:25 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

**What happened**
A clear and concise description of what happen.

**Expected behavior**

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf ...`
2. Bind a service `cf bind-service`
3. See error

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running
- version of the CC API Release you are on

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by kumarganesh2814** [comment] 2019-05-28 16:31
Hi Team,

We get issues while doing cf delete <app-name>

Server error, status code: 504, error code: 10001, message: Service instance my-dedicated-redis: The request to the service broker timed out

Can you please help us on the same.

cf version 6.44.0+5de0f0d02.2019-05-01

Best Regards
Ganesh Kumar

**Comment by georgi-lozev** [comment] 2019-05-29 07:24
Hey @kumarganesh2814, thank you very much for raising this issue.

As far as I could understand from the details provided, it looks like you have problem deleting an application and the error message is saying the request to the broker timed out.

To me it looks like you have a bound service instance to your application. 
In this case, when you attempt to delete the application an `unbind`(delete binding) request is made to the broker providing that service instance in order to invalidate any credentials associated with the binding. However, the broker responsible for that instance is currently unavailable/overloaded and could not handle requests(times out). 
I'll suggest you retry that operation after a couple minutes and if the problem still persists try to reach the corresponding team responsible for the broker, because this type of errors are not indicating a CLI problem.

I'll also suggest if you still think it's a CLI problem to elaborate a bit on the steps to reproduce and provide more details for the error you get using the `CF_TRACE` environment variable or the verbose `-v` flag of the CLI.

**Comment by kumarganesh2814** [comment] 2019-05-29 16:40
Thanks @georgi-lozev 
I will check broker logs, I was just assuming there is anything we can do from cf-cli point like adding CF_DIAL_TIMEOUT or cf delete with more option 

I will come back with more details of -v or CF_TRACE

Best Regards
Ganesh

**Comment by georgi-lozev** [comment] 2019-05-30 06:31
The timeout indicated in the error above is not between the CLI as a client and the CC(cloud_controller) as a server, but between CC and the Service Broker managing the service instance, so changing timeouts on the client side should not have effect.

There is another [timeout configuration](https://github.com/cloudfoundry/capi-release/blob/e303bcc6bff610c72110d7c0ff352ce2d8706c47/jobs/cloud_controller_ng/spec#L752) on the CC side which affects this and it could be changed from your platform operators. 
However, I'll say that it has a pretty reasonable default value of 60 seconds and if your broker is healthy and needs more time in the average case to respond to requests the team responsible for the broker should consider supporting [asynchronous broker operations](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#asynchronous-operations).
Today CC supports asynchronous provision, deprovision, update, bind and unbind operations.

**Comment by georgi-lozev** [comment] 2019-06-05 07:49
I'm closing this issue since I don't think it's related/caused by the CLI.

Feel free to re-open/create new one in case the description we provided early is not clear.

**Closed by georgi-lozev** 2019-06-05 07:49 UTC
Labels: sapi, unscheduled
