### ISSUE TITLE
Expired Certitificate Azure Pipeline

### ISSUE THREAD

**Issue by coloso** [cloudfoundry/cli#2991] opened 2024-07-05 08:22 UTC
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ x ] I reviewed open and closed github issues that may be related to my problem.
- [ x ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ x ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I've faced an issue using the Azure pipeline task: "Install Cloud Foundry CLI" while running the pipeline.

**What happened**
In the past the pipeline worked fine, since today it does not run successfully. It seems to be some certificates are expired.
The following logs are shown:

```
2024-07-05T07:46:11.8925222Z ##[section]Starting: Install Cloud Foundry CLI 8.7.10
2024-07-05T07:46:11.8945758Z ==============================================================================
2024-07-05T07:46:11.8945879Z Task         : Cloud Foundry CLI Install
2024-07-05T07:46:11.8945949Z Description  : Install Cloud Foundry command line interface.
2024-07-05T07:46:11.8946051Z Version      : 0.164.0
2024-07-05T07:46:11.8946110Z Author       : Microsoft
2024-07-05T07:46:11.8946906Z Help         : 
2024-07-05T07:46:11.8947013Z ==============================================================================
2024-07-05T07:46:12.1964767Z Downloading: https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8.7.10&source=azure-pipelines
2024-07-05T07:46:12.6198871Z ##[error]Error: Failed to download Cloud Foundry from location https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8.7.10&source=azure-pipelines. Error Error: certificate has expired
2024-07-05T07:46:12.6221257Z ##[section]Finishing: Install Cloud Foundry CLI 8.7.10
```

**Expected behavior**
CLI should be downloaded successfully

**Exact Steps To Reproduce**
Create Azure pipeline task "Install Cloud Foundry CLI" and run pipeline

**Provide more context**
Azure Pipeline, we've tried different versions:
8.7.10, 8.7.9, 8.7.8

I also found a related discussion: https://developercommunity.visualstudio.com/t/Getting-error-in-release-pipelines-in-cl/10692387?sort=active&topics=NodeJS

**Comment by pyttel** [comment] 2024-07-05 08:33
duplicate of #2990. While writing #2990 was written.

**Comment by moleske** [comment] 2024-07-20 05:50
closing as duplicate of #2990

**Closed by moleske** 2024-07-20 05:50 UTC
