### ISSUE TITLE
When i open cf7 or cf8 cli , it immediately closes after flashing few lines

### ISSUE THREAD

**Issue by cah-apoorv-gupta** [cloudfoundry/cli#2392] opened 2023-03-29 12:27 UTC
I have installed cf7 for Windows 64 bit. I unzipped it and ran the application. It got installed. But when i open cf terminal it immedaitely closes. I tried with both cf7 and cf8 . Please get this resolved asap.

**Comment by tremblaysimon** [comment] 2023-04-05 12:56
Could you provide more information about how you try to run the cf CLI?

If you open a command line terminal like cmd.exe and assuming cf.exe is in your PATH, if you type the command `cf --version` what do you get?

Why I ask this it's because if you double-click on cf CLI in an Explorer window it's normal that the cf CLI open and immediately closes like most CLI.

**Comment by a-b** [comment] 2023-04-11 16:44
@cah-apoorv-gupta, we need more info about your environment and detailed reproduction steps. We're running [integration tests on windows](https://github.com/cloudfoundry/cli/blob/1e8e32146afe72aadd25358f9a6faab6c221d0d7/.github/workflows/integration.yml#L157), and behavior you described is not visible there. 

I'm closing this issue for now, but feel free to reopen it with more insights.

**Closed by a-b** 2023-04-11 16:44 UTC
Labels: unscheduled
