### ISSUE TITLE
ssh gobbles stderr

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#737] opened 2016-01-24 21:33 UTC
```
$ cf ssh myapp -c 'echo stdout; echo stderr >&2'
```

only prints out

```
stdout
```

but should print out

```
stdout
stderr
```

**Comment by ematpl** [comment] 2016-01-25 06:24
Hi, @drnic,

This might actually be an issue with how the Diego ssh-proxy transfers stderr for non-interactive commands: I just tried this with the OS X OpenSSH client via `ssh -p 2222 cf:$(cf app MY_APP --guid)/0@ssh.CF_DOMAIN 'echo stdout; echo stderr >&2'` (with the password supplied by `cf ssh-code` output) and observed the same missing 'stderr' in the response. I've filed https://www.pivotaltracker.com/story/show/112308797 for the Diego team to correct this; once it's working for the native SSH clients, we'll see if the CLI has to change anything about its handling of stderr.

Thanks,
Eric

**Comment by drnic** [comment] 2016-01-25 09:49
Thanks Eric!

**Comment by dkoper** [comment] 2016-02-13 06:19
Closing as I understand there is currently nothing the CLI team can do. Looking at the source code we do treat stdout and stdout separately. Feel free to re-open if the issue is not resolved after Diego has addressed it.

**Comment by dkoper** [comment] 2016-04-12 20:55
Tracking this in https://www.pivotaltracker.com/story/show/117485897.

**Comment by dkoper** [comment] 2016-04-27 23:55
@drnic We were not able to reproduce the issue with the latest Diego, so it seems the fix on Diego's side was sufficient. Details of our findings are in the tracker issue I mentioned above.

**Closed by dkoper** 2016-04-27 23:55 UTC
