### ISSUE TITLE
CF push fails with "Error processing app files: remove <TEMP_FOLDER>\unzipped-app160441603\BOOT-INF\lib: The directory is not empty

### ISSUE THREAD

**Issue by tanhung3101** [cloudfoundry/cli#1355] opened 2018-03-29 02:55 UTC
## Command  
 `cf push` 

## What occurred
When pushing a java app from a windows machine once in a while we are treated with error after the upload of file is complete

`FAILED 
Error processing app files: remove <FOLDER_TEMP>\unzipped-app160441603\BOOT-INF\lib: The directory is not empty`

## What you expected to occur
CF CLI should not fail since it can't clean up temp folder, as it's a minor issue to exit the push, it should ignore and continue with the remaining task.
## CLI Version  
cf version  6.35.2+88a03e995.2018-03-15

## CC API Endpoint Version  

v2 (2.75.0)

## Platform & Shell Details  
Windows 10 64-bit with cmd only

## Any other relevant information  

<img width="673" alt="error_cf_push" src="https://user-images.githubusercontent.com/2618088/38070609-0814a872-3347-11e8-85b6-7e55497fb970.png">

**Comment by XenoPhex** [comment] 2018-03-30 20:52
@tanhung3101 By chance, are you running an Anti-Virus, if so, which one/version?

**Comment by tanhung3101** [comment] 2018-03-31 01:34
@XenoPhex : I'm using McAfee v5.0.5.658

And I do see the deprecation warning when pushing my app. So do you think the root cause is my manifest.yml file?

**Comment by XenoPhex** [comment] 2018-04-18 22:14
@tanhung3101 Sorry for the delayed response! Yes the issue is the manifest file contains [deprecated](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated) fields and is falling back on the legacy version of `push` (aka the old crunchy code). The problem you're seeing is due to the old code making multiple copies of your app files into a `TEMP` directory and then your virus scanner wanting to scan these copies for safety reasons. Because of this scanning, when the CF CLI tries to delete them (post upload), the files are still open by the Antivirus and an error occurs.

If you remove all the deprecated fields, `push` will use the new (more performant and safe) version of the code which has a fix for the problem you're seeing. This version only creates a single ZIP file in your `TEMP` dir containing your app bits which is much quicker to scan/requires less work for your anti-virus. Additionally, if `push` can't delete the file, for whatever reason, it'll just display a warning instead of breaking push.

I'm going to close this issue as it's been solved for manifests containing non-deprecated fields. Feel free to continue asking questions/providing feedback. I'll try and stay on top of any replies to this thread. Sorry again for the delay!!

**Closed by XenoPhex** 2018-04-18 22:14 UTC
Labels: unscheduled

**Comment by XenoPhex** [comment] 2018-04-18 22:16
Marking as dupe of #1006.
